import * as E from './production.mjs?v=18-jimenez';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Approved community functions, not a list of new purchasable services.
const places={heroes:['Preparación y salidas','Cazadores y Exploradores'],republica:['Puesto médico','Atención y suministros'],plaza:['Comunidad de paso','Relevos y acuerdos'],libertadores:['Huertos hidropónicos','Cultivo y abastecimiento'],leones:['Talleres','Electricidad y mantenimiento'],vicuna:['Operaciones','Defensa y extracción']};
const roles={'hmorales':'Coordinación de salidas','dr-romero':'Puesto médico','ana':'Comunidad de paso','beatriz':'Huertos e hidroponía','guzman':'Talleres','jimenez':'Jefe de operaciones','adasme':'Encargos de extracción'};
export const knownCommunityContacts=(data,world)=>data.contacts.filter(c=>E.knownMissions(data,world).some(m=>m.npc===c.id));
export function contactCard(c,image){return `<button class="community-contact" data-contact="${esc(c.id)}">${image(c.image,'')}<span><strong>${esc(c.name)}</strong><small>${esc(roles[c.id]||'Contacto de la red')}</small><em>Ver conversación <span aria-hidden="true">›</span></em></span></button>`;}
export function placeHeader(data,world,id,{titleId='dialogTitle',level='h2'}={}){const n=data.nodes[id],info=places[id]||[n.checkpoint?'Punto de control':'Estación del recorrido','Red interior'];return `<header class="community-heading"><div><span class="eyebrow">${esc(info[0])}</span><${level}${titleId?' id="'+titleId+'" tabindex="-1"':''}>${esc(n.name)}</${level}><p>${esc(info[1])}</p></div><span class="community-location">${world.location===id?'Equipo aquí':world.progression.visited.includes(id)?'Visitado':'En la red'}</span></header>`;}
export function communityNetwork(data,world,image){const contacts=knownCommunityContacts(data,world),ids=[...new Set(contacts.map(c=>c.refuge))].sort((a,b)=>Number(b===world.location)-Number(a===world.location));return `<div class="community-body"><header class="community-intro"><span class="eyebrow">LA RED QUE VAS CONOCIENDO</span><h2 id="dialogTitle" tabindex="-1">La gente de los refugios</h2><p>Cada puesto tiene sus propios turnos y necesidades. Estos contactos ya abrieron un trabajo al equipo; las siguientes entregas ampliarán la red.</p></header><div class="community-grid">${ids.map(id=>`<section class="community-place" aria-label="${esc(data.nodes[id].name)}">${placeHeader(data,world,id,{titleId:'',level:'h3'})}<div class="community-people">${contacts.filter(c=>c.refuge===id).map(c=>contactCard(c,image)).join('')}</div><button class="community-place-link" data-community-node="${esc(id)}">Ver comunidad</button></section>`).join('')||'<p class="empty">Todavía no hay contactos conocidos.</p>'}</div></div><div class="dialog-actions"><button data-close="dialog">Volver al mapa</button></div>`;}
export function conversation({portrait,name,place,title,body,note='',image}){return `<div class="community-body"><div class="community-conversation"><figure class="community-portrait">${image(portrait,name)}<figcaption><strong>${esc(name)}</strong><span>${esc(place)}</span></figcaption></figure><article class="community-talk"><span class="eyebrow">${esc(place)}</span><h2 id="dialogTitle" tabindex="-1">${esc(title)}</h2><div class="community-voice">${body}</div>${note?'<p class="community-note">'+esc(note)+'</p>':''}</article></div></div>`;}
