import * as E from './production.mjs?v=20-scarcity';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Presentation only: use live assignments and their accepted departure plans.
export function dossier(data,world,preferred,{image,itemRows,progressHTML}){
 const list=E.knownMissions(data,world).sort((a,b)=>Number(world.paid.includes(a.id))-Number(world.paid.includes(b.id))||data.routes[a.route].edges.length-data.routes[b.route].edges.length);
 const selected=list.find(m=>m.id===preferred)||list.find(m=>m.id===world.run?.mission)||list.find(m=>!world.paid.includes(m.id))||list[0];
 const state=id=>world.paid.includes(id)?'Entregado':world.run?.mission===id&&['active','failed'].includes(world.run.status)?(world.run.status==='failed'?'Interrumpido':'En curso'):'Por asignar';
 const index=`<aside class="contact-index"><span class="eyebrow">RED DE ENCARGOS</span><h2>El siguiente<br>recorrido</h2><p>Solicitudes de los refugios.</p><nav class="index-list" aria-label="Seleccionar expediente">${list.map(m=>`<button class="index-card" data-offer="${m.id}" aria-pressed="${m.id===selected?.id}">${image(m.portrait,'')}<span><strong>${esc(m.name)}</strong><small>${esc(m.issuer)} · ${state(m.id)}</small></span></button>`).join('')}</nav><div class="index-bottom">${String(list.length).padStart(2,'0')} SOLICITUDES<br>LOS MENSAJEROS · 2130</div><details class="conditions"><summary>Cómo abrir más encargos</summary>${progressHTML()}</details></aside>`;
 let reading='<section class="document"><h2 id="dialogTitle" tabindex="-1">Sin encargos conocidos</h2><p>Consulta los contactos de los refugios.</p><button data-close="dialog">Volver al mapa</button></section>';
 if(selected){
 const id=selected.id,m=E.assignment(data,world,id),complete=world.paid.includes(id),active=['active','failed'].includes(world.run?.status),plan=E.departurePlan(data,world,id),number=String(Object.keys(data.missions).indexOf(id)+1).padStart(2,'0');
 const action=complete?`<button data-receipt="${id}" class="primary">Ver resultado</button>`:active?'<button data-resume class="primary">Retomar encargo actual</button>':!E.atMissionOrigin(data,world,id)?`<button data-approach="${id}" class="primary">Revisar traslado</button>`:`<button data-accept="${id}" class="primary">Aceptar encargo</button>`;
 const supplied=Object.values(m.test_loadout||{}).some(n=>n>0);
 reading=`<section class="dossier-reading" aria-label="Expediente seleccionado"><div class="document-topline"><span>EXPEDIENTE ${number} / SOLICITUD</span><span class="tag">${state(id)}</span></div><article class="document"><div class="hero">${image(m.portrait,m.issuer)}<div><span class="eyebrow">${esc(m.issuer)}</span><h2 id="dialogTitle" tabindex="-1">${esc(m.name)}</h2><p class="destination">Destino: ${esc(m.recipient)}</p><span class="file-number">ENCARGO / ${number} · RED INTERIOR</span></div></div><p class="introduction">${esc(m.introduction)}</p><span class="eyebrow statement-label">LO QUE NECESITA ${esc(m.issuer)}</span><p class="statement">«${esc(m.briefing)}»</p><dl class="facts"><div><dt>Recorrido</dt><dd>${plan?.legs??data.routes[m.route].edges.length} <small>tramos</small></dd></div><div><dt>Plazo al aceptar</dt><dd>${plan?.limit??m.time_limit} <small>min</small></dd></div><div><dt>Recompensa</dt><dd>${m.reward.base} <small>Créditos${m.reward.stealth_bonus?' + '+m.reward.stealth_bonus+' sin combates':''}</small></dd></div></dl><section class="cargo"><h3 class="eyebrow">${m.pickup?'CARGA QUE DEBES RECOGER':'CARGA DEL ENCARGO'}</h3>${itemRows({...m.cargo,...m.issued})}</section><section class="cargo provisions"><h3 class="eyebrow">PROVISIONES PRESTADAS AL ACEPTAR</h3>${supplied?itemRows(m.test_loadout):'<p class="empty">Este encargo no entrega comida, agua, munición ni botiquines.</p>'}<p class="loan-note">Lo que no se use vuelve a la red al terminar o devolver el encargo.</p></section><details class="conditions"><summary>Plazo y efecto de la entrega</summary><p>Después del plazo, cada ${m.late_step_minutes} minutos se descuentan ${m.late_penalty} créditos, hasta la mitad del pago. Combatir, descansar, desviarse y saquear consumen tiempo; leer o cerrar el juego no.</p><p>${esc(m.effect)}</p></details>${!complete&&plan?'<p class="preparation">Preparación: '+esc(data.nodes[plan.destination].name)+'. '+plan.legs+' tramos de encargo desde allí. '+(plan.journey?'Primero debes llegar; el traslado tiene su propio tiempo y no descuenta el pago.':'El equipo ya está aquí. Puedes recibir el encargo cuando esté preparado.')+'</p>':''}</article><div class="document-actions"><button data-close="dialog" class="back">Volver al mapa</button><button data-preview-route="${id}">Revisar ruta</button>${action}</div></section>`;
 }
 return {selected:selected?.id,html:`<div class="dossier-layout">${index}${reading}</div>`};
}
