import * as E from './production.mjs';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=p=>new URL(p,import.meta.url).href;
const data=E.prepare(await fetch(new URL('./production.json',import.meta.url)).then(r=>{if(!r.ok)throw Error('No se pudo cargar el catálogo');return r.json();}));
let world=E.createWorld(data,{seed:crypto.getRandomValues(new Uint32Array(1))[0]}), warning='',selected='guzman-01',zoom=1,busy=false,loadError=false,filter='all';
try{const text=localStorage.getItem(data.save_key);if(text)world=E.restore(data,text);}catch(err){loadError=true;warning='El guardado no se pudo abrir. Se conserva intacto. Reinicia los encargos para crear una partida nueva. '+err.message;}
if(world.run)selected=world.run.mission;
const mapSource=await fetch(new URL('./map.svg',import.meta.url)).then(r=>r.text());
$('map').innerHTML=mapSource;const svg=$('map').querySelector('svg');svg.setAttribute('role','group');svg.setAttribute('aria-label','Mapa de refugios y recorrido de Los Mensajeros');
svg.querySelector('#hotspots')?.remove();svg.querySelector('#routeGlow')?.remove();
const ns='http://www.w3.org/2000/svg', layer=document.createElementNS(ns,'g');layer.id='missionLayer';svg.append(layer);
const dialog=$('dialog'),itemDialog=$('itemDialog'),closeTimers=new WeakMap();
function save(){if(loadError)return;try{localStorage.setItem(data.save_key,E.serialize(world));$('saveStatus').textContent='Progreso guardado en este navegador';}catch(err){warning='No se pudo guardar: el almacenamiento del navegador no está disponible.';$('saveStatus').textContent=warning;}}
function sound(path){try{const a=new Audio(asset('../../audio/'+path));a.volume=.22;a.play().catch(()=>{});}catch{}}
function apply(fn,...args){try{if(loadError)throw Error(warning);world=fn(data,world,...args);sound(fn===E.choose&&args[0]==='fire'?'combat/hit-normal-1.mp3':fn===E.choose&&world.run?.status==='completed'?'loot/loot-found.mp3':'ui/click-metal.mp3');save();render();return true;}catch(err){announce(err.message);return false;}}
function announce(text){$('announcement').textContent=text;$('saveStatus').textContent=text;}
function open(kicker,html){clearTimeout(closeTimers.get(dialog));$('dialogKicker').textContent=kicker;$('dialogBody').innerHTML=html;dialog.classList.remove('closing');if(!dialog.open)dialog.showModal();dialog.scrollTop=0;const heading=$('dialogTitle');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
function close(d){if(!d.open)return;clearTimeout(closeTimers.get(d));const finish=()=>{d.close();d.classList.remove('closing');if(d===dialog){const target=$('advanceButton')||$('catalogButton');target?.focus({preventScroll:true});}};if(matchMedia('(prefers-reduced-motion:reduce)').matches){finish();return;}d.classList.add('closing');closeTimers.set(d,setTimeout(finish,160));}
for(const d of [dialog,itemDialog]){d.addEventListener('cancel',e=>{e.preventDefault();close(d);});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close(d);}});}
const risks={low:'Baja',medium:'Media',high:'Alta'};
function image(p,alt,cls=''){return `<img src="${asset(p)}" alt="${esc(alt)}" class="${cls}" loading="eager" decoding="async">`;}
function itemRows(stock){return Object.entries(stock).filter(([,n])=>n>0).map(([id,n])=>`<button class="item-row" data-item="${id}">${image(data.items[id].image,data.items[id].name)}<span>${esc(data.items[id].name)}</span><b>×${n}</b></button>`).join('')||'<p class="empty">Sin carga en esta categoría.</p>';}
function itemModal(id){clearTimeout(closeTimers.get(itemDialog));itemDialog.classList.remove('closing');const i=data.items[id];$('itemBody').innerHTML=`<div class="item-detail">${image(i.image,i.name)}<div><span class="chip">${i.kind==='cargo'?'CARGA PROTEGIDA':'EQUIPO DE MISIÓN'}</span><h2 id="itemTitle">${esc(i.name)}</h2><p>${esc(i.description)}</p><dl><dt>Compra / venta</dt><dd>No disponible en este encargo</dd><dt>Desarme / descarte</dt><dd>No disponible; se conserva para la misión</dd><dt>Uso</dt><dd>${i.kind==='cargo'?'Entrega al destinatario':'Opciones de viaje, descanso o asistencia'}</dd></dl></div></div>`;if(!itemDialog.open)itemDialog.showModal();}
function catalog(){
 const list=Object.values(data.missions).filter(m=>filter==='all'||(filter==='done'?world.paid.includes(m.id):filter==='active'?world.run?.mission===m.id&&['active','failed'].includes(world.run.status):!world.paid.includes(m.id)));
 open('CENTRAL DE ENCARGOS',`<div class="dialog-body" style="padding-bottom:0"><h2 id="dialogTitle">Trabajo entre refugios</h2><p>Un equipo de tres Mensajeros. Siete contactos. Cada entrega ayuda a mantener viva la red.</p><div class="catalog-tabs" role="group" aria-label="Filtrar encargos">${[['all','Todos'],['available','Disponibles'],['active','En curso'],['done','Entregados']].map(([id,label])=>`<button data-filter="${id}" aria-pressed="${filter===id}">${label}</button>`).join('')}</div></div><div class="offer-grid">${list.map(m=>`<article class="offer">${image(m.portrait,m.issuer)}<div class="eyebrow">${esc(m.issuer)} / ${world.paid.includes(m.id)?'ENTREGADO':world.run?.mission===m.id&&world.run.status==='active'?'EN CURSO':data.routes[m.route].edges.length+' TRAMOS'}</div><h3>${esc(m.name)}</h3><p>${esc(m.summary)}</p><small>${m.reward.base}${m.reward.stealth_bonus?' + '+m.reward.stealth_bonus+' por sigilo':''} fichas</small><button data-offer="${m.id}">${world.paid.includes(m.id)?'Ver resultado':'Hablar con '+m.issuer}</button></article>`).join('')||'<p>No hay encargos en esta categoría.</p>'}</div>`);
}
function offer(id){selected=id;const m=data.missions[id],complete=world.paid.includes(id),active=world.run&&['active','failed'].includes(world.run.status);open('ENCARGO / '+m.issuer,`<div class="dialog-body"><div class="hero-brief">${image(m.portrait,m.issuer)}<div><h2 id="dialogTitle">${esc(m.name)}</h2><p>«${esc(m.briefing)}»</p><p class="muted">Destinatario: ${esc(m.recipient)}. Recompensa: ${m.reward.base}${m.reward.stealth_bonus?' + '+m.reward.stealth_bonus+' por evitar combates':''} fichas.</p></div></div><div class="outcome"><div class="eyebrow">${m.pickup?'CARGA QUE DEBES RECOGER':'CARGA Y EQUIPO DEL ENCARGO'}</div>${itemRows({...m.cargo,...m.issued})}</div><p>${esc(m.effect)}</p><p class="muted">La red reúne al equipo en ${esc(data.nodes[data.routes[m.route].nodes[0]].name)}. Dotación de salida: ${Object.entries(m.loadout).map(([k,n])=>n+' '+data.items[k].name.toLowerCase()).join(', ')}. Las compras de reserva se añaden al aceptar y lo que sobre de ellas vuelve a tu reserva al entregar. La dotación prestada se devuelve a la red. Solo puedes llevar un encargo activo.</p></div><div class="dialog-actions"><button data-catalog>Volver a encargos</button><button data-preview-route="${m.id}">Revisar ruta</button>${complete?'<button data-receipt="'+id+'" class="primary">Ver resultado</button>':active?'<button data-resume class="primary">Retomar encargo actual</button>':'<button data-accept="'+id+'" class="primary" '+(loadError?'disabled':'')+'>Aceptar y reunir al equipo</button>'}</div>`);}
function displayRoute(preview){const m=preview?data.missions[preview]:world.run?E.mission(data,world):data.missions[selected],r=data.routes[m.route];open('ITINERARIO / '+m.issuer,`<div class="dialog-body"><h2 id="dialogTitle">${esc(m.name)}</h2><p>Un avance por estación. Los puntos de control conservan un estado de recuperación; cada resolución también se guarda automáticamente.</p><ol class="route-list">${r.nodes.map((id,i)=>{const n=data.nodes[id];return `<li class="${world.run&&i===world.run.index?'active':''}"><span class="number">${String(i+1).padStart(2,'0')}</span><span>${esc(n.name)}</span><small>${n.checkpoint?(n.provisional?'Descanso provisional':'Punto de control'):n.kind==='rescue'?'Objetivo de búsqueda':'Instancia posible'}</small></li>`;}).join('')}</ol>${m.type==='extraction'?'<p class="muted" style="margin-top:18px">El enlace Vicuña Mackenna–Tobalaba representa un corredor completo. Los minutos son tiempo de viaje narrativo; leer o cerrar el juego no consume batería.</p>':''}</div><div class="dialog-actions"><button data-close="dialog" class="primary">Volver al mapa</button></div>`);}
function nodeInfo(id){const n=data.nodes[id];open('PUNTO DEL RECORRIDO',`<div class="dialog-body"><h2 id="dialogTitle">${esc(n.name)}</h2><p>${n.checkpoint?'Punto de control: al llegar queda registrada una posición de recuperación.':'Estación o punto de instancia: al avanzar puede aparecer calma, una decisión, una amenaza o un hallazgo.'}</p>${n.rest?'<p>Descanso opcional: consume 1 ración y 1 agua; recupera 25 puntos de condición. Una vez por visita.</p>':''}${n.provisional?'<p class="muted">Puesto de apoyo temporal; no es un refugio permanente.</p>':''}<p class="good">${id==='plaza'&&world.effects.includes('guzman-01')?'Las torretas de la salida vuelven a girar y detectar movimiento.':id==='uchile'&&world.effects.includes('ana-01')?'Acuerdo de paso confirmado: tienes un descanso adicional en esta posta.':''}</p><div class="contact-list">${data.contacts.filter(c=>c.refuge===id).map(c=>`<button data-contact="${c.id}">${image(c.image,c.name)}<span>${esc(c.name)} · hablar</span></button>`).join('')}</div><p>Consultar el mapa no mueve al grupo.</p></div><div class="dialog-actions"><button data-close="dialog" class="primary">Volver</button></div>`);}
function restModal(){open('PUNTO DE DESCANSO',`<div class="dialog-body"><h2 id="dialogTitle">Recuperar al grupo</h2><p>Descansar en ${esc(E.here(data,world).name)} consume 1 ración y 1 agua, recupera hasta 25 puntos y avanza 10 minutos narrativos. Si el inhibidor sigue encendido, también gasta batería.</p><p>El punto de control se actualiza después del descanso.</p></div><div class="dialog-actions"><button data-close="dialog">Continuar sin descansar</button><button data-rest-confirm class="primary">Descansar</button></div>`);}
function receipt(id=world.run?.mission){const r=world.completed[id];if(!r)return;open('ENCARGO ENTREGADO',`<div class="dialog-body"><div class="eyebrow">${esc(r.recipient)}</div><h2 id="dialogTitle">${esc(data.missions[id].name)}</h2><p>«${esc(r.dialogue)}»</p><div class="outcome"><span>Recompensa</span><strong>${r.amount} fichas</strong><span>${r.combats} enfrentamientos · ${r.evaded} encuentros evitados</span></div><p>${esc(r.effect||'')}</p><p>Entrega registrada. +35 XP para cada Mensajero. Puedes gastar las fichas en abastecimiento y recuperar al equipo. La recompensa se abona una sola vez.</p></div><div class="dialog-actions"><button data-close="dialog">Ver mapa</button><button data-catalog class="primary">Otros encargos</button></div>`);}
function pendingModal(){const r=world.run,p=r?.pending;if(!p||r.status!=='active')return;
 const e=E.eventFor(data,world);let title=e?.title||'',text=e?.text||'',art='../../backgrounds/station-ruins.webp',extra='';
 if(p.combat){const c=p.combat,member=r.party[c.actor],actor=data.crew.find(x=>x.id===member.id);title='Turno de '+actor.name;text='Selecciona un objetivo y una acción. Cada Mensajero actúa una vez; después responde el enemigo.';extra=`<div class="combat-enemies">${c.enemies.map((en,i)=>`<button data-target="${i}" class="enemy ${i===c.target?'targeted':''}" ${en.hp<=0?'disabled':''} aria-pressed="${i===c.target}">${image(en.image,en.name)}<strong>${esc(en.name)}</strong><span>${en.hp} / ${en.maxHp} HP</span></button>`).join('')}</div><div class="combat-team">${r.party.map((a,i)=>`<div class="${i===c.actor?'current-actor':''}">${image(data.crew[i].image,data.crew[i].name)}<b>${data.crew[i].name.split(' ')[0]}</b><span>${a.hp} / ${a.maxHp} HP</span></div>`).join('')}</div><p>Ronda ${c.round} · Munición: ${r.supplies.ammo556||0} · ${r.log.slice(-3).map(esc).join(' ')}</p>`;}
 else if(p.category==='checkpoint'){title='Un lugar para detenerse';text='Llegan a '+data.nodes[p.to].name+'. Al entrar se registra el punto de control. Pueden descansar si tienen provisiones.';}
 else if(p.category==='rescue'){title='El compañero está aquí';text=p.injured?'El operativo está consciente, pero una lesión le impide caminar. Tendrán que cargarlo de vuelta.':'El operativo está agotado, pero puede caminar con ayuda. Necesita compañía para volver.';extra='<p>Asistirlo consume provisiones. Cargarlo añade desgaste y tiempo; Bruno reduce el esfuerzo mientras pueda ayudar. No reduce la recompensa.</p>';}
 else if(p.category==='delivery'){title='El destinatario espera';text=E.mission(data,world).delivery_text;}
 const buttons=E.options(data,world).map(o=>`<button data-choice="${o.id}" ${!E.optionAvailable(world,o)?'disabled':''} class="${o.combat?'danger':''}">${esc(o.label)}</button>`).join('');
 open('EN RUTA / '+data.nodes[p.to].name,`<div class="dialog-body">${p.combat?'':image(art,'Escena del recorrido','event-art')}<div class="eyebrow">${p.combat?'CONTACTO ARMADO':({quiet:'PASO TRANQUILO',decision:'DECISIÓN',hostile:'CONTACTO HOSTIL',opportunity:'HALLAZGO',checkpoint:'PUNTO DE CONTROL',rescue:'EXTRACCIÓN',delivery:'ENTREGA'})[p.category]}</div><h2 id="dialogTitle">${esc(title)}</h2><p>${esc(text)}</p>${extra}${p.category==='hostile'&&r.supplies.jammer&&r.battery>0?`<button data-toggle-jammer>Inhibidor ${r.jammerOn?'activo':'apagado'} · ${r.battery} min · ${r.jammerOn?'apagar':'encender'}</button>`:''}${p.category==='hostile'&&!p.combat?'<p class="muted">Evitar el contacto conserva la bonificación de sigilo. Si retrocedes, el mismo paso seguirá pendiente. Combatir aumenta la vigilancia de esta ruta.</p>':''}<div class="choices">${buttons}</div></div>`);
}
function pathFor(edge){const a=data.nodes[edge.from],b=data.nodes[edge.to];return edge.path||`M${a.x} ${a.y}L${b.x} ${b.y}`;}
function svgEl(tag,attrs){const el=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,String(v));return el;}
function mapRender(){const m=world.run?E.mission(data,world):data.missions[selected],rt=data.routes[m.route];layer.replaceChildren();
 rt.edges.forEach(e=>layer.append(svgEl('path',{d:pathFor(e),class:'route-selected'})));
 [...new Set([...rt.nodes,...data.contacts.map(c=>c.refuge)])].filter(id=>data.nodes[id]).forEach(id=>{const n=data.nodes[id],visited=world.run&&rt.nodes.slice(0,world.run.index+1).includes(id);const el=svgEl(n.checkpoint?'rect':'circle',n.checkpoint?{x:n.x-7,y:n.y-7,width:14,height:14}:{cx:n.x,cy:n.y,r:5});el.setAttribute('class',(n.checkpoint?'control-point':'instance-point')+(visited?' point-visited':''));el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',n.name+(n.checkpoint?', punto de control':''));const t=svgEl('title',{});t.textContent=n.name;el.append(t);el.addEventListener('click',()=>nodeInfo(id));el.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();nodeInfo(id);}});layer.append(el);if(['ines','nunoa','estadio','nuble','biobio'].includes(id)){const label=svgEl('text',{x:n.x+(n.x===780?15:0),y:n.y+(n.x===780?4:24),class:'instance-label','text-anchor':n.x===780?'start':'middle'});label.textContent=n.name;layer.append(label);}});
 if(world.run){const r=world.run,n=data.nodes[rt.nodes[r.index]],marker=svgEl('circle',{cx:n.x,cy:n.y,r:9,class:'messenger'});marker.id='messenger';if(r.pending){const path=svgEl('path',{d:pathFor(rt.edges[r.index])});layer.append(path);const mid=path.getPointAtLength(path.getTotalLength()*.55);marker.setAttribute('cx',mid.x);marker.setAttribute('cy',mid.y);path.remove();}layer.append(marker);}
}
function render(){const r=world.run,m=r?E.mission(data,world):data.missions[selected],node=r?E.here(data,world):data.nodes[data.routes[m.route].nodes[0]];
 $('brief').innerHTML=`<div class="mission-portrait">${image(m.portrait,m.issuer)}<span class="portrait-name">${esc(m.issuer)}</span></div><span class="chip">${r?({active:'EN CURSO',completed:'ENTREGADO',failed:'VIAJE INTERRUMPIDO',abandoned:'ABANDONADO'})[r.status]:'DISPONIBLE'}</span><h2>${esc(m.name)}</h2><p>${esc(m.summary)}</p><div class="mission-meta">Destinatario<strong>${esc(m.recipient)}</strong></div><button class="primary" data-offer="${m.id}">Ver encargo</button>${r&&['active','failed'].includes(r.status)?'<button class="text-button" data-abandon>Devolver encargo</button>':''}`;
 $('location').textContent=r?.pending?'En tránsito a '+data.nodes[r.pending.to].name:node.name;mapRender();
 $('crewSummary').innerHTML=crewHTML();$('cargo').innerHTML=itemRows(r?r.cargo:m.cargo);$('supplies').innerHTML=itemRows(r?r.supplies:world.stock);
 $('status').innerHTML=r?`<div class="meter-label"><span>Resistencia del viaje</span><b>${r.condition}%</b></div><div class="progress"><span style="width:${r.condition}%"></span></div><div class="status-data"><div>Tiempo narrativo<b>${r.minutes} min</b></div><div>Enfrentamientos<b>${r.combats}</b></div><div>Encuentros evitados<b>${r.evaded}</b></div><div>Fichas<b>${world.credits}</b></div></div>${r.supplies.jammer?`<button id="jammerButton" ${r.status!=='active'||!r.battery?'disabled':''}>Inhibidor ${r.jammerOn?'activo':'apagado'} · ${r.battery} min</button>`:''}${r.rescued?'<p class="good" style="margin-top:14px">Compañero: '+(r.rescued.mode==='carry'?'transportado por el grupo':'caminando acompañado')+'</p>':''}`:'<p class="muted">Prepara un encargo para iniciar el recorrido.</p>';
 const edge=r?E.nextEdge(data,world):null,risk=edge?E.effectiveRisk(data,world,edge):'low';
 $('travel').innerHTML=!r?'<p>El recorrido aparece sobre el mapa. Acepta el encargo para comenzar.</p><button data-catalog class="primary">Consultar encargos</button>':r.status==='completed'?'<p class="good">Encargo entregado. El grupo está en '+esc(node.name)+'.</p><button data-receipt="'+r.mission+'" class="primary">Ver resultado</button>':r.status==='failed'?'<p>El grupo no puede continuar. El reintento conserva los encuentros ya sorteados y la vigilancia provocada.</p><button id="retryButton" class="primary">Reintentar desde '+esc(data.nodes[r.checkpoint.node].name)+'</button>':r.status==='abandoned'?'<p>Encargo devuelto a la red.</p><button data-catalog class="primary">Consultar encargos</button>':`<div class="travel-head"><span>${r.index} / ${E.route(data,world).edges.length} avances · ${esc(edge?.line||'Destino')}</span><span class="risk-${risk}">Amenaza ${risks[risk]}${world.regions[edge?.region]?' · vigilancia aumentada':''}</span></div><div class="progress"><span style="width:${100*r.index/E.route(data,world).edges.length}%"></span></div><div class="travel-actions"><button id="advanceButton" class="primary" ${busy?'disabled':''}>${r.pending?'Resolver instancia':'Avanzar a '+esc(data.nodes[edge.to].name)}</button>${!r.pending&&node.rest?`<button id="restButton" ${r.condition>=100||(r.rested.includes(r.index)&&!(world.effects.includes('ana-01')&&node.id==='uchile'&&!r.used.anaRest))||!(r.supplies.food>0&&r.supplies.water>0)?'disabled':''}>Descansar</button>`:''}</div><p class="muted" style="font-size:11px;margin:12px 0 0">Último punto de control: ${esc(data.nodes[r.checkpoint.node].name)}${edge?.kind==='grouped_corridor'?' · corredor con estaciones intermedias agrupadas':''}</p>`;
 $('journal').innerHTML=(r?.log||['Las estaciones marcan el recorrido. El peligro se conoce; el encuentro se descubre al avanzar.']).slice(-10).map(x=>'<p>'+esc(x)+'</p>').join('');$('journal').scrollTop=$('journal').scrollHeight;
 if(warning)$('saveStatus').textContent=warning;
}
function animateAdvance(){if(busy)return;if(world.run?.pending){pendingModal();return;}if(!apply(E.advance))return;if(world.run.status!=='active')return;busy=true;$('advanceButton').disabled=true;const edge=E.nextEdge(data,world),p=svgEl('path',{d:pathFor(edge)});layer.append(p);const marker=$('messenger'),length=p.getTotalLength(),start=performance.now(),duration=matchMedia('(prefers-reduced-motion:reduce)').matches?0:650;
 function step(now){const f=duration?Math.min(1,(now-start)/duration):1,point=p.getPointAtLength(length*.55*f);marker?.setAttribute('cx',point.x);marker?.setAttribute('cy',point.y);if(f<1)requestAnimationFrame(step);else{p.remove();busy=false;render();pendingModal();}}requestAnimationFrame(step);
}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;
 if(b.dataset.close){close($(b.dataset.close));return;}if(b.dataset.item){itemModal(b.dataset.item);return;}if(b.hasAttribute('data-catalog')||b.id==='catalogButton'){catalog();return;}
 if(b.dataset.offer){offer(b.dataset.offer);return;}if(b.dataset.accept){if(apply(E.start,b.dataset.accept)){close(dialog);announce('Encargo aceptado. Revisa el mapa y avanza por las estaciones.');}return;}
 if(b.hasAttribute('data-resume')){render();close(dialog);return;}if(b.dataset.receipt){receipt(b.dataset.receipt);return;}
 if(b.hasAttribute('data-toggle-jammer')){if(apply(E.toggleJammer))pendingModal();return;}
 if(b.dataset.choice){if(apply(E.choose,b.dataset.choice)){if(world.run.status==='completed')receipt();else if(world.run.pending&&world.run.status==='active')pendingModal();else close(dialog);}return;}
 if(b.id==='advanceButton'){animateAdvance();return;}if(b.id==='routeButton'){displayRoute();return;}if(b.id==='restButton'){restModal();return;}
 if(b.hasAttribute('data-rest-confirm')){if(apply(E.rest))close(dialog);return;}if(b.id==='jammerButton'){apply(E.toggleJammer);return;}if(b.id==='retryButton'){apply(E.retry);return;}
 if(b.hasAttribute('data-abandon')){open('INTERRUMPIR ENCARGO',`<div class="dialog-body"><h2 id="dialogTitle">¿Devolver este encargo?</h2><p>El encargo no se entregará ni pagará. La vigilancia provocada permanece. Podrás iniciar otro encargo.</p></div><div class="dialog-actions"><button data-close="dialog">Seguir viajando</button><button data-abandon-confirm class="danger">Devolver encargo</button></div>`);return;}
 if(b.hasAttribute('data-abandon-confirm')){if(apply(E.abandon))close(dialog);return;}
 if(b.id==='resetCouriers'){open('REINICIAR ENCARGOS',`<div class="dialog-body"><h2 id="dialogTitle">¿Empezar una nueva red de encargos?</h2><p>Se reinician únicamente las entregas, el equipo, las fichas y la vigilancia de Los Mensajeros. La historia principal conserva su partida. La central conservará una copia del guardado anterior en este navegador.</p></div><div class="dialog-actions"><button data-close="dialog">Conservar progreso</button><button data-reset-confirm class="danger">Reiniciar encargos</button></div>`);return;}
 if(b.hasAttribute('data-reset-confirm')){try{const previous=localStorage.getItem(data.save_key);if(previous)localStorage.setItem(data.save_key+'.backup',previous);}catch(err){announce('No se pudo conservar la copia anterior. No se ha reiniciado.');return;}world=E.createWorld(data,{seed:crypto.getRandomValues(new Uint32Array(1))[0]});warning='';loadError=false;$('bootStatus').hidden=true;save();render();help();return;}
 if(b.dataset.filter){filter=b.dataset.filter;catalog();return;}
 if(b.dataset.previewRoute){displayRoute(b.dataset.previewRoute);return;}
 if(b.dataset.contact){contact(b.dataset.contact);return;}
 if(b.dataset.target!==undefined){if(apply(E.target,Number(b.dataset.target)))pendingModal();return;}
 if(b.id==='helpButton'){help();return;}
 if(b.hasAttribute('data-help-done')){if(loadError){announce(warning);close(dialog);return;}world.helpSeen=true;save();catalog();return;}
 if(b.id==='contactsButton'){contacts();return;}
 if(b.dataset.refuge){nodeInfo(b.dataset.refuge);return;}
 if(b.id==='crewButton'){crewModal();return;}
 if(b.id==='supplyButton'){shop();return;}
 if(b.dataset.craft){if(apply(E.craft,b.dataset.craft))shop();return;}
 if(b.dataset.buy){if(apply(E.buy,b.dataset.buy))shop();return;}
 if(b.hasAttribute('data-recover')){if(apply(E.recover))crewModal();return;}
 if(b.dataset.heal){if(apply(E.heal,b.dataset.heal))crewModal();return;}
 if(['zoomIn','zoomOut','resetMap'].includes(b.id)){zoom=b.id==='resetMap'?1:Math.max(1,Math.min(2.5,zoom+(b.id==='zoomIn'?.25:-.25)));const n=world.run?E.here(data,world):data.nodes.leones,w=1090/zoom,h=704/zoom;svg.style.touchAction=zoom>1?'none':'pan-y';svg.setAttribute('viewBox',`${Math.max(0,Math.min(1090-w,n.x-w/2))} ${Math.max(0,Math.min(704-h,n.y-h/2))} ${w} ${h}`);}
});
$('bootStatus').hidden=!loadError;if(loadError)$('bootStatus').textContent=warning;render();if(loadError)announce(warning);else if(!world.helpSeen)help();else if(!world.run)catalog();window.NeoCourierBack=()=>{if(itemDialog.open){close(itemDialog);return true;}if(dialog.open){close(dialog);return true;}return false;};

function crewHTML(){const members=world.run&&['active','failed'].includes(world.run.status)?world.run.party:world.crew;return `<div class="crew-mini">${members.map((a,i)=>`<button data-crew="${a.id}" onclick="document.getElementById('crewButton').click()">${image(data.crew[i].image,data.crew[i].name)}<span><b>${data.crew[i].name.split(' ')[0]}</b><small>${a.hp}/${a.maxHp} HP · Nv. ${a.level}</small></span></button>`).join('')}</div>`;}
function crewModal(){const active=world.run?.status==='active',members=active?world.run.party:world.crew;open('LOS MENSAJEROS',`<div class="dialog-body"><h2 id="dialogTitle">Nadie cruza solo</h2><p>Los tres viajan juntos. Sus talentos permiten resolver los encargos de distintas maneras. Cada entrega otorga 35 XP; cada 60 XP ganan un nivel y 5 HP máximos.</p><div class="crew-cards">${members.map((c,i)=>{const d=data.crew[i];return `<article>${image(d.image,d.name)}<h3>${d.name}</h3><span class="chip">${d.role}</span><p>${d.description}</p><b>${c.hp}/${c.maxHp} HP · Nivel ${c.level} · ${c.xp}/60 XP</b>${active?`<button data-heal="${c.id}" ${world.run.pending||!world.run.supplies.medkit||c.hp>=c.maxHp?'disabled':''}>Usar botiquín</button>`:''}</article>`;}).join('')}</div></div><div class="dialog-actions"><button data-close="dialog">Volver</button>${!active?'<button data-recover '+(world.credits<8||world.run?.status==='failed'?'disabled':'')+'>Recuperar equipo · 8 fichas</button>':''}</div>`);}
function shop(){const allowed=E.canResupply(data,world),stock=world.run?.status==='active'?world.run.supplies:world.stock;open('ABASTECIMIENTO DE LA RED',`<div class="dialog-body"><h2 id="dialogTitle">Preparar el siguiente tramo</h2><p>${world.credits} fichas disponibles. ${allowed?'Las compras durante el viaje van al equipo; entre encargos quedan en reserva para la siguiente salida.':'Llega a un punto de control para recibir suministros.'}</p><div class="shop-grid">${data.shop.map(s=>`<article>${image(data.items[s.id].image,data.items[s.id].name)}<h3>${data.items[s.id].name} ×${s.qty}</h3><p>${data.items[s.id].description}</p><button data-buy="${s.id}" ${!allowed||world.credits<E.price(data,world,s.id)?'disabled':''}>${E.price(data,world,s.id)} fichas</button></article>`).join('')}</div><h3 class="craft-heading">Fabricar en la posta</h3><div class="shop-grid">${data.recipes.map(r=>`<article><h3>${data.items[r.id].name}</h3><p>${Object.entries(r.cost).map(([id,n])=>n+' '+data.items[id].name.toLowerCase()).join(' + ')}</p><button data-craft="${r.id}" ${!allowed||!Object.entries(r.cost).every(([id,n])=>(stock[id]||0)>=n)?'disabled':''}>Fabricar</button></article>`).join('')}</div></div><div class="dialog-actions"><button data-close="dialog">Volver al mapa</button></div>`);}
function contact(id){const c=data.contacts.find(c=>c.id===id),m=Object.values(data.missions).find(m=>m.npc===id);open('CONTACTO DEL REFUGIO',`<div class="dialog-body"><div class="hero-brief">${image(c.image,c.name)}<div><h2 id="dialogTitle">${esc(c.name)}</h2><p>${esc(m.briefing)}</p><span class="chip">${esc(data.nodes[c.refuge]?.name||'Red de refugios')}</span></div></div></div><div class="dialog-actions"><button data-close="dialog">Volver al mapa</button><button data-offer="${m.id}" class="primary">${world.paid.includes(m.id)?'Consultar entrega':'Ver encargo'}</button></div>`);}
function help(){open('GUÍA DE ENCARGOS',`<div class="dialog-body"><h2 id="dialogTitle">Cada entrega sostiene un refugio</h2><div class="help-sections"><section><h3>1. Elige y prepara</h3><p>Habla con un contacto desde el mapa o la central. Revisa destinatario, ruta y recompensa. Rocío, Tomás y Bruno viajan juntos; la red los reúne en el origen del encargo y ofrece atención básica hasta un 40% de HP. Recuperarse por completo cuesta fichas. Solo hay un encargo activo.</p></section><section><h3>2. Recorre las estaciones</h3><p>Avanza por la ruta marcada. Cada tramo puede traer calma, una decisión, un hallazgo o enemigos. El resultado se guarda: recargar no cambia el encuentro. El tramo destruido de Baquedano no se puede cruzar.</p></section><section><h3>3. Cuida al equipo y la carga</h3><p>La resistencia mide el desgaste del viaje; los HP son la salud de cada Mensajero. Descansar cuesta 1 ración y 1 agua, recupera 25 de resistencia y 12 HP por persona. Los botiquines recuperan 24 HP. La carga protegida solo se entrega: no se vende ni se desarma.</p></section><section><h3>4. Evita, enfrenta o retrocede</h3><p>Rocío encuentra un paso silencioso y Tomás evita un barrido electrónico una vez por encargo. Puedes usar humo, señuelos y trampas de demora. En las postas se fabrican señuelos con 1 electrónica y 1 pieza metálica, o trampas con 2 piezas metálicas. En combate elige objetivo y acción para cada Mensajero. Retirarte conserva heridas y carga y vuelve al andén anterior; el paso sigue pendiente. Pelear aumenta la vigilancia aunque después escapes.</p></section><section><h3>5. Entrega y mejora</h3><p>Llegar no basta: entrega al destinatario. La recompensa se cobra una sola vez y sirve para comprar recursos. Adasme paga más si no combates. Los resultados de otros encargos abren descuentos o ayudas para próximos viajes.</p></section><section><h3>Tu historia sigue esperando</h3><p>Usa «Volver a actividades» para retomar la campaña. Ambos progresos se conservan por separado. El inhibidor de los encargos tiene 20 minutos narrativos: solo se gastan al actuar con él encendido. Leer, cerrar ventanas o salir no gasta batería. Si el grupo cae, vuelve al último punto de control; la vigilancia provocada permanece.</p></section></div></div><div class="dialog-actions"><button data-help-done class="primary">Entendido · ver encargos</button></div>`);}

// Pan the existing SVG after zooming; keep node clicks and vertical mobile scrolling at base zoom.
let mapDrag=null,suppressMapClick=false;
svg.addEventListener('pointerdown',e=>{if(zoom<=1)return;const v=svg.viewBox.baseVal;mapDrag={id:e.pointerId,x:e.clientX,y:e.clientY,vx:v.x,vy:v.y,w:v.width,h:v.height,moved:false};svg.setPointerCapture(e.pointerId);});
svg.addEventListener('pointermove',e=>{if(!mapDrag||mapDrag.id!==e.pointerId)return;const b=svg.getBoundingClientRect(),dx=(e.clientX-mapDrag.x)*mapDrag.w/b.width,dy=(e.clientY-mapDrag.y)*mapDrag.h/b.height;if(Math.abs(dx)+Math.abs(dy)>4)mapDrag.moved=true;svg.setAttribute('viewBox',`${Math.max(0,Math.min(1090-mapDrag.w,mapDrag.vx-dx))} ${Math.max(0,Math.min(704-mapDrag.h,mapDrag.vy-dy))} ${mapDrag.w} ${mapDrag.h}`);});
svg.addEventListener('pointerup',()=>{suppressMapClick=!!mapDrag?.moved;mapDrag=null;});
svg.addEventListener('pointercancel',()=>{mapDrag=null;});
svg.addEventListener('click',e=>{if(suppressMapClick){e.stopImmediatePropagation();suppressMapClick=false;}},true);

function contacts(){open('RED DE REFUGIOS',`<div class="dialog-body"><h2 id="dialogTitle">Comunidades y contactos</h2><p>Consulta sus funciones y habla con los encargados. Abrir una ficha no desplaza al equipo.</p><div class="contact-list">${data.contacts.map(c=>`<button data-contact="${c.id}">${image(c.image,c.name)}<span><strong>${esc(c.name)}</strong><small>${esc(data.nodes[c.refuge]?.name||'Red de refugios')}</small></span></button>`).join('')}</div></div><div class="dialog-actions"><button data-close="dialog">Volver al mapa</button></div>`);}
