import * as E from './production.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=p=>new URL(p,import.meta.url).href;
const data=E.prepare(await fetch(new URL('./production.json',import.meta.url)).then(r=>{if(!r.ok)throw Error('No se pudo cargar el catálogo');return r.json();}));
let world=E.createWorld(data,{seed:crypto.getRandomValues(new Uint32Array(1))[0]}),warning='',selected='guzman-01',zoom=1,busy=false,loadError=false,filter='all',selectedCrew='rocio',selectedVendor='mara',selectedLooter='rocio';
try{const text=localStorage.getItem(data.save_key);if(text)world=E.restore(data,text);}catch(err){loadError=true;warning='El guardado no se pudo abrir. Se conserva intacto. '+err.message;}
if(world.run)selected=world.run.mission;
const mapSource=await fetch(new URL('./map.svg',import.meta.url)).then(r=>r.text());$('map').innerHTML=mapSource;const svg=$('map').querySelector('svg');svg.setAttribute('role','group');svg.setAttribute('aria-label','Mapa de refugios y recorrido de Los Mensajeros');svg.querySelector('#hotspots')?.remove();svg.querySelector('#routeGlow')?.remove();
const ns='http://www.w3.org/2000/svg',layer=document.createElementNS(ns,'g');layer.id='missionLayer';svg.append(layer);
const dialog=$('dialog'),itemDialog=$('itemDialog'),risks={low:'Baja',medium:'Media',high:'Alta'};
function save(){if(loadError)return;try{localStorage.setItem(data.save_key,E.serialize(world));$('saveStatus').textContent='Progreso guardado en este navegador';}catch{$('saveStatus').textContent='No se pudo guardar en este navegador.';}}
function sound(path){try{const a=new Audio(asset('../../audio/'+path));a.volume=.22;a.play().catch(()=>{});}catch{}}
function apply(fn,...args){try{if(loadError)throw Error(warning);world=fn(data,world,...args);save();render();return true;}catch(err){announce(err.message);return false;}}
function announce(text){$('announcement').textContent=text;$('saveStatus').textContent=text;}
function image(p,alt,cls=''){return `<img src="${asset(p)}" alt="${esc(alt)}" class="${cls}" loading="eager" decoding="async">`;}
function open(kicker,html){$('dialogKicker').textContent=kicker;$('dialogBody').innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;$('dialogTitle')?.focus({preventScroll:true});}
function close(d){if(d.open)d.close();}
for(const d of [dialog,itemDialog]){d.addEventListener('cancel',e=>{e.preventDefault();close(d);});}
function party(){return world.run?.status==='active'?world.run.party:world.crew;}
function member(id){return party().find(x=>x.id===id);}
function def(id){return data.crew.find(x=>x.id===id);}
function dname(id){return def(id).name.split(' ')[0];}
function totals(){return party().reduce((out,c)=>{for(const x of c.bag)out[x.id]=(out[x.id]||0)+x.qty;return out;},{});}
function itemRows(stock){return Object.entries(stock||{}).filter(([,n])=>n>0).map(([id,n])=>`<button class="item-row" data-item="${id}">${image(data.items[id].image,data.items[id].name)}<span>${esc(data.items[id].name)}</span><b>×${n}</b></button>`).join('')||'<p class="empty">Sin objetos en esta categoría.</p>';}
function itemModal(id){const i=data.items[id];$('itemBody').innerHTML=`<div class="item-detail">${image(i.image,i.name)}<div><span class="chip">${i.kind==='cargo'?'CARGA PROTEGIDA':i.kind.toUpperCase()}</span><h2 id="itemTitle">${esc(i.name)}</h2><p>${esc(i.description)}</p><dl><dt>Comercio</dt><dd>${i.kind==='cargo'?'No disponible':'Mara o el Armero en Los Héroes · venta '+E.salePrice(data,id)+' fichas'}</dd><dt>Fabricación</dt><dd>Los Mensajeros no fabrican ni desarman</dd><dt>Uso</dt><dd>${i.slot?'Puede equiparse desde la ficha del Mensajero':i.heal?'Puede usarse desde su mochila':i.kind==='cargo'?'Entrega al destinatario':'Viaje, combate o comercio'}</dd></dl></div></div>`;if(!itemDialog.open)itemDialog.showModal();}
function catalog(){
 const list=Object.values(data.missions).filter(m=>filter==='all'||(filter==='done'?world.paid.includes(m.id):filter==='active'?world.run?.mission===m.id&&['active','failed'].includes(world.run.status):!world.paid.includes(m.id)));
 const sample=data.missions['guzman-01'];open('CENTRAL DE ENCARGOS',`<div class="dialog-body"><h2 id="dialogTitle" tabindex="-1">Trabajo entre refugios</h2><p>Después del plazo se descuentan ${sample.late_penalty} fichas por cada ${sample.late_step_minutes} minutos adicionales, hasta la mitad del pago.</p><div class="catalog-tabs">${[['all','Todos'],['available','Disponibles'],['active','En curso'],['done','Entregados']].map(([id,label])=>`<button data-filter="${id}" aria-pressed="${filter===id}">${label}</button>`).join('')}</div><div class="offer-grid">${list.map(m=>`<article class="offer">${image(m.portrait,m.issuer)}<div class="eyebrow">${esc(m.issuer)} / ${world.paid.includes(m.id)?'ENTREGADO':data.routes[m.route].edges.length+' TRAMOS'}</div><h3>${esc(m.name)}</h3><p>${esc(m.summary)}</p><small>Plazo ${m.time_limit} min · ${m.reward.base}${m.reward.stealth_bonus?' + '+m.reward.stealth_bonus+' por sigilo':''} fichas</small><button data-offer="${m.id}">${world.paid.includes(m.id)?'Ver resultado':'Hablar con '+m.issuer}</button></article>`).join('')||'<p>No hay encargos en esta categoría.</p>'}</div></div>`);
}
function offer(id){
 selected=id;const m=data.missions[id],complete=world.paid.includes(id),active=world.run&&['active','failed'].includes(world.run.status);
 open('ENCARGO / '+m.issuer,`<div class="dialog-body"><div class="hero-brief">${image(m.portrait,m.issuer)}<div><h2 id="dialogTitle" tabindex="-1">${esc(m.name)}</h2><p>«${esc(m.briefing)}»</p><p class="muted">Destino: ${esc(m.recipient)} · Plazo: ${m.time_limit} minutos · Recompensa: ${m.reward.base}${m.reward.stealth_bonus?' + '+m.reward.stealth_bonus+' sin combates':''} fichas.</p><p>Después del plazo, cada ${m.late_step_minutes} minutos restan ${m.late_penalty} fichas. Combatir, descansar, desviarse y saquear consumen tiempo; leer o cerrar el juego no.</p></div></div><div class="outcome"><div class="eyebrow">${m.pickup?'CARGA QUE DEBES RECOGER':'CARGA DEL ENCARGO'}</div>${itemRows({...m.cargo,...m.issued})}</div><p>${esc(m.effect)}</p></div><div class="dialog-actions"><button data-catalog>Volver</button><button data-preview-route="${m.id}">Revisar ruta</button>${complete?'<button data-receipt="'+id+'" class="primary">Ver resultado</button>':active?'<button data-resume class="primary">Retomar encargo actual</button>':'<button data-accept="'+id+'" class="primary">Aceptar encargo</button>'}</div>`);
}
function displayRoute(preview){const m=preview?data.missions[preview]:world.run?E.mission(data,world):data.missions[selected],r=data.routes[m.route];open('ITINERARIO / '+m.issuer,`<div class="dialog-body"><h2 id="dialogTitle" tabindex="-1">${esc(m.name)}</h2><p>Tiempo base: ${r.edges.reduce((n,e)=>n+e.minutes,0)} min. Plazo con margen: ${m.time_limit} min.</p><ol class="route-list">${r.nodes.map((id,i)=>{const n=data.nodes[id],edge=r.edges[i];return `<li class="${world.run&&i===world.run.index?'active':''}"><span class="number">${String(i+1).padStart(2,'0')}</span><span>${esc(n.name)}</span><small>${edge?edge.minutes+' min al próximo punto':'Destino'}</small></li>`;}).join('')}</ol></div><div class="dialog-actions"><button data-close="dialog" class="primary">Volver</button></div>`);}
function nodeInfo(id){const n=data.nodes[id];open('PUNTO DEL RECORRIDO',`<div class="dialog-body"><h2 id="dialogTitle" tabindex="-1">${esc(n.name)}</h2><p>${n.checkpoint?'Punto de control: registra recuperación y permite gestionar el equipo.':'Estación o instancia posible.'}</p>${id==='heroes'?'<p class="good">Aquí puedes hablar con Mara y el Armero. Durante un encargo debes llegar físicamente por la ruta.</p>':''}<div class="contact-list">${data.contacts.filter(c=>c.refuge===id).map(c=>`<button data-contact="${c.id}">${image(c.image,c.name)}<span>${esc(c.name)} · hablar</span></button>`).join('')}</div></div><div class="dialog-actions"><button data-close="dialog" class="primary">Volver</button></div>`);}
function contact(id){const c=data.contacts.find(x=>x.id===id),m=Object.values(data.missions).find(x=>x.npc===id);open('CONTACTO DEL REFUGIO',`<div class="dialog-body"><div class="hero-brief">${image(c.image,c.name)}<div><h2 id="dialogTitle" tabindex="-1">${esc(c.name)}</h2><p>${esc(m.briefing)}</p><span class="chip">${esc(data.nodes[c.refuge]?.name)}</span></div></div></div><div class="dialog-actions"><button data-close="dialog">Volver</button><button data-offer="${m.id}" class="primary">Ver encargo</button></div>`);}
function contacts(){open('RED DE REFUGIOS',`<div class="dialog-body"><h2 id="dialogTitle" tabindex="-1">Comunidades y contactos</h2><div class="contact-list">${data.contacts.map(c=>`<button data-contact="${c.id}">${image(c.image,c.name)}<span><strong>${esc(c.name)}</strong><small>${esc(data.nodes[c.refuge]?.name)}</small></span></button>`).join('')}</div></div>`);}
function restModal(){const f=E.rewardForecast(data,world);open('PUNTO DE DESCANSO',`<div class="dialog-body"><h2 id="dialogTitle" tabindex="-1">Recuperar al grupo</h2><p>Consume 1 ración y 1 agua, recupera resistencia y 12 HP por persona. Avanza 10 minutos.</p><p class="time-warning">Pago estimado: ${f.amount} fichas · plazo ${f.limit} min.</p></div><div class="dialog-actions"><button data-close="dialog">Seguir</button><button data-rest-confirm class="primary">Descansar</button></div>`);}
function receipt(id=world.run?.mission){const r=world.completed[id];if(!r)return;open('ENCARGO ENTREGADO',`<div class="dialog-body"><h2 id="dialogTitle" tabindex="-1">${esc(data.missions[id].name)}</h2><p>«${esc(r.dialogue)}»</p><div class="outcome"><span>Pago final</span><strong>${r.amount} fichas</strong><span>${r.minutes} min · plazo ${r.timeLimit} min</span></div>${r.penalty?`<p class="bad">Demora: −${r.penalty} fichas sobre ${r.gross}.</p>`:'<p class="good">Entrega dentro del plazo: sin descuento.</p>'}<p>${esc(r.effect||'')}</p></div><div class="dialog-actions"><button data-close="dialog">Mapa</button><button data-heroes class="primary">Viajar a Los Héroes</button></div>`);}
function pendingModal(){
 const r=world.run,p=r?.pending;if(!p||r.status!=='active')return;if(p.combat){close(dialog);renderBattle();return;}
 const e=E.eventFor(data,world);let title=e?.title||'',text=e?.text||'',art='../../backgrounds/station-ruins.webp';
 if(p.category==='checkpoint'){title='Un lugar para detenerse';text='Llegan a '+data.nodes[p.to].name+'. Al entrar se registra el punto de control.';}else if(p.category==='rescue'){title='El compañero está aquí';text=p.injured?'Está herido y no puede caminar.':'Está agotado, pero puede caminar con ayuda.';}else if(p.category==='delivery'){title='El destinatario espera';text=E.mission(data,world).delivery_text;}
 const buttons=E.options(data,world).map(o=>`<button data-choice="${o.id}" ${!E.optionAvailable(world,o)?'disabled':''} class="${o.combat?'danger':''}">${esc(o.label)}</button>`).join('');
 open('EN RUTA / '+data.nodes[p.to].name,`<div class="dialog-body">${image(art,'Escena del recorrido','event-art')}<div class="eyebrow">${({quiet:'PASO TRANQUILO',decision:'DECISIÓN',hostile:'CONTACTO HOSTIL',opportunity:'HALLAZGO',checkpoint:'PUNTO DE CONTROL',rescue:'EXTRACCIÓN',delivery:'ENTREGA'})[p.category]}</div><h2 id="dialogTitle" tabindex="-1">${esc(title)}</h2><p>${esc(text)}</p><div class="choices">${buttons}</div></div>`);
}
function crewHTML(){return `<div class="crew-mini">${party().map(c=>`<button data-crew="${c.id}">${image(def(c.id).image,def(c.id).name)}<span><b>${dname(c.id)}</b><small>${c.hp}/${c.maxHp} HP · Nv. ${c.level} · Mochila ${E.bagUsed(c)}/${E.bagCapacity(data,c)}</small></span></button>`).join('')}</div>`;}
function inventoryCard(c,item){const i=data.items[item.id],others=party().filter(x=>x.id!==c.id);return `<article class="bag-card">${image(i.image,i.name)}<div><b>${esc(i.name)} ×${item.qty}</b><small>${esc(i.description)}</small><div class="bag-actions">${i.slot?`<button data-equip="${i.id}" data-member="${c.id}">Equipar</button>`:''}${i.heal?`<button data-use="${i.id}" data-member="${c.id}" ${c.hp>=c.maxHp?'disabled':''}>Usar</button>`:''}${others.map(o=>`<button data-transfer="${i.id}" data-from="${c.id}" data-to="${o.id}">A ${dname(o.id)}</button>`).join('')}</div></div></article>`;}
function crewModal(id=selectedCrew){
 selectedCrew=id;const c=member(id)||party()[0],d=def(c.id),gear=Object.entries(c.equipment||{}).filter(([,v])=>v).map(([slot,v])=>`<button data-item="${v}">${image(data.items[v].image,data.items[v].name)}<span>${slot==='weapon'?'Arma':'Protección'}<b>${data.items[v].name}</b></span></button>`).join('');
 open('EQUIPO / LOS MENSAJEROS',`<div class="dialog-body loadout-view"><div class="profile-switch">${party().map(x=>`<button data-crew="${x.id}" aria-pressed="${x.id===c.id}">${def(x.id).name}</button>`).join('')}</div><div class="loadout-grid"><div class="loadout-person">${image(d.image,d.name)}<h2 id="dialogTitle" tabindex="-1">${d.name}</h2><span class="chip">${d.role}</span><p>${d.description}</p><b>${c.hp}/${c.maxHp} HP · Nivel ${c.level} · ${c.xp}/60 XP</b></div><section><h3>Equipo colocado</h3><div class="equipped-list">${gear||'<p class="empty">Sin equipo.</p>'}</div><h3>Mochila · ${E.bagUsed(c)}/${E.bagCapacity(data,c)}</h3><div class="bag-list">${c.bag.map(x=>inventoryCard(c,x)).join('')||'<p class="empty">Mochila vacía.</p>'}</div></section></div><h3>Rama de habilidades · ${E.skillPoints(c)} puntos</h3><div class="skill-tree">${data.skillTrees[c.id].map(k=>{const learned=c.skills.includes(k.id),locked=k.requires&&!c.skills.includes(k.requires);return `<div class="skill-node"><b>${k.name}</b><p>${k.description}</p><button data-member="${c.id}" data-learn="${k.id}" ${learned||locked||E.skillPoints(c)<1?'disabled':''}>${learned?'Aprendida':locked?'Requiere habilidad anterior':'Aprender · 1 punto'}</button></div>`;}).join('')}</div></div><div class="dialog-actions"><button data-close="dialog" class="primary">Volver</button></div>`);
}
function heroes(){
 if(!E.atHeroes(data,world)){
  if(!world.run||!['active','failed'].includes(world.run.status))open('VIAJE AL REFUGIO',`<div class="dialog-body"><h2 id="dialogTitle" tabindex="-1">Viajar a Los Héroes</h2><p>Regresa a la central de Línea 1 para comerciar con Mara y el Armero.</p></div><div class="dialog-actions"><button data-close="dialog">Cancelar</button><button data-travel-heroes class="primary">Viajar</button></div>`);
  else announce('Durante el encargo debes llegar físicamente a Los Héroes por la ruta.');return;
 }
 const c=member(selectedCrew)||party()[0],npc=selectedVendor==='mara'?{name:'Mara',role:'Intercambista del Andén 4',image:'../../characters/mara-trader.webp',text:'Compra lo que recuperen y vende suministros para sostener el viaje.'}:{name:'Bruno',role:'Armero de túnel',image:'../../characters/armero-trader.webp',text:'Mantiene armas y protección reconstruidas para quienes cruzan los túneles.'},offers=data.shop.filter(x=>x.vendor===selectedVendor);
 const sell=c.bag.filter(x=>selectedVendor==='mara'?!['weapon','armor'].includes(data.items[x.id].kind):['weapon','armor','material'].includes(data.items[x.id].kind));
 open('REFUGIO LOS HÉROES',`<div class="dialog-body refuge-view"><div class="vendor-tabs"><button data-vendor="mara" aria-pressed="${selectedVendor==='mara'}">Mara</button><button data-vendor="armorer" aria-pressed="${selectedVendor==='armorer'}">Armero</button></div><div class="hero-brief vendor-brief">${image(npc.image,npc.name)}<div><h2 id="dialogTitle" tabindex="-1">${npc.name}</h2><span class="chip">${npc.role}</span><p>${npc.text}</p><b>${world.credits} fichas</b></div></div><div class="profile-switch">${party().map(x=>`<button data-shop-member="${x.id}" aria-pressed="${x.id===c.id}">${dname(x.id)} · ${E.bagUsed(x)}/${E.bagCapacity(data,x)}</button>`).join('')}</div><h3>${selectedVendor==='mara'?'Reservas de Mara':'Banco del Armero'}</h3><div class="shop-grid">${offers.map(s=>`<article>${image(data.items[s.id].image,data.items[s.id].name)}<h3>${data.items[s.id].name} ×${s.qty}</h3><p>${data.items[s.id].description}</p><button data-buy="${s.id}" data-member="${c.id}" ${world.credits<E.price(data,world,s.id)?'disabled':''}>Comprar · ${E.price(data,world,s.id)} fichas</button></article>`).join('')}</div><h3>Objetos de ${dname(c.id)}</h3><div class="shop-grid">${sell.map(x=>`<article>${image(data.items[x.id].image,data.items[x.id].name)}<h3>${data.items[x.id].name} ×${x.qty}</h3><button data-sell="${x.id}" data-member="${c.id}">Vender 1 · ${E.salePrice(data,x.id)} fichas</button></article>`).join('')||'<p class="empty">No hay objetos que este comerciante compre.</p>'}</div></div><div class="dialog-actions"><button data-recover ${world.credits<8?'disabled':''}>Recuperar grupo · 8 fichas</button><button data-close="dialog" class="primary">Volver al mapa</button></div>`);
}
function help(){open('GUÍA DE ENCARGOS',`<div class="dialog-body"><h2 id="dialogTitle" tabindex="-1">La misma supervivencia, otro equipo</h2><div class="help-sections"><section><h3>Combate y equipo</h3><p>La batalla usa la misma disposición de la exploración: aliados, amenazas, turno, objetivo, acciones y registro. Cada Mensajero lleva arma, protección y mochila. Puedes equipar, usar y transferir objetos. No fabrican.</p></section><section><h3>Saqueo</h3><p>Al vencer, elige quién registra cada amenaza. Cada objeto ocupa espacio y cada unidad agrega un minuto.</p></section><section><h3>Los Héroes</h3><p>Mara compra loot y vende suministros; el Armero ofrece armas y chalecos. Durante un encargo solo accedes si la ruta llega físicamente al refugio.</p></section><section><h3>Tiempo y recompensa</h3><p>Los minutos representan desplazamientos y acciones. Superar el plazo descuenta fichas por bloques de cinco minutos, hasta la mitad del pago. Leer o cerrar el juego no consume tiempo.</p></section><section><h3>Tomás</h3><p>Es ciego y falla más ataques. Escuchar prepara su siguiente golpe cercano; reconoce desvíos y guía retiradas. El ruido electrónico reduce esas ventajas.</p></section></div></div><div class="dialog-actions"><button data-help-done class="primary">Entendido</button></div>`);}
function renderBattle(){
 const r=world.run,c=r?.pending?.combat;if(!c){$('battleLayer').classList.add('hidden');return;}$('battleLayer').classList.remove('hidden');const loot=c.phase==='loot',actor=loot?null:r.party[c.actor];if(loot&&!r.party.some(x=>x.id===selectedLooter&&x.hp>0))selectedLooter=r.party.find(x=>x.hp>0)?.id;
 $('battleTitle').textContent=loot?'Amenazas neutralizadas':'Paso bloqueado';$('battleRound').textContent=loot?'SAQUEO':'Ronda '+String(c.round).padStart(2,'0');$('battleBrief').textContent=loot?'Registra los cuerpos o deja el loot para proteger el plazo.':'Selecciona una amenaza y una acción.';$('turnLabel').textContent=loot?'Tiempo actual: '+r.minutes+' min':'Turno de '+dname(actor.id)+' · disparo '+Math.round(E.hitChance(data,world,'fire')*100)+'% · cercano '+Math.round(E.hitChance(data,world,'melee')*100)+'%';
 $('allyUnits').innerHTML=r.party.map((x,i)=>`<button class="unit ${!loot&&i===c.actor?'active':''} ${loot&&x.id===selectedLooter?'looter-selected':''}" ${loot&&x.hp>0?`data-looter="${x.id}"`:''} ${x.hp<=0?'disabled':''}>${image(def(x.id).image,def(x.id).name,'portrait')}<div class="unit-info"><h3>${dname(x.id)}</h3><small>${def(x.id).role} · Nv. ${x.level}</small><div class="barline"><span>HP</span><div class="bar"><span style="width:${100*x.hp/x.maxHp}%"></span></div><b>${x.hp}/${x.maxHp}</b></div><div class="barline"><span>Moch</span><div class="bar bag"><span style="width:${100*E.bagUsed(x)/E.bagCapacity(data,x)}%"></span></div><b>${E.bagUsed(x)}/${E.bagCapacity(data,x)}</b></div></div></button>`).join('');
 $('enemyUnits').innerHTML=c.enemies.map((e,i)=>`<${!loot&&e.hp>0?'button':'article'} class="unit ${!loot&&i===c.target?'targeted':''} ${e.hp<=0?'down':''}" ${!loot&&e.hp>0?`data-target="${i}"`:''}>${image(e.image,e.name,'portrait')}<div class="unit-info"><h3>${esc(e.name)}</h3><small>${loot?'Amenaza registrada':'Hostil'}</small><div class="barline"><span>HP</span><div class="bar"><span style="width:${100*e.hp/e.maxHp}%"></span></div><b>${e.hp}/${e.maxHp}</b></div>${loot?`<div class="corpse-loot">${e.loot.filter(x=>x.qty>0).map(x=>`<button data-take-loot="${x.id}" data-enemy="${i}" ${!E.canLoot(data,world,selectedLooter,x.id)?'disabled':''}>${data.items[x.id].name} ×${x.qty}</button>`).join('')||'<span>Sin loot</span>'}</div>`:''}</div></${!loot&&e.hp>0?'button':'article'}>`).join('');
 $('enemyHeading').textContent=loot?'Amenazas · Saqueo':'Amenazas · Selecciona objetivo';$('combatActions').innerHTML=loot?'':E.options(data,world).map(o=>`<button data-choice="${o.id}" ${!E.optionAvailable(world,o)?'disabled':''}>${esc(o.label)}</button>`).join('');$('lootControls').classList.toggle('hidden',!loot);$('combatLog').innerHTML=r.log.slice(-8).map(x=>'<p>'+esc(x)+'</p>').join('');$('combatLog').scrollTop=$('combatLog').scrollHeight;
}
function pathFor(edge){const a=data.nodes[edge.from],b=data.nodes[edge.to];return edge.path||`M${a.x} ${a.y}L${b.x} ${b.y}`;}
function svgEl(tag,attrs){const el=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,String(v));return el;}
function mapRender(){
 const m=world.run?E.mission(data,world):data.missions[selected],rt=data.routes[m.route];layer.replaceChildren();rt.edges.forEach(e=>layer.append(svgEl('path',{d:pathFor(e),class:'route-selected'})));
 [...new Set([...rt.nodes,...data.contacts.map(c=>c.refuge)])].filter(id=>data.nodes[id]).forEach(id=>{const n=data.nodes[id],el=svgEl(n.checkpoint?'rect':'circle',n.checkpoint?{x:n.x-7,y:n.y-7,width:14,height:14}:{cx:n.x,cy:n.y,r:5});el.setAttribute('class',n.checkpoint?'control-point':'instance-point');el.setAttribute('role','button');el.setAttribute('tabindex','0');el.addEventListener('click',()=>nodeInfo(id));layer.append(el);});
 if(world.run){const r=world.run,n=data.nodes[rt.nodes[r.index]],marker=svgEl('circle',{cx:n.x,cy:n.y,r:9,class:'messenger'});marker.id='messenger';layer.append(marker);}
}
function render(){
 const r=world.run,m=r?E.mission(data,world):data.missions[selected],node=r?E.here(data,world):data.nodes[data.routes[m.route].nodes[0]],forecast=r?E.rewardForecast(data,world):null;
 $('brief').innerHTML=`<div class="mission-portrait">${image(m.portrait,m.issuer)}<span class="portrait-name">${esc(m.issuer)}</span></div><span class="chip">${r?({active:'EN CURSO',completed:'ENTREGADO',failed:'VIAJE INTERRUMPIDO',abandoned:'DEVUELTO'})[r.status]:'DISPONIBLE'}</span><h2>${esc(m.name)}</h2><p>${esc(m.summary)}</p><button class="primary" data-offer="${m.id}">Ver encargo</button>${r&&['active','failed'].includes(r.status)?'<button class="text-button" data-abandon>Devolver encargo</button>':''}`;
 $('location').textContent=r?.pending?'En tránsito a '+data.nodes[r.pending.to].name:node.name;mapRender();$('crewSummary').innerHTML=crewHTML();$('cargo').innerHTML=itemRows(r?r.cargo:m.cargo);$('supplies').innerHTML=itemRows(r?r.supplies:totals());
 $('status').innerHTML=r?`<div class="meter-label"><span>Resistencia</span><b>${r.condition}%</b></div><div class="progress"><span style="width:${r.condition}%"></span></div><div class="deadline ${forecast.penalty?'late':''}"><span>${forecast.minutes} / ${forecast.limit} min</span><b>Pago estimado ${forecast.amount} fichas</b><small>${forecast.penalty?'Descuento actual −'+forecast.penalty:'Dentro del plazo'}</small></div><div class="status-data"><div>Combates<b>${r.combats}</b></div><div>Evitados<b>${r.evaded}</b></div><div>Fichas<b>${world.credits}</b></div></div>`:`<p>${world.location==='heroes'?'El equipo está en Los Héroes.':'Viaja a Los Héroes para preparar al equipo.'}</p><b>${world.credits} fichas</b>`;
 const edge=r?E.nextEdge(data,world):null,risk=edge?E.effectiveRisk(data,world,edge):'low';
 $('travel').innerHTML=!r?'<p>Consulta los encargos o visita Los Héroes.</p><button data-catalog class="primary">Consultar encargos</button>':r.status==='completed'?'<p class="good">Encargo entregado.</p><button data-receipt="'+r.mission+'" class="primary">Ver resultado</button><button data-heroes>Viajar a Los Héroes</button>':r.status==='failed'?'<p>El grupo no puede continuar.</p><button id="retryButton" class="primary">Reintentar desde '+esc(data.nodes[r.checkpoint.node].name)+'</button>':r.status==='abandoned'?'<p>Encargo devuelto.</p><button data-heroes class="primary">Viajar a Los Héroes</button>':`<div class="travel-head"><span>${r.index}/${E.route(data,world).edges.length} · próximo tramo ${edge?.minutes||0} min</span><span class="risk-${risk}">Amenaza ${risks[risk]}</span></div><div class="progress"><span style="width:${100*r.index/E.route(data,world).edges.length}%"></span></div><div class="travel-actions"><button id="advanceButton" class="primary">${r.pending?'Resolver instancia':'Avanzar a '+esc(data.nodes[edge.to].name)}</button>${!r.pending&&node.rest?'<button id="restButton">Descansar · 10 min</button>':''}${!r.pending&&node.id==='heroes'?'<button data-heroes>Hablar con Mara / Armero</button>':''}</div>`;
 $('journal').innerHTML=(r?.log||['La red de encargos espera.']).slice(-10).map(x=>'<p>'+esc(x)+'</p>').join('');renderBattle();
}
function animateAdvance(){if(busy)return;if(world.run?.pending){pendingModal();return;}if(!apply(E.advance))return;if(world.run.status!=='active')return;busy=true;setTimeout(()=>{busy=false;render();pendingModal();},matchMedia('(prefers-reduced-motion:reduce)').matches?0:500);}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;
 if(b.dataset.close){close($(b.dataset.close));return;}if(b.dataset.item){itemModal(b.dataset.item);return;}if(b.hasAttribute('data-catalog')||b.id==='catalogButton'){catalog();return;}if(b.dataset.offer){offer(b.dataset.offer);return;}if(b.dataset.accept){if(apply(E.start,b.dataset.accept)){close(dialog);announce('Encargo aceptado.');}return;}if(b.hasAttribute('data-resume')){close(dialog);return;}if(b.dataset.receipt){receipt(b.dataset.receipt);return;}
 if(b.dataset.choice){if(apply(E.choose,b.dataset.choice)){sound('ui/click-metal.mp3');if(world.run?.pending?.combat)renderBattle();else if(world.run?.status==='completed')receipt();else pendingModal();}return;}if(b.dataset.target!==undefined){if(apply(E.target,Number(b.dataset.target)))renderBattle();return;}if(b.dataset.looter){selectedLooter=b.dataset.looter;renderBattle();return;}if(b.dataset.takeLoot){if(apply(E.takeLoot,Number(b.dataset.enemy),selectedLooter,b.dataset.takeLoot)){sound('loot/take-item-1.mp3');renderBattle();}return;}if(b.id==='finishLoot'){if(apply(E.finishLoot)){sound('loot/loot-exit.mp3');$('battleLayer').classList.add('hidden');}return;}
 if(b.id==='advanceButton'){animateAdvance();return;}if(b.id==='routeButton'){displayRoute();return;}if(b.id==='restButton'){restModal();return;}if(b.hasAttribute('data-rest-confirm')){if(apply(E.rest))close(dialog);return;}if(b.id==='retryButton'){apply(E.retry);return;}
 if(b.hasAttribute('data-abandon')){open('DEVOLVER ENCARGO',`<div class="dialog-body"><h2 id="dialogTitle">¿Devolver el encargo?</h2><p>No habrá pago. La vigilancia provocada permanece.</p></div><div class="dialog-actions"><button data-close="dialog">Seguir</button><button data-abandon-confirm class="danger">Devolver</button></div>`);return;}if(b.hasAttribute('data-abandon-confirm')){if(apply(E.abandon))close(dialog);return;}
 if(b.dataset.filter){filter=b.dataset.filter;catalog();return;}if(b.dataset.previewRoute){displayRoute(b.dataset.previewRoute);return;}if(b.dataset.contact){contact(b.dataset.contact);return;}if(b.id==='contactsButton'){contacts();return;}
 if(b.id==='crewButton'){crewModal();return;}if(b.dataset.crew){crewModal(b.dataset.crew);return;}if(b.dataset.equip){if(apply(E.equip,b.dataset.member,b.dataset.equip))crewModal(b.dataset.member);return;}if(b.dataset.use){if(apply(E.useItem,b.dataset.member,b.dataset.use))crewModal(b.dataset.member);return;}if(b.dataset.transfer){if(apply(E.transfer,b.dataset.from,b.dataset.to,b.dataset.transfer))crewModal(b.dataset.from);return;}if(b.dataset.learn){if(apply(E.learn,b.dataset.member,b.dataset.learn))crewModal(b.dataset.member);return;}
 if(b.id==='heroesButton'||b.hasAttribute('data-heroes')){heroes();return;}if(b.hasAttribute('data-travel-heroes')){if(apply(E.travelHeroes)){selectedVendor='mara';heroes();}return;}if(b.dataset.vendor){selectedVendor=b.dataset.vendor;heroes();return;}if(b.dataset.shopMember){selectedCrew=b.dataset.shopMember;heroes();return;}if(b.dataset.buy){if(apply(E.buy,b.dataset.buy,b.dataset.member))heroes();return;}if(b.dataset.sell){if(apply(E.sell,b.dataset.sell,b.dataset.member))heroes();return;}if(b.hasAttribute('data-recover')){if(apply(E.recover))heroes();return;}
 if(b.id==='helpButton'){help();return;}if(b.hasAttribute('data-help-done')){world.helpSeen=true;save();close(dialog);return;}
 if(b.id==='resetCouriers'){open('REINICIAR ENCARGOS',`<div class="dialog-body"><h2 id="dialogTitle">¿Reiniciar?</h2><p>Se borrará solo el progreso de Los Mensajeros.</p></div><div class="dialog-actions"><button data-close="dialog">Cancelar</button><button data-reset-confirm class="danger">Reiniciar</button></div>`);return;}if(b.hasAttribute('data-reset-confirm')){world=E.createWorld(data,{seed:crypto.getRandomValues(new Uint32Array(1))[0]});loadError=false;save();render();close(dialog);return;}
 if(['zoomIn','zoomOut','resetMap'].includes(b.id)){zoom=b.id==='resetMap'?1:Math.max(1,Math.min(2.5,zoom+(b.id==='zoomIn'?.25:-.25)));const n=world.run?E.here(data,world):data.nodes.leones,w=1090/zoom,h=704/zoom;svg.setAttribute('viewBox',`${Math.max(0,Math.min(1090-w,n.x-w/2))} ${Math.max(0,Math.min(704-h,n.y-h/2))} ${w} ${h}`);}
});
$('bootStatus').hidden=!loadError;render();if(loadError)announce(warning);else if(!world.helpSeen)help();else if(!world.run)catalog();window.NeoCourierBack=()=>{if(!$('battleLayer').classList.contains('hidden'))return true;if(itemDialog.open){close(itemDialog);return true;}if(dialog.open){close(dialog);return true;}return false;};
