import {animateRoute} from './travel.mjs?v=1';
import * as E from './engine.mjs';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=p=>new URL(p,import.meta.url).href;
const data=await fetch(new URL('./data.json',import.meta.url)).then(r=>{if(!r.ok)throw Error('No se pudo cargar el catálogo');return r.json();});
let world=E.createWorld(data,{mode:'laboratory',seed:crypto.getRandomValues(new Uint32Array(1))[0]}), warning='',selected='guzman-01',zoom=1,busy=false;
try{const text=localStorage.getItem(data.save_key);if(text)world=E.restore(data,text);}catch(err){warning='No se pudo recuperar el guardado del laboratorio. '+err.message;}
if(world.run)selected=world.run.mission;
const mapSource=await fetch(new URL('./map.svg',import.meta.url)).then(r=>r.text());
$('map').innerHTML=mapSource;const svg=$('map').querySelector('svg');svg.setAttribute('role','group');svg.setAttribute('aria-label','Mapa de refugios y recorrido de Los Mensajeros');
svg.querySelector('#hotspots')?.remove();svg.querySelector('#routeGlow')?.remove();
const ns='http://www.w3.org/2000/svg', layer=document.createElementNS(ns,'g');layer.id='missionLayer';svg.append(layer);
const dialog=$('dialog'),itemDialog=$('itemDialog');
function save(){try{localStorage.setItem(data.save_key,E.serialize(world));$('saveStatus').textContent='Progreso guardado en este navegador';}catch(err){warning='No se pudo guardar: el almacenamiento del navegador no está disponible.';$('saveStatus').textContent=warning;}}
function apply(fn,...args){try{world=fn(data,world,...args);save();render();return true;}catch(err){announce(err.message);return false;}}
function announce(text){$('announcement').textContent=text;$('saveStatus').textContent=text;}
function open(kicker,html){if(busy)return;$('dialogKicker').textContent=kicker;$('dialogBody').innerHTML=html;dialog.classList.remove('closing');if(!dialog.open)dialog.showModal();dialog.scrollTop=0;const heading=$('dialogTitle');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
function close(d){if(!d.open)return;d.classList.add('closing');setTimeout(()=>{d.close();d.classList.remove('closing');if(d===dialog){const target=$('advanceButton')||$('catalogButton');target?.focus({preventScroll:true});}},matchMedia('(prefers-reduced-motion:reduce)').matches?0:160);}
for(const d of [dialog,itemDialog]){d.addEventListener('cancel',e=>{e.preventDefault();close(d);});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close(d);}});}
const risks={low:'Baja',medium:'Media',high:'Alta'};
function image(p,alt,cls=''){return `<img src="${asset(p)}" alt="${esc(alt)}" class="${cls}" loading="lazy" decoding="async">`;}
function itemRows(stock){return Object.entries(stock).filter(([,n])=>n>0).map(([id,n])=>`<button class="item-row" data-item="${id}">${image(data.items[id].image,data.items[id].name)}<span>${esc(data.items[id].name)}</span><b>×${n}</b></button>`).join('')||'<p class="empty">Sin carga en esta categoría.</p>';}
function itemModal(id){const i=data.items[id];$('itemBody').innerHTML=`<div class="item-detail">${image(i.image,i.name)}<div><span class="chip">${i.kind==='cargo'?'CARGA PROTEGIDA':'EQUIPO DE MISIÓN'}</span><h2 id="itemTitle">${esc(i.name)}</h2><p>${esc(i.description)}</p><dl><dt>Compra / venta</dt><dd>No disponible en este encargo</dd><dt>Desarme / descarte</dt><dd>No disponible; se conserva para la misión</dd><dt>Uso</dt><dd>${i.kind==='cargo'?'Entrega al destinatario':'Opciones de viaje, descanso o asistencia'}</dd></dl></div></div>`;if(!itemDialog.open)itemDialog.showModal();}
function catalog(){open('CENTRAL DE ENCARGOS',`<div class="dialog-body" style="padding-bottom:0"><h2 id="dialogTitle">Trabajo entre refugios</h2><p>Elige un encargo y prepara el viaje. Cada estación puede cambiar la situación del grupo.</p></div><div class="offer-grid">${Object.values(data.missions).map(m=>`<article class="offer">${image(m.portrait,m.issuer)}<div class="eyebrow">${m.type==='delivery'?'TALLERES / ENTREGA':'OPERACIONES / EXTRACCIÓN'}</div><h3>${esc(m.name)}</h3><p>${esc(m.summary)}</p><button data-offer="${m.id}">${world.paid.includes(m.id)?'Ver entrega completada':'Hablar con '+m.issuer}</button></article>`).join('')}</div>`);}
function offer(id){selected=id;const m=data.missions[id],complete=world.paid.includes(id),active=world.run?.status==='active';open('ENCARGO / '+m.issuer,`<div class="dialog-body"><div class="hero-brief">${image(m.portrait,m.issuer)}<div><h2 id="dialogTitle">${esc(m.name)}</h2><p>«${esc(m.briefing)}»</p><p class="muted">Destino: ${esc(m.recipient)}. Recompensa de prueba: ${m.reward.base}${m.reward.stealth_bonus?' + '+m.reward.stealth_bonus+' por evitar combates':''} fichas.</p></div></div><div class="outcome"><div class="eyebrow">${m.type==='delivery'?'COMPONENTES ENTREGADOS POR GUZMÁN':'EQUIPO ENTREGADO POR ADASME'}</div>${itemRows({...m.cargo,...m.issued})}</div><p class="muted">Preparación de prueba: 3 raciones, 3 unidades de agua y 12 municiones. Estos valores aún pueden ajustarse.</p></div><div class="dialog-actions"><button data-close="dialog">Volver</button>${complete?'<button data-receipt="'+id+'" class="primary">Ver resultado</button>':active?'<button data-resume class="primary">Volver al viaje activo</button>':'<button data-accept="'+id+'" class="primary">Aceptar encargo</button>'}</div>`);}
function displayRoute(){const m=world.run?E.mission(data,world):data.missions[selected],r=data.routes[m.route];open('ITINERARIO / '+m.issuer,`<div class="dialog-body"><h2 id="dialogTitle">${esc(m.name)}</h2><p>Un avance por estación. Los puntos de control conservan un estado de recuperación; cada resolución también se guarda automáticamente.</p><ol class="route-list">${r.nodes.map((id,i)=>{const n=data.nodes[id];return `<li class="${world.run&&i===world.run.index?'active':''}"><span class="number">${String(i+1).padStart(2,'0')}</span><span>${esc(n.name)}</span><small>${n.checkpoint?(n.provisional?'Descanso provisional':'Punto de control'):n.kind==='rescue'?'Objetivo de búsqueda':'Instancia posible'}</small></li>`;}).join('')}</ol>${m.type==='extraction'?'<p class="muted" style="margin-top:18px">El enlace Vicuña Mackenna–Tobalaba está agrupado: sus estaciones intermedias todavía no están desarrolladas. Los tiempos del laboratorio son abstractos.</p>':''}</div><div class="dialog-actions"><button data-close="dialog" class="primary">Volver al mapa</button></div>`);}
function nodeInfo(id){const n=data.nodes[id];open('PUNTO DEL RECORRIDO',`<div class="dialog-body"><h2 id="dialogTitle">${esc(n.name)}</h2><p>${n.checkpoint?'Punto de control: al llegar queda registrada una posición de recuperación.':'Estación o punto de instancia: al avanzar puede aparecer calma, una decisión, una amenaza o un hallazgo.'}</p>${n.rest?'<p>Descanso opcional: consume 1 ración y 1 agua; recupera 25 puntos de condición. Una vez por visita.</p>':''}${n.provisional?'<p class="muted">Ubicación o función provisional dentro de esta prueba.</p>':''}<p>Consultar el mapa no mueve al grupo.</p></div><div class="dialog-actions"><button data-close="dialog" class="primary">Volver</button></div>`);}
function restModal(){open('PUNTO DE DESCANSO',`<div class="dialog-body"><h2 id="dialogTitle">Recuperar al grupo</h2><p>Descansar en ${esc(E.here(data,world).name)} consume 1 ración y 1 agua, recupera hasta 25 puntos y avanza 10 minutos narrativos. Si el inhibidor sigue encendido, también gasta batería.</p><p>El punto de control se actualiza después del descanso.</p></div><div class="dialog-actions"><button data-close="dialog">Continuar sin descansar</button><button data-rest-confirm class="primary">Descansar</button></div>`);}
function receipt(id=world.run?.mission){const r=world.completed[id];if(!r)return;open('ENCARGO ENTREGADO',`<div class="dialog-body"><div class="eyebrow">${esc(r.recipient)}</div><h2 id="dialogTitle">${esc(data.missions[id].name)}</h2><p>«${esc(r.dialogue)}»</p><div class="outcome"><span>Recompensa de prueba</span><strong>${r.amount} fichas</strong><span>${r.combats} enfrentamientos · ${r.evaded} encuentros evitados o abandonados</span></div><p>Entrega registrada. La recompensa se abona una sola vez. La vigilancia provocada permanece en los corredores afectados.</p></div><div class="dialog-actions"><button data-close="dialog">Ver mapa</button><button data-catalog class="primary">Otros encargos</button></div>`);}
function pendingModal(){if(busy)return;const r=world.run,p=r?.pending;if(!p||r.status!=='active')return;
 const e=E.eventFor(data,world);let title=e?.title||'',text=e?.text||'',art='../../backgrounds/station-ruins.webp',extra='';
 if(p.combat){title='Paso bloqueado';text='Combate de prueba por turnos. Puedes abrir paso o retirarte; la vigilancia ya aumentó al iniciar el enfrentamiento.';art='../../portraits/'+(e?.electronic?'drone.webp':'merodeador.webp');extra=`<div class="meter-label"><span>Amenaza restante</span><b>${p.combat.hp} / ${p.combat.maxHp}</b></div><div class="progress"><span style="width:${100*p.combat.hp/p.combat.maxHp}%"></span></div><p>Condición del grupo: ${r.condition} / 100 · Munición: ${r.supplies.ammo556||0}</p>`;}
 else if(p.category==='checkpoint'){title='Un lugar para detenerse';text='Llegan a '+data.nodes[p.to].name+'. Al entrar se registra el punto de control. Pueden descansar si tienen provisiones.';}
 else if(p.category==='rescue'){title='El compañero está aquí';text=p.injured?'El operativo está consciente, pero una lesión le impide caminar. Tendrán que cargarlo de vuelta.':'El operativo está agotado, pero puede caminar con ayuda. Necesita compañía para volver.';extra='<p>Asistirlo consume provisiones. Cargarlo añade 2 puntos de desgaste y 2 minutos por avance. No reduce la recompensa por sí solo.</p>';}
 else if(p.category==='delivery'){title=E.mission(data,world).type==='delivery'?'Los técnicos esperan la carga':'De vuelta en Vicuña Mackenna';text=E.mission(data,world).type==='delivery'?'Han llegado a Plaza de Armas. Los técnicos verifican los dos rotores y el sensor antes de recibirlos.':'El compañero está de regreso. Falta entregarlo e informar a Adasme para cerrar el encargo.';}
 const buttons=E.options(data,world).map(o=>`<button data-choice="${o.id}" ${!E.optionAvailable(world,o)?'disabled':''} class="${o.combat?'danger':''}">${esc(o.label)}</button>`).join('');
 open('INSTANCIA / '+data.nodes[p.to].name,`<div class="dialog-body">${image(art,'Escena del recorrido','event-art')}<div class="eyebrow">${p.combat?'COMBATE DE PRUEBA':({quiet:'PASO TRANQUILO',decision:'DECISIÓN',hostile:'CONTACTO HOSTIL',opportunity:'HALLAZGO',checkpoint:'PUNTO DE CONTROL',rescue:'EXTRACCIÓN',delivery:'ENTREGA'})[p.category]}</div><h2 id="dialogTitle">${esc(title)}</h2><p>${esc(text)}</p>${extra}${p.category==='hostile'&&!p.combat?'<p class="muted">Puedes evitar el contacto. Iniciar una pelea aumenta la vigilancia; retirarse después no elimina esa consecuencia.</p>':''}<div class="choices">${buttons}</div></div>`);
}
function pathFor(edge){const a=data.nodes[edge.from],b=data.nodes[edge.to];return edge.path||`M${a.x} ${a.y}L${b.x} ${b.y}`;}
function svgEl(tag,attrs){const el=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,String(v));return el;}
function mapRender(){const m=world.run?E.mission(data,world):data.missions[selected],rt=data.routes[m.route];layer.replaceChildren();
 rt.edges.forEach((e,i)=>layer.append(svgEl('path',{d:pathFor(e),class:'route-selected',fill:'none','data-edge':i})));
 [...new Set(rt.nodes)].forEach(id=>{const n=data.nodes[id],visited=world.run&&rt.nodes.slice(0,world.run.index+1).includes(id);const el=svgEl(n.checkpoint?'rect':'circle',n.checkpoint?{x:n.x-7,y:n.y-7,width:14,height:14}:{cx:n.x,cy:n.y,r:5});el.setAttribute('class',(n.checkpoint?'control-point':'instance-point')+(visited?' point-visited':''));el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',n.name+(n.checkpoint?', punto de control':''));const t=svgEl('title',{});t.textContent=n.name;el.append(t);el.addEventListener('click',()=>nodeInfo(id));el.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();nodeInfo(id);}});layer.append(el);if(['ines','nunoa','estadio','nuble','biobio'].includes(id)){const label=svgEl('text',{x:n.x+(n.x===780?15:0),y:n.y+(n.x===780?4:24),class:'instance-label','text-anchor':n.x===780?'start':'middle'});label.textContent=n.name;layer.append(label);}});
 if(world.run){const r=world.run,n=data.nodes[r.pending&&!busy?r.pending.to:rt.nodes[r.index]],marker=svgEl('circle',{cx:n.x,cy:n.y,r:9,class:'messenger'});marker.id='messenger';layer.append(marker);}
}
function render(){const r=world.run,m=r?E.mission(data,world):data.missions[selected],node=r?E.here(data,world):data.nodes[data.routes[m.route].nodes[0]];
 $('brief').innerHTML=`<div class="mission-portrait">${image(m.portrait,m.issuer)}<span class="portrait-name">${esc(m.issuer)}</span></div><span class="chip">${r?({active:'EN CURSO',completed:'ENTREGADO',failed:'VIAJE INTERRUMPIDO',abandoned:'ABANDONADO'})[r.status]:'DISPONIBLE'}</span><h2>${esc(m.name)}</h2><p>${esc(m.summary)}</p><div class="mission-meta">Destinatario<strong>${esc(m.recipient)}</strong></div><button class="primary" data-offer="${m.id}">Ver encargo</button>${r&&['active','failed'].includes(r.status)?'<button class="text-button" data-abandon>Abandonar prueba de este encargo</button>':''}`;
 $('location').textContent=r?.pending?(busy?'En tránsito a ':'')+data.nodes[r.pending.to].name:node.name;mapRender();
 $('cargo').innerHTML=itemRows(r?r.cargo:m.cargo);$('supplies').innerHTML=itemRows(r?r.supplies:{...m.test_loadout,...m.issued});
 $('status').innerHTML=r?`<div class="meter-label"><span>Condición del grupo</span><b>${r.condition}%</b></div><div class="progress"><span style="width:${r.condition}%"></span></div><div class="status-data"><div>Tiempo narrativo<b>${r.minutes} min</b></div><div>Enfrentamientos<b>${r.combats}</b></div><div>Encuentros evitados<b>${r.evaded}</b></div><div>Fichas de prueba<b>${world.credits}</b></div></div>${r.supplies.jammer?`<button id="jammerButton" ${r.status!=='active'||!r.battery?'disabled':''}>Inhibidor ${r.jammerOn?'activo':'apagado'} · ${r.battery} min</button>`:''}${r.rescued?'<p class="good" style="margin-top:14px">Compañero: '+(r.rescued.mode==='carry'?'transportado por el grupo':'caminando acompañado')+'</p>':''}`:'<p class="muted">Prepara un encargo para iniciar el recorrido.</p>';
 const edge=r?E.nextEdge(data,world):null,risk=edge?E.effectiveRisk(data,world,edge):'low';
 $('travel').innerHTML=!r?'<p>El recorrido aparece sobre el mapa. Acepta el encargo para comenzar.</p><button data-catalog class="primary">Consultar encargos</button>':r.status==='completed'?'<p class="good">Encargo entregado. El grupo está en '+esc(node.name)+'.</p><button data-receipt="'+r.mission+'" class="primary">Ver resultado</button>':r.status==='failed'?'<p>El grupo no puede continuar. El reintento conserva los encuentros ya sorteados y la vigilancia provocada.</p><button id="retryButton" class="primary">Reintentar desde '+esc(data.nodes[r.checkpoint.node].name)+'</button>':r.status==='abandoned'?'<p>Encargo abandonado en esta prueba.</p><button data-catalog class="primary">Consultar encargos</button>':`<div class="travel-head"><span>${r.index} / ${E.route(data,world).edges.length} avances · ${esc(edge?.line||'Destino')}</span><span class="risk-${risk}">Amenaza ${risks[risk]}${world.regions[edge?.region]?' · vigilancia aumentada':''}</span></div><div class="progress"><span style="width:${100*r.index/E.route(data,world).edges.length}%"></span></div><div class="travel-actions"><button id="advanceButton" class="primary" ${busy?'disabled':''}>${r.pending?'Resolver instancia':'Avanzar a '+esc(data.nodes[edge.to].name)}</button>${!r.pending&&node.rest?`<button id="restButton" ${r.condition>=100||r.rested.includes(r.index)||!(r.supplies.food>0&&r.supplies.water>0)?'disabled':''}>Descansar</button>`:''}</div><p class="muted" style="font-size:11px;margin:12px 0 0">Último punto de control: ${esc(data.nodes[r.checkpoint.node].name)}${edge?.kind==='grouped_corridor'?' · tramo L4 agrupado para esta prueba':''}</p>`;
 $('journal').innerHTML=(r?.log||['Las estaciones marcan el recorrido. El peligro se conoce; el encuentro se descubre al avanzar.']).slice(-10).map(x=>'<p>'+esc(x)+'</p>').join('');$('journal').scrollTop=$('journal').scrollHeight;
 if(warning)$('saveStatus').textContent=warning;
}
async function animateAdvance(){
 if(busy)return;
 if(world.run?.pending){pendingModal();return;}
 busy=true;
 if(!apply(E.advance)){busy=false;render();return;}
 if(world.run.status!=='active'){busy=false;render();return;}
 const run=world.run,pending=run.pending,destination=data.nodes[pending.to];
 const current=()=>world.run===run&&run.pending===pending&&run.status==='active';
 const marker=$('messenger'),path=layer.querySelector('[data-edge="'+run.index+'"]');
 $('advanceButton').disabled=true;$('advanceButton').textContent='En camino a '+destination.name+'…';
 try{
  const arrived=await animateRoute({path,marker,destination,reducedMotion:matchMedia('(prefers-reduced-motion:reduce)').matches,isCurrent:current});
  busy=false;
  if(arrived&&current()){render();pendingModal();}
 }catch(error){busy=false;render();announce('No se pudo mostrar el recorrido. Pulsa Resolver instancia para continuar.');}
}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b||busy)return;
 if(b.dataset.close){close($(b.dataset.close));return;}if(b.dataset.item){itemModal(b.dataset.item);return;}if(b.hasAttribute('data-catalog')||b.id==='catalogButton'){catalog();return;}
 if(b.dataset.offer){offer(b.dataset.offer);return;}if(b.dataset.accept){if(apply(E.start,b.dataset.accept))close(dialog);return;}
 if(b.hasAttribute('data-resume')){render();close(dialog);return;}if(b.dataset.receipt){receipt(b.dataset.receipt);return;}
 if(b.dataset.choice){if(apply(E.choose,b.dataset.choice)){if(world.run.status==='completed')receipt();else if(world.run.pending&&world.run.status==='active')pendingModal();else close(dialog);}return;}
 if(b.id==='advanceButton'){animateAdvance();return;}if(b.id==='routeButton'){displayRoute();return;}if(b.id==='restButton'){restModal();return;}
 if(b.hasAttribute('data-rest-confirm')){if(apply(E.rest))close(dialog);return;}if(b.id==='jammerButton'){apply(E.toggleJammer);return;}if(b.id==='retryButton'){apply(E.retry);return;}
 if(b.hasAttribute('data-abandon')){open('INTERRUMPIR ENCARGO',`<div class="dialog-body"><h2 id="dialogTitle">¿Abandonar esta prueba?</h2><p>El encargo no se entregará ni pagará. La vigilancia provocada permanece. Podrás iniciar otro encargo.</p></div><div class="dialog-actions"><button data-close="dialog">Seguir viajando</button><button data-abandon-confirm class="danger">Abandonar encargo</button></div>`);return;}
 if(b.hasAttribute('data-abandon-confirm')){if(apply(E.abandon))close(dialog);return;}
 if(b.id==='resetLab'){open('REINICIAR LABORATORIO',`<div class="dialog-body"><h2 id="dialogTitle">¿Comenzar una prueba nueva?</h2><p>Se borrarán únicamente los avances, entregas y vigilancia de este laboratorio. Se generará otra secuencia de encuentros.</p></div><div class="dialog-actions"><button data-close="dialog">Conservar prueba</button><button data-reset-confirm class="danger">Reiniciar prueba</button></div>`);return;}
 if(b.hasAttribute('data-reset-confirm')){world=E.createWorld(data,{mode:'laboratory',seed:crypto.getRandomValues(new Uint32Array(1))[0]});warning='';save();render();catalog();return;}
 if(['zoomIn','zoomOut','resetMap'].includes(b.id)){zoom=b.id==='resetMap'?1:Math.max(1,Math.min(2.5,zoom+(b.id==='zoomIn'?.25:-.25)));const n=world.run?E.here(data,world):data.nodes.leones,w=1090/zoom,h=704/zoom;svg.setAttribute('viewBox',`${Math.max(0,Math.min(1090-w,n.x-w/2))} ${Math.max(0,Math.min(704-h,n.y-h/2))} ${w} ${h}`);}
});
render();if(!world.run)catalog();
