// Escenas originales del laboratorio. No alteran el canon ni las partidas del RPG.
const doc = (label, title, paragraphs, rows) => ({ label, title, paragraphs, rows });
export const FAMILIES = [
  { id: 'relevo', number: '01', name: 'Clave de relevo', subtitle: 'Lo que dejaron escrito', kind: 'numeric', digits: 4, plate: 'MT · 417 A', description: 'Reconstruye lo que pasó al otro lado de una lista, una nota o un registro de paso.' },
  { id: 'archivo', number: '02', name: 'Archivo de turno', subtitle: 'La versión que falta', kind: 'numeric', digits: 6, plate: 'AT · 06 / RESERVA', description: 'Cruza testimonios y documentos. Un registro más nuevo no siempre cuenta lo que ocurrió.' },
  { id: 'continuidad', number: '03', name: 'Diagnóstico', subtitle: 'Medir antes de unir', kind: 'circuit', digits: 2, plate: 'DC · 24 / SERVICIO', description: 'Usa el medidor y los puentes de servicio para recuperar el cierre sin anular sus protecciones.' },
];

const numeric = (family, data) => ({ family, kind: 'numeric', attempts: 4, digits: family === 'relevo' ? 4 : 6, ...data });
const circuit = data => ({ family: 'continuidad', kind: 'circuit', digits: 2, attempts: 4, ...data });

export const PUZZLES = [
  numeric('relevo', {
    id: 'relevo-elena', title: 'El relevo de Elena', location: 'La Moneda · paso de personal', difficulty: 'Inicial',
    intro: 'Tras la compuerta hay una galería paralela al andén. En la puerta alguien pegó la nómina del turno y, encima, una hoja arrancada de un cuaderno. Elena debía salir antes de la cena para buscar a su hija. El relevo previsto no apareció. La luz del teclado sigue encendida: alguien mantuvo este acceso funcionando después de que la estación dejara de ser una estación.',
    instruction: 'Reconstruye el relevo que ocurrió e introduce una clave de cuatro cifras.',
    inscription: 'Dos últimas cifras de la ficha de quien entrega el puesto; después, dos de quien lo recibe. El cambio real, no el impreso.',
    documents: [
      doc('Nómina', 'Turno de acceso · copia de la mañana', ['La hoja está limpia. Junto al nombre de Iván hay una marca de asistencia hecha antes de repartir los trabajos.'], [['Elena', 'Ficha 3841 · salida prevista 19:00'], ['Iván', 'Ficha 1857 · relevo previsto'], ['Nelson', 'Ficha 6726 · reparto de agua'], ['Lidia', 'Ficha 9038 · apoyo de cocina']]),
      doc('Cuaderno', 'Anotaciones junto al teléfono', ['18:45. Iván sigue en la bomba de Toesca. Avisó por radio que no puede dejarla sola. No lo cuenten acá.', '19:10. Elena continúa en la puerta. Lidia vino a dejarle comida, pero volvió a la cocina. No recibió las llaves.', '19:35. Nelson terminó el reparto y recibió las llaves de Elena. Revisaron juntos el pestillo. Elena pudo irse.']),
      doc('Nota', 'Para el turno siguiente', ['Soy Elena. Dejé la nómina porque no tenemos otra hoja, pero no la usen para cerrar el registro. Nelson no estaba obligado a quedarse y se quedó igual. Mañana le cubro la primera ronda.', 'Iván me debe una explicación por no avisar antes, no un turno doble. La bomba estaba fallando de verdad.']),
    ],
    answer: '4126', hints: ['Separa el relevo previsto de la entrega efectiva de las llaves.', 'Lidia no recibió el puesto. El cuaderno confirma quién reemplazó a Elena.', 'Usa las dos últimas cifras de las fichas de Elena y Nelson, en ese orden.'],
    explanation: 'Elena entregó el puesto y Nelson lo recibió. Sus fichas terminan en 41 y 26: 4126. La nómina de la mañana quedó desactualizada.',
    success: 'El pestillo retrocede. Del otro lado hay una silla, una taza vacía y una manta doblada: el lugar donde Nelson pasó el resto del turno. La galería de personal queda abierta.',
  }),
  numeric('relevo', {
    id: 'relevo-agua', title: 'El agua que se puede llevar', location: 'Universidad de Chile · depósito lateral', difficulty: 'Intermedia',
    intro: 'Un carro vacío bloquea parte del acceso. Dos familias esperan bidones al otro lado del túnel, pero el depósito también guarda agua para el puesto médico. Quien hizo el inventario dejó las entradas y las pérdidas en hojas distintas. En una esquina del papel alguien escribió que llevarse todo lo que todavía tenga tapa no es lo mismo que llevarse lo disponible.',
    instruction: 'Calcula los bidones disponibles para reparto: dos cifras del depósito este y dos del oeste.',
    inscription: 'Despacho: ESTE / OESTE. Dos cifras por depósito. Descuenta los rotos y la reserva médica. No cuentes dos veces lo recibido.',
    documents: [
      doc('Inventario', 'Antes del reparto', ['El conteo inicial se hizo antes de que llegaran los carros. Todos los números son bidones completos.'], [['Este · inicial', '18'], ['Oeste · inicial', '15'], ['Este · recibidos después', '4'], ['Oeste · recibidos después', '5']]),
      doc('Incidencias', 'Revisión de tapas y sellos', ['En el este encontramos tres bidones con grietas. En el oeste, dos. Los aparté detrás de la malla; ya no sirven para consumo.', 'Los cinco destinados al puesto médico en el este y los seis del oeste están sanos. Siguen en el inventario, pero no se pueden repartir. No los vuelvan a descontar como rotos. — Paula']),
      doc('Mensaje', 'Nota bajo la manilla del carro', ['Ayer una familia se fue sin agua porque calculamos con la cifra de la mañana. Hoy voy a esperar a que revisen todo. No les prometí una cantidad.', 'Si sobra menos de lo que pensamos, lo repartimos de otra forma. La reserva del puesto no se toca: Romero la pidió para limpiar instrumental, no para acumularla. — Esteban']),
    ], answer: '1412', hints: ['Empieza con el inventario inicial y suma las entregas posteriores.', 'Los bidones rotos y los reservados son grupos distintos.', 'Este: 18 + 4 − 3 − 5. Oeste: 15 + 5 − 2 − 6. Escribe ambos resultados con dos cifras.'],
    explanation: 'Quedan 14 bidones repartibles en el este y 12 en el oeste. La clave de despacho es 1412; la reserva médica permanece dentro del depósito.',
    success: 'La puerta se abre hacia el pasillo de carga. El carro puede pasar. Junto a los bidones reservados hay una cuerda roja que alguien se tomó el tiempo de volver a atar.',
  }),
  numeric('relevo', {
    id: 'relevo-reloj', title: 'Dieciocho minutos', location: 'Toesca · acceso de bombas', difficulty: 'Intermedia',
    intro: 'La compuerta guarda la hora del último cierre manual. El reloj del panel aún funciona, aunque ya nadie confía en él para cambiar de turno. Junto a una radio sin batería hay un parte firmado por Andrés. Tuvo que salir a buscar una abrazadera mientras su compañera sujetaba una unión con una correa. El parte de esa noche quedó escrito con dos relojes distintos.',
    instruction: 'Introduce la hora real del cierre en formato HHMM.',
    inscription: 'Usar la hora del refugio. La pantalla del panel adelanta 18 minutos. El registro automático NO corrige esa diferencia.',
    documents: [
      doc('Registro', 'Memoria del cierre', ['El papel sale de una impresora térmica. La cabecera indica «hora interna del panel».'], [['Cierre programado', '21:10'], ['Cierre manual confirmado', '21:46'], ['Apertura posterior', 'Ninguna']]),
      doc('Parte', 'Trabajo fuera de horario', ['No cerramos a la hora prevista. La abrazadera del repuesto era demasiado grande y Andrés volvió al almacén. Cerré cuando regresó; no antes.', 'La radio anunció las 21:00 del refugio y la pantalla de aquí marcaba 21:18. Sigue adelantada igual que ayer. La impresora copia esa pantalla. — Patricia']),
      doc('Aviso', 'Papel doblado para Andrés', ['Tu comida quedó en la segunda olla. Tu hermano quiso traerla, pero le dije que no cruzara mientras estuvieran trabajando.', 'Si llegan tarde otra vez, avisen. No hace falta que inventen una hora mejor en el parte: necesitamos saber cuánto se demora de verdad esa reparación.']),
    ], answer: '2128', hints: ['La hora programada no es la del cierre que ocurrió.', 'El cierre manual está registrado con el reloj adelantado.', 'Resta 18 minutos a 21:46 y usa cuatro cifras, sin los dos puntos.'],
    explanation: 'La memoria registró 21:46 en un reloj que adelanta 18 minutos. El cierre real ocurrió a las 21:28: 2128.',
    success: 'Se oye el golpe seco del cierre al soltarse. El acceso de bombas está despejado. La correa de aquella reparación sigue colgada de una tubería, junto a la abrazadera correcta.',
  }),
  numeric('relevo', {
    id: 'relevo-camas', title: 'Dos camas juntas', location: 'República · corredor de atención', difficulty: 'Intermedia',
    intro: 'La puerta permite cruzar por detrás del puesto de atención. Carmen y su nieto Simón durmieron aquí después de perder el acceso a su vivienda. La primera asignación los dejó separados por una cortina y varios carros. Una auxiliar los trasladó antes del cambio de turno, pero nadie alcanzó a reemplazar la hoja de ingreso que sigue pegada al panel.',
    instruction: 'Reconstruye sus camas definitivas: primero Carmen, después Simón, con dos cifras cada una.',
    inscription: 'Acceso familiar: cama de Carmen + cama de Simón. Siempre la asignación final. Completar con cero si la cama tiene una sola cifra.',
    documents: [
      doc('Ingreso', 'Asignación al llegar', ['La auxiliar escribió los números apenas llegaron. La hoja no contiene los traslados posteriores.'], [['Carmen', 'Cama 12'], ['Simón', 'Cama 13'], ['Sector 7 y 8', 'Ocupado al inicio del turno']]),
      doc('Traslado', 'Cambios de la madrugada', ['02:10. Se desocupan las camas 7 y 8. Los pacientes regresaron con sus familias.', '02:25. Una gotera moja las mantas del sector 12–13. Trasladamos juntos a Carmen y Simón al espacio libre.', 'Carmen queda junto a la pared, donde puede afirmarse para sentarse. Simón queda al lado del pasillo. El sector viejo se cierra hasta secarlo.']),
      doc('Plano', 'Distribución del sector libre', ['La auxiliar dejó este dibujo escrito en palabras para que el turno nuevo no cambiara otra vez las camas.'], [['Cama 7', 'Junto a la pared · barra de apoyo'], ['Cama 8', 'Junto al pasillo · acceso libre'], ['Nota de Carmen', 'Gracias por dejarnos juntos. Él dice que no le importa, pero anoche no pudo dormir hasta verme.']]),
    ], answer: '0708', hints: ['La hoja de ingreso describe dónde estuvieron al principio.', 'El traslado deja a Carmen junto a la pared y a Simón junto al pasillo.', 'El plano asigna 7 a la pared y 8 al pasillo. Cada número debe ocupar dos cifras.'],
    explanation: 'Carmen terminó en la cama 7 y Simón en la 8. Con los ceros exigidos por el panel, la clave es 0708.',
    success: 'La compuerta se desliza sin golpear el marco. El corredor permite rodear el andén. Una silla entre ambas camas confirma que alguien se quedó acompañándolos.',
  }),
  numeric('relevo', {
    id: 'relevo-regreso', title: 'No cerramos por lista', location: 'Parque O’Higgins · galería de retorno', difficulty: 'Avanzada',
    intro: 'Un grupo salió a buscar herramientas al otro extremo del túnel. En el refugio quedaron sus nombres y una promesa: no cerrar el acceso mientras faltara alguien. La lista contiene correcciones, dos personas que no salieron y un nombre escrito dos veces. El registro de regreso importa más que el total que alguien anotó apurado antes de partir.',
    instruction: 'Forma la clave con el total real que regresó y las dos últimas cifras de la ficha de la última persona en entrar.',
    inscription: 'Cierre de grupo: personas que efectivamente regresaron / final de ficha del último ingreso. Dos cifras por dato.',
    documents: [
      doc('Salida', 'Lista corregida', ['Había 12 renglones. Teresa y Joel finalmente se quedaron reparando el carro; no salieron. Samuel aparecía dos veces, una con apellido y otra sin él. Todos los demás salieron una sola vez.', 'La corrección se hizo delante del grupo. No hay personas sin registrar.']),
      doc('Regreso', 'Control del acceso', ['22:57. Entran ocho personas. Samuel quiere cerrar para ir a comer. Le pedimos que espere: Isabel acompañaba a una vecina y vuelve más despacio.', '23:14. Isabel entra sola después de dejar a la vecina en su refugio. La vecina no pertenecía a este grupo ni cruzó este control. Con Isabel regresaron todos los que salieron.'], [['Samuel', 'Ficha 8892'], ['Isabel', 'Ficha 4716'], ['Joel', 'Ficha 6390']]),
      doc('Nota', 'Escrito por Samuel', ['Dejé una silla junto al control. Ayer me apuré porque estaba cansado y porque desde aquí ya no se oían pasos. No era razón para cerrar.', 'La próxima vez alguien espera sentado hasta comprobar el último regreso. Si me toca a mí, guárdenme comida.']),
    ], answer: '0916', hints: ['Doce renglones no equivalen a doce personas que salieron.', 'Resta las dos personas que se quedaron y el renglón duplicado. El regreso confirma ese total.', 'Regresaron nueve personas. Isabel fue la última y su ficha termina en 16.'],
    explanation: '12 renglones menos 2 ausentes y 1 duplicado son 9 personas. Isabel fue la última en entrar; su ficha termina en 16. La clave es 0916.',
    success: 'El acceso libera el paso. Hay espacio para rodear la zona ocupada del andén. La silla de Samuel está todavía junto a la puerta, orientada hacia el lugar por donde debía volver Isabel.',
  }),
  numeric('archivo', {
    id: 'archivo-orden', title: 'La orden que nadie cerró', location: 'Los Leones · archivo de mantenimiento', difficulty: 'Intermedia',
    intro: 'En el taller no siempre coinciden el trabajo realizado y el papel que lo describe. Guzmán pidió conservar las órdenes antiguas porque algunos repuestos siguen identificados con sus números. Esta puerta acepta el número de la intervención que dejó operativo el cierre. La carpeta contiene una reparación concluida, otra anulada y una prueba que se presentó como solución antes de tiempo.',
    instruction: 'Encuentra la orden de seis cifras que dejó el cierre reparado y entregado.',
    inscription: 'Validar con la orden ejecutada y recibida. Una prueba o una solicitud no habilitan el paso.',
    documents: [
      doc('Órdenes', 'Carpeta de intervenciones', ['Las hojas están ordenadas por número, no por resultado.'], [['184203', 'Solicitud de cambio completo · anulada por falta de piezas'], ['184207', 'Reparación de pestillo · firma del técnico al dorso'], ['184219', 'Prueba de motor sustituto · pendiente de recepción']]),
      doc('Recepción', 'Lo que se probó con carga', ['Probamos la 184219 sin el peso de la hoja y parecía funcionar. Al montar la puerta, el motor se detuvo. Retiramos el sustituto y no lo dimos por recibido.', 'Volvimos al conjunto reparado en la 184207. Se hicieron tres aperturas con la hoja montada. Mariela recibió las llaves y firmó conforme. Faltó pasar el cierre administrativo a la portada.']),
      doc('Mensaje', 'Guzmán, al turno de mañana', ['No vuelvan a pedir que cambien todo el motor porque la carpeta dice «pendiente». La falla del conjunto viejo estaba en el pestillo. Mariela lo revisó conmigo.', 'Sé que el papel debería estar al día. Cuando hubo que elegir entre entregar el acceso y buscar al encargado del archivo, entregamos el acceso. Ahora dejen anotado qué quedó instalado.']),
    ], answer: '184207', hints: ['El número mayor corresponde a la prueba más reciente, no necesariamente a la reparación válida.', 'La recepción distingue una prueba sin carga de una apertura con la puerta montada.', 'Busca la orden que Mariela recibió después de tres aperturas completas.'],
    explanation: 'La orden 184207 reparó el conjunto que quedó instalado y fue recibido por Mariela. La 184219 falló con carga, aunque su número sea posterior.',
    success: 'El mismo pestillo reparado se retira del marco. El motor trabaja unos segundos y se detiene. La galería abre sin necesitar el repuesto que nunca llegó.',
  }),
  numeric('archivo', {
    id: 'archivo-piezas', title: 'Dos piezas, una devolución', location: 'Plaza de Armas · resguardo técnico', difficulty: 'Avanzada',
    intro: 'Ana pidió que las piezas rechazadas no se mezclaran con las que sí podían instalarse. Aun así, alguien devolvió un rotor en la caja del repuesto bueno. Los números pintados en las cajas dejaron de servir. La ficha del banco de pruebas registra qué rotor y qué sensor quedaron montados en el sistema del acceso; tendrás que seguir las piezas, no sus embalajes.',
    instruction: 'Introduce el número de tres cifras del rotor instalado, seguido del número del sensor aceptado.',
    inscription: 'ROTOR / SENSOR. Usar números grabados en las piezas. Conservar ceros iniciales. No usar etiquetas de caja.',
    documents: [
      doc('Entrega', 'Piezas recibidas en el banco', ['La caja azul decía 318. La caja gris decía 482. Había dos sensores, 076 y 236.'], [['Rotor grabado 318', 'Rodamiento con juego · apartado'], ['Rotor grabado 482', 'Giro estable con carga'], ['Sensor 076', 'Pendiente de prueba húmeda'], ['Sensor 236', 'Pendiente de prueba húmeda']]),
      doc('Pruebas', 'Informe después de limpiar el banco', ['El sensor 236 disparó sin movimiento cuando humedecimos el entorno. No se acepta para esta galería.', 'El 076 respondió al paso de una persona y quedó estable con humedad. Se montó con el único rotor que pasó la prueba de carga.', 'El rotor rechazado volvió dentro de la caja gris. La caja no corresponde a su número grabado.']),
      doc('Nota', 'Una discusión que quedó por escrito', ['La persona que llevó la caja se disculpó tres veces. No hace falta convertir eso en un informe de culpa. Sí hace falta dejar de identificar repuestos por cajas que reutilizamos todos los días. — Ana', 'Entregado: conjunto probado, instalado y funcionando. Los embalajes vacíos quedaron bajo el banco.']),
    ], answer: '482076', hints: ['Sigue los números grabados; las cajas se intercambiaron.', 'Solo un rotor pasó la carga y solo un sensor pasó la prueba húmeda.', 'El rotor válido es 482. El sensor que no disparó con humedad conserva un cero al principio.'],
    explanation: 'Se instalaron el rotor 482 y el sensor 076. La etiqueta equivocada de la caja no cambia esos números: 482076.',
    success: 'El sistema responde al primer movimiento de la hoja. No se activa la alarma de paso. Por el corredor puedes cruzar sin entrar al andén principal.',
  }),
  numeric('archivo', {
    id: 'archivo-llave', title: 'La puerta quedó a su nombre', location: 'Franklin · vestuario de personal', difficulty: 'Avanzada',
    intro: 'Mauro figuraba como responsable del acceso, pero lleva varios días en otra estación. Celia se hizo cargo cuando hubo que alojar a dos familias en el vestuario. El archivo conserva la autorización vieja y un recibo nuevo escrito en el reverso de una ficha. El panel utiliza la identidad de quien conserva la llave, no la de quien ocupa el cargo en una lista.',
    instruction: 'Combina la ficha de cuatro cifras de quien recibió la llave con las dos cifras del gancho donde se guardaba.',
    inscription: 'Custodia vigente: FICHA + GANCHO DE ORIGEN. No usar el casillero personal del encargado.',
    documents: [
      doc('Personal', 'Libro de responsables', ['El libro se actualiza cuando vuelve el encargado de archivo. La última modificación es de hace una semana.'], [['Mauro', 'Ficha 6418 · responsable anterior · casillero 12'], ['Celia', 'Ficha 2753 · apoyo de alojamiento · casillero 04'], ['Rafael', 'Ficha 8091 · inventario · casillero 09']]),
      doc('Recibo', 'Entrega efectiva', ['Mauro pidió por radio que Celia conservara la llave hasta que las familias tuvieran otro lugar. Rafael la retiró del tablero y se la entregó a ella. Rafael solo hizo el traslado.', 'Celia firmó: «La recibí. No la voy a dejar en mi casillero; la llevo conmigo para abrir de noche si hace falta».']),
      doc('Tablero', 'Ganchos del juego de llaves', ['Hay tres siluetas dibujadas para reconocer las llaves incluso con poca luz.'], [['Gancho 04', 'Armario de ropa'], ['Gancho 09', 'Compuerta del vestuario'], ['Gancho 12', 'Almacén de herramientas'], ['Anotación de Rafael', 'La del vestuario salió de su gancho habitual. No moví los carteles.']]),
    ], answer: '275309', hints: ['La custodia la determina el recibo, no el libro antiguo.', 'Rafael transportó la llave, pero Celia la recibió y la conserva.', 'Usa la ficha de Celia y el gancho de la compuerta del vestuario. Su casillero es irrelevante.'],
    explanation: 'Celia, ficha 2753, conserva la llave retirada del gancho 09. La clave vigente es 275309.',
    success: 'El vestuario abre hacia una salida de mantenimiento. Alguien separó el paso de las camas con una cortina para que la gente pudiera dormir aunque otros siguieran cruzando.',
  }),
  numeric('archivo', {
    id: 'archivo-cultivo', title: 'Lo que Beatriz decidió guardar', location: 'Los Libertadores · galería de riego', difficulty: 'Avanzada',
    intro: 'El acceso al riego quedó vinculado al lote que Beatriz apartó como reserva. Dos bandejas cambiaron de lugar durante una filtración; una etiqueta sobrevivió mejor que la otra. Luz anotó el traslado y las pruebas, pero dejó la conclusión para su supervisora. El registro sirve para reconstruir qué se guardó realmente sin confundir la reserva con el cultivo de uso diario.',
    instruction: 'Encuentra las tres cifras del lote reservado y las tres de su bandeja definitiva.',
    inscription: 'LOTE / BANDEJA ACTUAL. La etiqueta del estante no sigue a la bandeja. Solo cuenta la reserva aprobada.',
    documents: [
      doc('Lotes', 'Seguimiento antes de la filtración', ['Los números identifican lotes, no cantidades de plantas.'], [['307', 'Muestra estable · bandeja 042'], ['319', 'Agua turbia en el control · bandeja 024'], ['322', 'Cultivo de consumo diario · bandeja 018']]),
      doc('Traslado', 'Luz anotó cada cambio', ['Saqué el 319 para repetir el control. Su bandeja 024 quedó vacía, la lavamos y Beatriz revisó la limpieza.', 'El soporte de la 042 estaba torcido. Pasamos el lote 307 a la bandeja 024 ya limpia. La 042 quedó sin plantas. El cartel del estante todavía dice 319; no encontré con qué despegarlo.']),
      doc('Decisión', 'Respuesta de Beatriz', ['El segundo control del 319 volvió a salir mal. Sigue apartado y no lo vamos a convertir en reserva por falta de espacio.', 'Guardemos el lote que ya estaba estable. Lo revisé después del cambio de bandeja y está bien. El 322 se sigue usando para consumo. Luz hizo bien en anotar el traslado: sin esa hoja habríamos confiado en el cartel equivocado.']),
    ], answer: '307024', hints: ['El lote y su bandeja son dos identidades distintas.', 'La reserva es el lote estable; su bandeja cambió durante la filtración.', 'El lote 307 terminó en la bandeja 024, aunque el cartel del estante quedó atrasado.'],
    explanation: 'Beatriz aprobó el lote 307, trasladado a la bandeja limpia 024. La etiqueta del estante no se actualizó. La clave es 307024.',
    success: 'La compuerta deja oír el goteo regular del riego. El pasillo técnico rodea los cultivos sin obligarte a cruzar la zona expuesta. La bandeja de reserva tiene una etiqueta nueva escrita a mano.',
  }),
  numeric('archivo', {
    id: 'archivo-traslado', title: 'El último traslado', location: 'Vicuña Mackenna · enlace interior', difficulty: 'Avanzada',
    intro: 'La carpeta describe el traslado de un grupo por una galería interior. El horario previsto se copió en dos formularios antes de que alguien comprobara si el carro pasaba por la puerta. Una mujer regresó a buscar una cantimplora y quedó contada otra vez por un observador distinto. Nadie desapareció; el problema está en cómo se escribió una salida que no ocurrió exactamente como se había planeado.',
    instruction: 'Introduce la hora efectiva de salida, HHMM, seguida del número de personas distintas, con dos cifras.',
    inscription: 'SALIDA EFECTIVA / PERSONAS. No usar llegada, horario previsto ni cantidad de cruces.',
    documents: [
      doc('Horario', 'Plan y cierre de la operación', ['El formulario de planificación indica salida a las 23:20. La recepción del otro extremo ocurrió a las 00:08 del día siguiente.', 'El control final confirma que todos llegaron juntos; no hubo incorporaciones durante el trayecto.']),
      doc('Demora', 'Anotación junto al marco', ['El carro no pasaba con la manilla lateral. Entre desmontarla y volver a asegurar la carga perdimos veinte minutos desde la hora prevista.', 'Salieron inmediatamente después de ese trabajo, sin otra espera. Yo acompañé el carro hasta la primera curva. — Daniela']),
      doc('Conteo', 'Dos observadores, una misma persona', ['El grupo estaba formado por cinco adultos y dos niños. Marta cruzó, volvió a buscar su cantimplora y cruzó de nuevo.', 'La segunda hoja dice ocho porque volvió a contar a Marta. Ella pertenece a los cinco adultos iniciales; no se sumó nadie más.', 'Marta pidió que no retaran al muchacho del control. Era su primera noche y él mismo vino a decir que los números no le cuadraban.']),
    ], answer: '234007', hints: ['Debes corregir tanto la hora planificada como el conteo de cruces.', 'La salida se demoró veinte minutos. Marta no es una persona adicional.', '23:20 más veinte minutos da la hora de salida. Cinco adultos y dos niños suman siete personas.'],
    explanation: 'La salida efectiva fue a las 23:40 y viajaron siete personas distintas. En el formato solicitado, la clave es 234007.',
    success: 'La hoja de acero libera el enlace interior. Una marca nueva en el marco señala por dónde pasó el carro después de quitarle la manilla.',
  }),
  circuit({
    id: 'continuidad-corte', title: 'La luz no abre la puerta', location: 'Los Héroes · gabinete de servicio', difficulty: 'Inicial', maxBridges: 1,
    intro: 'La lámpara funciona, pero el pestillo no se mueve. Claudia dejó un puente de servicio para quien viniera con un medidor. Su hijo le ayudó a sujetar la linterna; la anotación que dice «sí hay luz» es de él. Ella agregó debajo que eso no prueba que la orden llegue al cierre. Puedes comprobar cada tramo antes de intentar abrir.',
    instruction: 'Mide dos puntos, localiza el corte e instala un puente sin saltarte el fusible ni el cierre.',
    inscription: 'Una luz encendida no confirma el cierre. Medir primero. Dispones de un puente de servicio.',
    documents: [
      doc('Circuito', 'Recorrido que debe conservarse', ['La orden debe ir del punto 1 al 4 con una lectura de 2 Ω o menos. El fusible y la bobina del cierre deben quedar dentro del recorrido, sin puentearlos.'], [['1 → 2', 'Fusible de protección'], ['2 → 3', 'Cable de mando'], ['3 → 4', 'Bobina del cierre'], ['5 → 6', 'Lámpara independiente · mantener aislada del mando']]),
      doc('Claudia', 'Nota bajo la tapa', ['Revisé los bornes apretando de a uno, porque ya nos pasó que mover todo junto arregla algo sin saber qué era.', 'No unas directamente entrada y salida aunque el medidor pite. Estarías dejando fuera la protección. La lámpara tiene su propio circuito; encenderla no abre esta puerta.']),
      doc('Medidor', 'Cómo comprobarlo', ['Teclea dos puntos del 1 al 6, o tócalos en el gabinete, y pulsa MEDIR. OL significa que no hay continuidad. Hasta 2 Ω sirve para este cierre.', 'Medir no gasta intentos. Instalar un puente tampoco. PROBAR CIERRE consume uno. El medidor incluye los puentes instalados; puedes quitarlos y volver a medir.']),
    ],
    edges: [[1,2,0.3],[3,4,0.4],[5,6,0.2]], required: [[1,4,2]], isolated: [[1,5],[1,6]], protected: [{edge:[1,2],route:0,name:'fusible'},{edge:[3,4],route:0,name:'bobina del cierre'}], sampleSolution: [[2,3]],
    hints: ['Compara las lecturas de 1–2, 2–3 y 3–4.', 'El fusible y la bobina conducen. Falta el cable entre ellos.', 'El puente debe recuperar 2–3; así la señal sigue atravesando 1–2 y 3–4.'],
    explanation: '1–2 y 3–4 ya conducen. Un puente 2–3 recupera el mando sin excluir el fusible ni la bobina. La lámpara 5–6 permanece separada.',
    success: 'El relé golpea una vez. La luz sigue igual, pero ahora el pestillo sí retrocede. La galería de servicio queda disponible.',
  }),
  circuit({
    id: 'continuidad-resistencia', title: 'Pita, pero no alcanza', location: 'República · gabinete húmedo', difficulty: 'Intermedia', maxBridges: 1,
    intro: 'El turno anterior marcó todos los cables como buenos porque el medidor detectaba contacto. Aun así, la puerta no abre. El gabinete tiene humedad en la base. Ernesto dejó por escrito cuánto trabajo perdió confiando en un pitido y no mirando el valor. Hay un único puente seco, protegido dentro de una bolsa de tela.',
    instruction: 'Busca el tramo con resistencia excesiva y recupéralo sin anular la protección.',
    inscription: 'No basta con que exista contacto. De 1 a 4 necesitamos 2 Ω o menos. Un puente disponible.',
    documents: [
      doc('Plano', 'Mando de apertura', ['El circuito es 1 → 2 → 3 → 4. El tramo 1–2 contiene el fusible; 3–4 contiene el cierre. Ambos deben seguir en el recorrido.'], [['2–3', 'Cable inferior · zona de humedad'], ['5–6', 'Piloto auxiliar · circuito separado'], ['Límite del mando', '2 Ω entre 1 y 4']]),
      doc('Ernesto', 'Corrección del diagnóstico', ['Ayer di por bueno el cable porque el instrumento hizo un sonido. Fue un error. Hay contacto, sí, pero el cierre no recibe lo que necesita.', 'El puente se puede poner sobre el tramo dañado. No hace falta reemplazar el fusible sano ni juntar el piloto con el mando. Si algo marca alto, miren por qué antes de cambiar otra pieza.']),
      doc('Instrumento', 'Interpretar la lectura', ['OL: circuito abierto. Un número alto: hay contacto, pero la resistencia puede impedir abrir. Hasta 2 Ω: recorrido aceptable para este panel.', 'Puedes medir todas las veces que quieras. Después de instalar el puente, comprueba otra vez de 1 a 4 antes de gastar un intento de apertura.']),
    ], edges:[[1,2,0.2],[2,3,18],[3,4,0.3],[5,6,0.2]],required:[[1,4,2]],isolated:[[1,5],[1,6]],protected:[{edge:[1,2],route:0,name:'fusible'},{edge:[3,4],route:0,name:'bobina del cierre'}],sampleSolution:[[2,3]],
    hints:['Mide cada tramo y compara los valores, no solo la presencia de contacto.','El tramo de la parte húmeda tiene una resistencia muy superior al resto.','El puente 2–3 reduce la resistencia del recorrido completo sin saltar las protecciones.'],
    explanation:'El cable 2–3 tiene 18 Ω. Un puente en ese tramo ofrece un recorrido de baja resistencia; 1–2 y 3–4 siguen cumpliendo sus funciones.',
    success:'El cierre vuelve a responder. La puerta abre lentamente, con una marca húmeda donde el marco tocaba el suelo. El puente sostiene el paso hasta que llegue un cable de reemplazo.',
  }),
  circuit({
    id: 'continuidad-alarma',title:'El cable del mismo color',location:'Los Leones · derivación de aviso',difficulty:'Intermedia',maxBridges:1,
    intro:'Repararon este tablero usando lo que quedó de otros gabinetes. Dos cables rojos van a sistemas distintos. Uno pertenece al cierre y el otro activa una campana que antes avisaba al personal. Ahora esa campana se oye demasiado lejos. El técnico retiró las etiquetas falsas, dejó los números y escribió qué contactos comprobó de verdad.',
    instruction:'Recupera el mando del punto 1 al 6 manteniendo aislada la campana.',
    inscription:'No sigas el color. La campana tiene su propio lazo. Un puente; ninguna unión al aviso.',
    documents:[
      doc('Asignación','Números comprobados en terreno',['Los colores de las fundas no identifican funciones. Esta hoja se escribió siguiendo físicamente cada conductor.'],[['1–5','Entrada a través del fusible'],['2–6','Bobina del cierre'],['3–4','Lazo de la campana · debe quedar separado'],['Mando completo','De 1 a 6, máximo 2 Ω']]),
      doc('Reparación','Nota de Guzmán',['El rojo que va hacia arriba no es el que va hacia el cierre. Los pusimos iguales porque era el cable que había, no para que alguien adivinara después.', 'Hice las mediciones y dejé los números. No unan entrada y bobina por los extremos si con eso saltan el fusible. La gente del puesto quiere usar esta puerta sin hacer sonar la campana.']),
      doc('Acuerdo','Mensaje de quienes cuidan el paso',['Anoche la campana despertó a todo el refugio. Nadie se enojó por despertarse; nos enojamos porque salimos a buscar a alguien que no estaba pidiendo ayuda.', 'Dejen el aviso conectado a su propio lazo. Necesitamos que funcione cuando de verdad lo usemos.']),
    ],edges:[[1,5,0.3],[2,6,0.4],[3,4,0.2]],required:[[1,6,2]],isolated:[[1,3],[1,4]],protected:[{edge:[1,5],route:0,name:'fusible'},{edge:[2,6],route:0,name:'bobina del cierre'}],sampleSolution:[[2,5]],
    hints:['Identifica con el medidor los tres pares que ya conducen.','Debes unir la salida del fusible con la entrada de la bobina. La campana no participa.','La salida protegida es 5 y la entrada de la bobina es 2.'],
    explanation:'El puente 2–5 une el fusible 1–5 con la bobina 2–6. El lazo de campana 3–4 permanece aislado.',
    success:'La hoja empieza a moverse. No suena la campana. Del otro lado, el personal del puesto puede seguir trabajando sin abandonar sus tareas para revisar una falsa alarma.',
  }),
  circuit({
    id:'continuidad-doble',title:'Dos cortes, una protección',location:'Franklin · cámara de enlace',difficulty:'Avanzada',maxBridges:2,
    intro:'Un carro enganchó el mazo del gabinete. El fusible, el contacto de seguridad y la bobina siguen funcionando, pero quedaron separados. Inés dejó dos puentes. También dejó una advertencia porque alguien propuso abrir conectando la alimentación directamente al cierre. El contacto central impide mover la hoja cuando una persona está en el paso.',
    instruction:'Reconecta los tres tramos con dos puentes. El contacto de seguridad debe seguir en el recorrido.',
    inscription:'No anular la seguridad para ganar tiempo. Mando 1 → 6. Dos puentes disponibles.',
    documents:[
      doc('Tramos','Elementos que se deben conservar',['Cada componente está sano. El problema está en las uniones entre ellos. El contacto de seguridad es reversible: sus extremos 3 y 4 pueden intercambiarse.'],[['1–2','Fusible'],['3–4','Contacto de seguridad'],['5–6','Bobina del cierre'],['Recorrido final','De 1 a 6, máximo 2 Ω, pasando por los tres componentes']]),
      doc('Inés','Por qué no hicimos el puente directo',['Cuando se movió el carro, Matías estaba recogiendo una correa dentro del marco. El contacto de seguridad cortó la orden. Si lo dejamos fuera del circuito, la próxima vez la puerta podría seguir moviéndose.', 'Nos faltan dos cables, no una excusa para sacar la protección. Hay dos puentes en el cajón. Pruébenlos antes de llamar al grupo.']),
      doc('Comprobación','Después de reconectar',['Mide el recorrido completo. Si queda abierto, revisa qué bloque sigue suelto. Si hay continuidad pero saltaste un componente, el diagnóstico de apertura rechazará la configuración.', 'Puedes retirar cualquier puente sin gastar intentos. La prueba final comprueba también que las protecciones no tengan un desvío alrededor.']),
    ],edges:[[1,2,0.2],[3,4,0.2],[5,6,0.3]],required:[[1,6,2]],isolated:[],protected:[{edge:[1,2],route:0,name:'fusible'},{edge:[3,4],route:0,name:'contacto de seguridad'},{edge:[5,6],route:0,name:'bobina del cierre'}],sampleSolution:[[2,3],[4,5]],
    hints:['Unir solo el fusible a la bobina deja fuera el contacto de seguridad.','Piensa en tres bloques en serie: fusible, seguridad y cierre.','Una opción válida es 2–3 y 4–5. También sirve invertir los extremos del contacto reversible: 2–4 y 3–5.'],
    explanation:'Los puentes 2–3 y 4–5 mantienen los tres componentes en serie. También se acepta 2–4 y 3–5: el contacto central es reversible. No se acepta saltar la protección.',
    success:'La compuerta abre al terminar la comprobación del contacto. Inés dejó el paso despejado para probarlo: esta vez nadie tiene que sostener la hoja mientras los demás cruzan.',
  }),
  circuit({
    id:'continuidad-dos-redes',title:'Abrir sin apagar el aire',location:'Los Libertadores · acceso de ventilación',difficulty:'Avanzada',maxBridges:2,
    intro:'El cierre y la ventilación comparten gabinete, pero tienen alimentaciones separadas. Una reparación apresurada dejó ambos sistemas unidos. Al abrir se detenía el ventilador, y quienes trabajaban en el cuarto debían salir. Beatriz pidió devolver cada circuito a su alimentación. Hay dos puentes disponibles y una hoja donde el técnico identificó las salidas protegidas.',
    instruction:'Recupera cierre y ventilación con dos puentes, manteniendo separadas las dos alimentaciones.',
    inscription:'Dos circuitos. CIERRE 1 → 4 / AIRE 2 → 5. No unir las redes. Máximo 2 Ω en cada recorrido.',
    documents:[
      doc('Bornes','Identificación después de desmontar el cruce',['El cableado cruzado anterior ya fue retirado. Solo quedan las dos alimentaciones protegidas.'],[['1–6','Alimentación del cierre a través de su fusible'],['4','Entrada del cierre'],['2–3','Alimentación del ventilador a través de su fusible'],['5','Entrada del ventilador']]),
      doc('Turno','Lo que pasaba al abrir',['Cada vez que cruzaba alguien se detenía el aire. Al principio pensamos que era otra caída de la batería. Después Luz se quedó mirando mientras pasaban dos personas y vio que coincidía con la apertura.', 'No podemos pedirle al equipo que deje de entrar mientras trabajamos. El acceso y el aire tienen que poder funcionar a la vez. — Beatriz']),
      doc('Condiciones','Recepción de la reparación',['La apertura se acepta solo si 1 llega a 4 y 2 llega a 5, conservando ambos fusibles. Las redes de 1 y 2 deben quedar sin continuidad entre sí.', 'Antes de probar el cierre, mide ambos recorridos y comprueba que 1–2 siga marcando OL. Las lecturas incluyen los puentes que hayas instalado.']),
    ],edges:[[1,6,0.3],[2,3,0.3]],required:[[1,4,2],[2,5,2]],isolated:[[1,2]],protected:[{edge:[1,6],route:0,name:'fusible del cierre'},{edge:[2,3],route:1,name:'fusible del ventilador'}],sampleSolution:[[4,6],[3,5]],
    hints:['Cada salida protegida debe volver a su propio equipo.','El punto 6 sale del fusible del cierre; el 3, del fusible del ventilador.','Une 6–4 y 3–5. Comprueba 1–4 y 2–5; 1–2 debe permanecer abierto.'],
    explanation:'6–4 recupera el cierre y 3–5 recupera el ventilador. Los fusibles siguen dentro de sus recorridos y las dos alimentaciones permanecen separadas.',
    success:'La compuerta se abre y el ventilador mantiene su ritmo. El aire sigue entrando mientras cruzas hacia la galería. Nadie necesita abandonar el cuarto para dejar pasar al grupo.',
  }),
];
