"use strict";
// Reading-only additions run after conditional scene adapters. Existing facts,
// choices and saved outcomes remain the source of truth.
var chapterOnePassages={
 "d1-signal":[
  "La voz volvió a oírse mientras ajustaban las mochilas. Salía del receptor de Elías con el mismo corte al principio y una respiración breve antes de cada repetición. Cerca del mesón, alguien dejó de contar sus compras para escuchar. Otro vecino siguió trabajando: llevaba demasiadas mañanas oyendo rumores de la superficie como para detenerse por uno más. Elías bajó el volumen. Todavía no sabían si aquello seguía emitiéndose desde una sala ocupada o si una máquina repetía la llamada de alguien que ya no estaba.",
  "Sara pidió que anotaran la hora de salida. El encargado buscó un espacio en una hoja llena de nombres y puso una regla sobre el último renglón. Noa observó la columna destinada al regreso; algunos espacios llevaban meses en blanco. Cuando le tocó firmar, movió la hoja para que Sara pudiera apoyar también el codo.\n\n—La reserva pesa poco —dijo Mara—. Lo que no puedo hacer es entregarla dos veces.\n\nElías dejó de probar el contacto de la celda. Aún estaban a tiempo de decidir qué llevar y qué dejar para quienes esperarían allí."
 ],
 "d1-council":[
  "La carpeta tenía esquinas nuevas sujetando hojas mucho más antiguas. Sara alcanzó a distinguir tachaduras y un número escrito sobre otro antes de que el anciano la cerrara. Noa apoyó el mapa junto a su mano, sin intentar quitársela. En el pasillo seguían preparando los carros de la próxima salida. Cada tanto un golpe de rueda impedía oír lo que se decía alrededor de la mesa.",
  "—Si falta alguien, nosotros también vamos a tener que explicarlo —dijo Noa.\n\nEl anciano miró las tres mochilas. Habló de quienes habían dejado de salir después de escuchar relatos de la superficie, de turnos que otros tuvieron que cubrir. Sara lo dejó terminar. Después volvió a pedir un dato concreto: cómo reconocer a aquellos cuerpos antes de tenerlos delante. Elías abrió su cuaderno por una página limpia. No quería llevarse una promesa de que todo estaría bien; necesitaba algo que pudiera comprobar cuando se cerrara la compuerta. La mano del anciano permaneció sobre los registros."
 ],
 "d1-gate":[
  "La pintura del marco había saltado alrededor de los pernos. Noa iluminó primero el suelo y después la ranura inferior; una marca de arrastre desaparecía debajo de la hoja metálica. Elías le pidió que mantuviera quieta la linterna. La cerradura seguía recibiendo corriente de algún ramal que los planos del refugio daban por inactivo. Al acercar la oreja reconoció un pequeño relé, insistente, detrás del roce más pesado del otro lado.",
  "Sara señaló los cables que salían hacia el techo.\n\n—¿Alimentarlo avisa que estamos acá?\n—Le permite leer —respondió Elías—. No es lo mismo que saber a quién va a encontrar.\n\nNoa probó con el pie la primera sujeción del ducto superior. El óxido cayó sobre su manga. Por allí tendrían que subir las mochilas antes que los cuerpos y avanzar sin espacio para volverse. La puerta ofrecía un paso más ancho, pero aquello que raspaba al otro lado dejaba de hacerlo cada vez que hablaban. Noa se apartó lo suficiente para cubrir ambas salidas."
 ],
 "d1-ration":[
  "La niña tenía un zapato puesto y el otro entre las manos de un adulto. No se quejaba; seguía con la mirada el recipiente de agua. A su lado, una mochila abierta dejaba ver cartuchos envueltos por separado y piezas que alguien había limpiado hasta quitarles casi todo el óxido. Habían separado lo que podían ofrecer sin desarmar el equipo con que pensaban salir a cazar.",
  "Sara se agachó para hablar a la altura de la niña. Preguntó desde cuándo tenía fiebre y escuchó la respuesta sin abrir todavía su mochila. Noa revisó el paso que acababan de dejar atrás. Elías esperó junto a las piezas; reconoció un conector que podría servirles más adelante y volvió a dejarlo en su sitio.\n\n—No les estamos pidiendo todo —dijo uno de los cazadores.\n\nSara asintió. Sabía cuánto quedaba en las reservas del grupo, pero no cuánto iban a necesitar antes de encontrar un lugar seguro. La niña terminó de ponerse el zapato mientras los mayores seguían esperando una respuesta."
 ],
 "d1-red-lights":[
  "Noa levantó una mano y los otros se detuvieron antes de entender por qué. El cable casi no se distinguía contra el suelo. Más allá había trozos de tela atados a las columnas, algunos recientes, otros endurecidos por el polvo. Sara vio una taza junto a una manta enrollada. Aquel paso tenía habitantes, aunque desde los mapas de Los Héroes solo apareciera como una galería de tránsito.",
  "Una de las figuras golpeó dos veces el hormigón. La que estaba más cerca del cable retrocedió medio paso, dejando libre una línea hacia el centro del grupo. Noa siguió ese movimiento con el arma, sin levantarla del todo.\n\n—Nos están dando un límite —murmuró Sara.\n—O espacio para que crucemos —respondió Noa.\n\nElías buscó las caras detrás de los visores. Las prótesis no encajaban entre sí: una mano industrial, una rodilla sujeta con correas, un protector de otro tamaño. Ninguno de esos detalles les decía qué harían si el grupo avanzaba. Para hablar tendrían que exponerse; para retroceder, apartar la vista del camino que venía hacia ellos."
 ],
 "d1-flood":[
  "No se veía el fondo. Bajo la luz de la linterna flotaban hebras de plástico y una etiqueta que giraba en círculos antes de perderse junto a la pared. Elías hundió una vara hasta tocar el borde de un durmiente; al moverla un poco dejó de encontrar apoyo. La corriente parecía débil desde la orilla, pero empujó la madera cuando la sostuvo atravesada.",
  "Sara comprobó los cierres de su mochila y señaló la caja del otro lado. La habían puesto suficientemente alta para que el agua no la alcanzara. Noa buscó dónde afirmar una cuerda y tiró de una argolla hasta hacer crujir el soporte.\n\n—Si cae la mochila, la sueltan —dijo.\n\nElías miró los cables sumergidos. Podían cruzar sujetos y confiar en los apoyos que fueran encontrando, o gastar energía para aislar el circuito. El rodeo evitaba entrar al agua, aunque obligaba a volver atrás y arrastrar el equipo por ventilación. Sara se ajustó la correa del pecho; aún no había dado el primer paso."
 ],
 "d1-camp":[
  "Sara se detuvo antes de tocar el primer lecho. A un costado habían dejado unas botas abiertas, con los calcetines puestos a secar sobre el cordón. La olla contenía una costra que todavía se desprendía con el calor. Noa revisó el espacio detrás de las mantas. Elías llamó una vez y esperó; desde la galería llegó únicamente el golpeteo irregular de una cañería.",
  "No había manera de saber cuánto tardaría en volver alguien, si es que alguien pensaba hacerlo. Las marcas tachadas podían indicar una retirada o una advertencia para los siguientes viajeros. Elías quiso compararlas con su cuaderno, pero Noa le pidió que primero mantuviera libre el paso.\n\nSara leyó el mensaje otra vez.\n—¿Sus núcleos?\n\nNadie respondió. El rastro hacia la casa de bombas estaba allí para seguirlo. También había comida y equipo al alcance de la mano. Noa puso una piedra junto al sitio donde habían entrado; si debían salir deprisa, no quería buscar de nuevo la abertura entre los lechos."
 ],
 "d1-pump":[
  "El ruido se sentía antes de llegar a la sala. Cada arranque de la bomba hacía vibrar una baranda y expulsaba aire por una unión mal sellada. Elías comparó el nivel del agua con una raya pintada en la pared: alguien lo había estado vigilando. Sobre el tablero quedaban herramientas ordenadas por tamaño, demasiado lejos para alcanzarlas desde la entrada.",
  "Noa hizo que se agacharan detrás de una tubería. Desde allí podía ver las placas del guardián y solo una parte del espacio que debía cubrir. Sara buscó una salida para el grupo; no encontró ninguna que no los obligara a pasar de nuevo cerca de la máquina.\n\n—No dispares al tablero —pidió Elías.\n—Entonces dime dónde puedo moverme.\n\nÉl señaló el cierre manual y después el punto donde podría poner el señuelo. Tendrían que coordinarlo sin gritar sobre el ruido. Seguir de largo les ahorraba ese enfrentamiento, pero la raya del agua les recordaba que aún necesitaban una ruta por la que volver."
 ],
 "d1-matias":[
  "Primero vieron una mano. Salía por debajo del mostrador, cerca de un recipiente vacío. Sara dejó la linterna en el suelo para no apuntarle a los ojos y le dijo su nombre antes de acercarse. Matías trató de acomodar las piernas; el movimiento le cortó una palabra. Noa apartó un trozo de vidrio con la bota y se quedó mirando la entrada.",
  "Elías puso el receptor donde el hombre pudiera oírlo. Matías reaccionó al patrón de la señal antes de entender la pregunta. Quiso explicar algo sobre los cambios de ruta, pero Sara le pidió que respirara primero.\n\n—¿Cuánto puedes caminar?\n\nÉl miró el espacio entre el mostrador y la puerta. No respondió. Sara conocía esa manera de medir una distancia. Tendría que estabilizarlo antes de intentar moverlo, y después alguien cargaría una parte del peso durante el regreso. Noa comprobó las correas de las mochilas para ver qué podían convertir en un apoyo. Aún podían irse con una frecuencia o con un mapa. Matías seguía allí."
 ],
 "d2-drone-pulse":[
  "La sombra de la unidad cortó la claridad del pozo. Noa buscó con la mano a quien venía detrás y lo hizo detenerse contra el muro. El sonido del motor cambiaba cada vez que la óptica pasaba de una superficie húmeda a otra seca. Elías reconoció el ritmo de comparación, aunque no podía ver qué identidad esperaba encontrar el lector.",
  "Sara apoyó dos dedos sobre su propia muñeca. Había pasado la noche atendiendo necesidades mucho más concretas que una cifra en la pantalla de un dron; ahora debía pensar en cómo bajar el pulso sin saber si ya lo estaban leyendo.\n\n—No nos separemos todavía —murmuró.\n\nElías localizó una caja de alimentación a pocos pasos. Llegar hasta ella significaba salir de la cobertura. Noa podía atacar desde donde estaba, pero no asegurar que la unidad cayera antes de enviar su lectura. La subida seguía abierta detrás del aparato. Ninguno podía utilizarla sin entrar primero en el espacio que barría su óptica."
 ],
 "d2-republica":[
  "El aire de la escalera traía un olor que abajo casi no llegaba: tierra húmeda, hojas y algo quemado mucho más lejos. Sara se quedó un momento bajo la última sombra antes de mirar hacia arriba. Había ventanas abiertas en fachadas donde ya no quedaban pisos. Elías protegió el receptor con la mano; la señal era más clara allí, pero también podía oír otros aparatos buscando frecuencia.",
  "Noa no discutió todavía cuál era el mejor camino. Pidió que miraran lo que ella veía: una franja descubierta, un acceso donde tendrían que pasar de uno en uno y varias marcas que podían haber cambiado desde la última visita de un cazador. Sara señaló dónde podrían detener a alguien herido. Elías buscó una referencia que pudiera conservar aunque perdieran recepción.\n\nDurante un momento hablaron de una esquina concreta, de la distancia hasta una pared, del peso de una mochila. Esa era la parte del plan que podían acordar antes de subir. Lo demás tendrían que revisarlo al encontrarse con la calle."
 ],
 "d2-alameda":[
  "Un trozo de papel cruzó la avenida sin que ninguna óptica lo siguiera. En cambio, una columna de aire que salía de una rejilla hizo girar al dron más bajo. Elías observó el movimiento desde el marco de un local. La unidad alta permanecía casi inmóvil; no necesitaba acercarse para recibir lo que detectara la otra.",
  "Sara quiso saber si el subterráneo salía al otro lado o si solo los alejaría de la torre. Noa señaló las escaleras visibles y admitió que no conocía el resto. Sobre el asfalto quedaban vehículos que parecían ofrecer cobertura hasta que se miraban desde arriba.\n\n—Si cae uno, el otro va a verlo —dijo Elías.\n\nNoa comprobó la línea entre su posición y la rejilla. Sara aseguró lo que colgaba de su mochila. Podían comprometer equipo para engañar la lectura, enfrentarse a las unidades o renunciar al cruce directo. La señal seguía llegando desde el otro lado; no les decía por cuál de esos caminos podrían alcanzarla."
 ],
 "d2-safe-house":[
  "Noa sostuvo la puerta mientras Sara revisaba el suelo. Una silla estaba apartada de la mesa, como si alguien se hubiera levantado esperando volver. En un plato había una pequeña rotura reparada con alambre; los otros tres no pertenecían al mismo juego. Elías dejó la mochila sobre una baldosa seca para no mojar las mantas.",
  "El lugar invitaba a hacer cosas que llevaban horas postergando: sentarse, aflojar las correas, comer sin vigilar un extremo de túnel. Sara encontró el rastro de sangre al buscar dónde apoyar el agua. Lo siguió con la vista hasta la puerta trasera.\n\n—No sabemos cuándo pasó —dijo Elías.\n—Tampoco si van a volver —respondió ella.\n\nNoa revisó el exterior sin alejarse de la entrada. Ninguna de las dos puertas podía vigilarse bien desde la mesa. Si descansaban, tendrían que repartirse ese trabajo. Si seguían el rastro, dejarían atrás la primera habitación en mucho tiempo que parecía preparada para recibir a alguien."
 ],
 "d2-node14":[
  "La pantalla tardó en responder al primer contacto. Bajo el polvo quedaban huellas de distintas manos, unas alrededor del teclado y otras directamente sobre el vidrio. Elías limpió una esquina con la manga. Un indicador cambiaba de fecha cada vez que el terminal intentaba abrir un bloque dañado. Sara acercó la linterna para leer sin tocar nada.",
  "Había nombres de lugares que los tres reconocían y otros que solo habían oído a personas mayores. A veces aparecía un estado de funcionamiento, pero ninguna señal de que alguien lo hubiera confirmado recientemente. Noa preguntó qué consulta podían hacer sin entregar algo a cambio. Elías siguió el cable de red hasta una abertura del suelo.\n\n—No puedo prometer que esto solo reciba —dijo.\n\nSara separó en su cuaderno los datos que buscaban de las preguntas que seguirían abiertas. Encontrar una entrada no era lo mismo que encontrar gente al final de ella. Elías esperó antes de elegir el primer bloque: lo que abrieran podía ser también lo último que conservara aquella memoria."
 ],
 "d2-identity":[
  "La patrulla no disparó al verlos. Esa demora hizo que Noa se detuviera con más cuidado. El agente de la calle levantó el lector, mientras el tirador mantuvo el arma apoyada sobre el borde de una ventana. Sara contó los pasos hasta la entrada de un edificio y dejó de mirar hacia allí cuando vio girar la óptica del dron.",
  "Elías conocía los gestos de una revisión: la mano libre a la vista, el equipo cerrado, una respuesta breve. Ninguno garantizaba que la credencial resistiera la siguiente consulta. El lector podía recordar a otra persona y exigir una señal que el grupo no supiera imitar.\n\n—Que hable uno —susurró Noa.\n\nSara no contestó; estaba observando al hombre del lector, buscando una pausa que perteneciera a él y no al procedimiento. Si atacaban, el tirador tenía la calle medida. Si se escondían, tendrían que hacerlo antes de que cerraran el acceso. Permanecer quietos tampoco iba a detener la comparación."
 ],
 "d2-exposed-core":[
  "Sara dejó un espacio libre entre ella y la camilla. Antes de acercar las manos, preguntó si la mujer podía oírla. El núcleo azul iluminaba una parte de las correas y dejaba la otra en sombra. A Elías le bastó ver el ritmo de esa luz para dejar de tratar el conector como una pieza que pudiera retirarse sin más.",
  "Noa comprobó dónde estaba el arma y volvió a mirar la puerta. Desde fuera, la sala parecía un sitio vacío; desde allí dentro se oía cada paso del corredor. Sara ordenó lo que podía utilizar sin abrirlo todavía. Quería explicar lo que iba a hacer antes de tocar una herida o una conexión.\n\n—El agua te la puedo acercar —dijo—. Para lo demás necesito que me dejes mirar.\n\nElías se arrodilló donde no estorbaba a Sara. Habían visto máquinas que conservaban nombres y otras que vigilaban cuerpos. En esa camilla, una conexión seguía acompañando cada respiración. Cualquier decisión tendría que contar con ese hecho, además de con lo que quedara en las mochilas."
 ],
 "d2-pulse-hunters":[
  "El semáforo cambiaba para una calle sin vehículos. Durante unos segundos pareció una costumbre que la ciudad hubiera olvidado apagar. Después Noa vio moverse una figura cuando el controlador emitió el pulso. En otro balcón, alguien levantó la cabeza exactamente al mismo tiempo.",
  "Elías señaló la caja de control al pie del poste. Tendría que trabajar allí expuesto a las ventanas. Sara buscó dónde podría cubrirlo sin perder de vista a Noa; ninguna posición permitía hacerlo todo. En los patios laterales apenas se veía la primera puerta, seguida por otra hoja metálica y una escalera sin luz.\n\n—No se están moviendo como una patrulla —dijo Noa—. Están esperando que el aparato les diga dónde mirar.\n\nPodían aprovechar esa dependencia o entrar en el cruce sabiendo desde dónde vendrían los disparos. El rodeo les daría distancia, pero también los obligaría a reconocer nuevas salidas con el cansancio del día ya encima."
 ],
 "d2-vera":[
  "El taller olía a aceite y a ropa que no había terminado de secarse. Mientras Vera hablaba, alguien seguía limpiando el mismo engranaje junto a la pared. Nadie fingió que el encuentro fuera privado. Noa eligió un sitio desde el que pudiera ver la puerta y las manos de quienes pasaban detrás de la mesa.",
  "Elías acercó la vista al módulo, sin tocarlo. Podía distinguir reparaciones en la carcasa y un conector que aún conservaba su cubierta original. Sara miraba otra cosa: el espacio del mapa donde Vera esperaba que escribieran.\n\n—Una dirección sirve aunque nosotros nos vayamos —dijo.\n\nVera levantó los ojos. Tenía trabajo acumulado y gente esperando agua, pero eso no aclaraba qué haría después con cada dato. Noa pidió separar las ofertas: qué obtendrían ahora, qué tendrían que entregar y qué seguirían debiendo al salir de la torre. Elías apartó su cuaderno del mapa hasta que hubiera una respuesta para cada parte."
 ],
 "d3-avenue":[
  "La torre aparecía entre dos edificios mucho antes de que hubiera una ruta clara para alcanzarla. Elías comprobó la recepción y guardó el aparato otra vez. Ya no necesitaba sostenerlo a la vista para saber en qué dirección continuar. Noa, en cambio, seguía buscando dónde dejaría de cubrirlos la sombra.",
  "Desde el edificio hundido llegó otra llamada. Sara trató de distinguir cuántas personas había y si podían salir por sus propios medios. Una ventana se cerró un piso más arriba. La patrulla avanzaba sin desviarse, pero el cruce entre ambos recorridos se hacía cada vez más estrecho.\n\n—Si vamos hacia ellos, primero les decimos por dónde salir —dijo Noa.\n\nSara asintió. Correr sin una salida podía convertir al grupo en otra cosa que sacar de allí. Elías revisó el equipo con el que podrían desviar la atención. La torre seguía al fondo, al alcance de la vista; entre ellos y su entrada había personas que no podían esperar a que acabara la misión."
 ],
 "d3-purple-cordon":[
  "Detrás del cordón había luz eléctrica estable. No parpadeaba con el paso de las unidades ni dependía de una lámpara llevada a mano. Sara vio una cortina moverse en una ventana y después quedarse quieta. Las fachadas seguían dañadas, pero las entradas tenían números legibles y puertas capaces de cerrar.",
  "Noa examinó a los guardianes buscando la señal que indicaría quién daba las órdenes. Elías miró los lectores: no parecían dispuestos a aceptar cualquier dato que trajeran desde otros sectores. El grupo había aprendido cosas durante el viaje, aunque aún no sabía cuáles tendrían valor frente a esos cascos.\n\n—Hay gente detrás —dijo Sara.\n\nNoa lo había visto. Por eso buscaba también hacia dónde apuntaban las armas y qué espacio quedaría libre si empezaban a disparar. El derrumbe ofrecía una forma de evitar la línea principal, a costa de exponerse en terreno sin revisar. Para pasar por el cordón tendrían que decidir qué estaban dispuestos a mostrar, pedir o romper."
 ],
 "d3-drone-nest":[
  "Los cables cruzaban la azotea sujetos con fijaciones recientes. Alguien, o alguna unidad de mantenimiento, seguía cuidando aquella instalación. Bajo una cubierta abierta se alineaban los puntos de carga. Elías vio encenderse un indicador lejos de donde se había movido la primera óptica.",
  "—Comparten lo que ven —dijo, señalando el relé.\n\nSara se agachó antes de acercarse al borde. Desde allí distinguía patios y ventanas, pero no podía saber cuáles conservaban habitantes. Noa midió la distancia hasta la escalera por la que habían subido. Si el nido despertaba entero, ese sería el primer camino que tendrían que proteger.\n\nElías preparó el cable sin conectarlo. Podían gastar una pieza que todavía les sirviera en la torre, arriesgarse a sostener el lugar por la fuerza o bajar a buscar otro acceso. Cualquier intervención en el relé debía hacerse sabiendo que los efectos podían llegar más lejos que las máquinas visibles sobre aquella azotea."
 ],
 "d3-dead-without-core":[
  "El vestíbulo conservaba la forma de un lugar por donde alguna vez pasaron muchas personas. Había una línea de espera pintada en el suelo y un mesón caído sobre los primeros escalones. Sara apartó un trozo de tela para no pisarlo y descubrió debajo otra marca de disparo. El polvo hacía difícil distinguir lo que cayó durante el combate de lo que se había desprendido después.",
  "Noa recorrió con la mirada las posiciones antes de acercarse a ningún equipo. Algunas armas apuntaban hacia la misma entrada aunque quienes las llevaban pertenecieran a grupos distintos. Elías sostuvo la luz para que Sara pudiera examinar una correa sin mover el resto.\n\n—Si cambiamos las cosas de sitio, después no vamos a saber —dijo ella.\n\nLo que quedaba podía servirles para reconstruir una historia o para sostener el tramo que aún faltaba. Registrar bolsillos y mecanismos tomaría tiempo junto a lectores que tal vez conservaran energía. También podían continuar dejando aquello como lo encontraron, sin resolver quién había defendido esa puerta."
 ],
 "d3-continuity-door":[
  "La entrada no daba directamente a una escalera. Primero había un tramo iluminado, después una zona de sombra y al fondo otro cierre. Elías contó los sensores visibles sin suponer que fueran los únicos. Noa señaló los pilares que podrían ocultar a una persona; ninguno cubría al grupo completo con las mochilas puestas.",
  "Sara probó la correa que más le había rozado el hombro. Estaban cerca de la señal, pero todavía no sabían qué encontrarían al otro lado ni qué tendrían que cargar al salir. Quiso que acordaran una retirada antes de cruzar. Noa marcó un punto donde podrían reunirse si las puertas los separaban.\n\n—Si abre una, no damos por hecho que abrirá la siguiente —advirtió Elías.\n\nLos permisos y conocimientos del viaje podían cambiar la respuesta de ese acceso. Sin ellos tendrían que enfrentarse a su defensa o dañar parte de la estructura. El ruido que hicieran allí llegaría a una torre que ya parecía estar esperando alguna clase de intrusión."
 ],
 "d3-last-patrol":[
  "Elías se inclinó sobre la consola y volvió a leer la misma secuencia para asegurarse de no confundir una respuesta con una espera. Sara sujetó un cable que se soltaba cada vez que él movía el brazo. Al otro lado de la sala, Noa distinguió el ruido del primer ascensor antes de que apareciera su luz en el panel.",
  "Había más de una puerta por donde podían llegar. Noa arrastró un mueble hasta encontrar una posición que no cerrara también la salida del grupo. Sara miró la distancia entre esa cobertura y la consola; tendría que cruzarla si alguien caía lejos de ella.\n\n—Dime cuándo puedes apartarte —pidió a Elías.\n\nÉl revisó los indicadores antes de responder. No quería prometer unos segundos que la máquina aún no podía darle. Conservar la antena exigía quedarse junto a sus controles. Preparar otra salida permitiría mover al grupo, pero podía dejar atrás el canal que habían venido a buscar. Los pasos de los niveles inferiores empezaron a oírse sin ayuda del panel."
 ],
 "d3-irene":[
  "La habitación era más pequeña de lo que Sara había imaginado durante el viaje. Había un vaso fuera del alcance de la cama y una marca rectangular en la pared donde antes debió colgar algo. La repetición del receptor no llenaba ya aquel espacio: allí podía oírse cuánto le costaba a Irene terminar una frase.",
  "Noa permaneció cerca de la puerta, vuelta a medias hacia el corredor. Elías buscó dónde apoyar el equipo sin mover los cables del soporte. Sara acercó la silla y esperó hasta quedar a la altura de los ojos de Irene. Tenía preguntas sobre la señal, el archivo y las personas cuyos nombres habían ido encontrando. Empezó por preguntarle si esa posición le permitía respirar mejor.\n\nIrene hizo un pequeño movimiento con la mano para que dejara de ajustar la silla. Quería hablar antes de que decidieran por ella. Sara se quedó quieta. Habían recorrido tres jornadas siguiendo una voz que siempre decía lo mismo; ahora podían escuchar lo que no había cabido en aquella grabación."
 ],
 "d3-exiles":[
  "El primer ruido llegó desde el cierre de la cámara. Noa hizo que Elías se apartara de la línea de entrada y buscó una cobertura desde la que no tuviera que disparar a través del grupo. Las figuras que aparecieron miraban hacia el interior, siguiendo algo que reconocían allí antes de detenerse en las armas de los exploradores.",
  "Sara oyó una palabra repetida en voz baja entre los recién llegados. Podía ser un nombre. Elías miró los núcleos almacenados y comprendió por qué habían seguido ese camino hasta la torre. Aun así, no sabía qué aceptarían del grupo ni cuánto recordaban de sus encuentros anteriores.\n\n—Déjenlos hablar —dijo Sara.\n\nNoa no bajó la guardia. La salida que habían conseguido o perdido durante el asedio seguía importando. Compartir una prueba, ofrecer una pieza o defender la cámara tendría un significado distinto para quienes estaban allí buscando a los suyos. Elías esperó antes de levantar el lector: primero necesitaba saber si iban a permitirle mostrarlo."
 ],
 "d3-truth":[
  "Afuera ya no podían distinguir todos los ruidos que venían de la torre. Algunas luces permanecían encendidas; otras habían desaparecido detrás de los muros. Noa comprobó una última vez que los tres pudieran seguir el mismo recorrido. Elías abrió la mochila lo justo para revisar lo que llevaba y volvió a cerrarla.",
  "Sara intentó ordenar lo que tendría que contar al llegar. Había hechos que habían visto los tres, otros que solo conocían por un registro y preguntas que seguían sin respuesta. La versión que llegara al refugio empezaría con esas diferencias. Noa le pidió que esperara a estar bajo techo para escribir. Todavía tenían que recorrer el último tramo con lo que les quedaba de fuerzas."
 ]
};
function chapterOneReading(ev){
 if(ev.chapter===2||ev._expandedReading)return ev;
 var p=chapterOnePassages[ev.id];if(!p)return ev;
 return Object.assign({},ev,{text:p[0]+"\n\n"+ev.text+"\n\n"+p[1],_expandedReading:true});
}
// Additional exchanges in existing detours: no extra clicks, timers or choices.
var chapterOneRouteReading={
 matiasRescue:["Sara enrolla una prenda para sostenerle la cabeza y pide que prueben cómo levantarlo antes de ponerse en marcha. Matías intenta ayudar con el brazo sano. «Avísame cuando te duela», le dice ella. Él responde que ya le duele. Sara lo mira y asiente: «Entonces avísame cuando cambie». Elías mueve su mochila para poder cargar desde ese lado. Noa comprueba que sigan teniendo una mano disponible al llegar a las puertas."],
 rosaIaraRoute:["Rosa recoge el recipiente antes de que ruede bajo la banca. Iara intenta seguirlo con una mano y vuelve a quedarse quieta. Sara espera a que Rosa termine de acomodarla para hacer la siguiente pregunta. A Elías le llaman la atención las marcas, pero no abre el cuaderno sin preguntar. Noa se aparta un poco de la niña con el arma hacia el suelo. Rosa mira ese gesto antes de explicar por dónde pueden seguir."],
 liraExiledCore:["Lira conoce dónde debe pisar, pero no deja de mirar hacia el lugar por donde se llevaron a su hermano. Sara le pregunta si habían cambiado alguna conexión antes del traslado. Lira niega y después corrige la respuesta: oyó hablar de una pieza, no alcanzó a verla. Elías anota la diferencia. Noa les pide que sigan hablando bajo; necesita oír si el ruido del corredor se acerca o permanece al otro lado de la pared."],
 unit7LastOrder:["Sara pregunta a la unidad si puede dejar de repetir la orden. El motor cambia de tono y vuelve al mismo zumbido. Elías le explica que no sabe si la pausa significa una elección o una falla. S-7 sigue frente a ellos. Noa revisa la compuerta que acaba de abrirse: puede ser un camino y también un lugar donde quedar encerrados. Antes de moverse, pide a Elías que compruebe si tendrán cómo abrirla desde dentro."],
 unit12InvisibleMap:["Sara se queda detrás de la carcasa del autobús, cerca de una fila de asientos arrancados. Elías le indica con la mano que espere otro barrido. Noa mira hacia la esquina siguiente y luego hacia la que acaban de dejar: si aprovechan la falla tendrán que hacerlo juntos. En el asfalto, el sensor devuelve el mismo intervalo una segunda vez. Todavía no demuestra que el dron vaya a repetirlo cuando empiecen a moverse."],
 vegaDeadNames:["Vega intenta tapar el resultado con la palma y activa otra consulta. Elías le pide que retire la mano. Sara se dirige a él por su nombre para que la mire, pero el agente sigue observando la fecha que aparece junto a su rostro. Noa oye moverse a la escolta. No pueden darle allí todo el tiempo que necesita. Para salir con él tendrán que decidir qué lectura dejarán en ese aparato y cuál intentarán llevarse."],
 ortegaObedientCity:["Noa ve que uno de los tiradores mantiene el dedo cerca del disparador incluso después de escuchar la orden. Ortega tiene que repetirla mirándolo. Sara espera esa segunda respuesta antes de moverse. Elías comprueba la tensión del cierre con una herramienta; no confía su peso a una autorización verbal. La compuerta sigue bajando despacio. Detrás se alcanzan a ver pasillos con luz, puertas cerradas y una persona que se aparta cuando advierte al grupo."]
};
function expandChapterOneRoutes(){
 Object.keys(chapterOneRouteReading).forEach(function(id){
  var scene=routeNarrativeDefs[id].scenes[0];
  scene.lines=scene.lines.concat(chapterOneRouteReading[id]);
 });
 ireneFinalDialogue.nodes.start.lines.push("Irene mira el receptor de Elías. Le pide que lo apague mientras hablan. Él comprueba que haya dejado de sonar y lo pone boca abajo sobre la mesa. Sara le acerca el vaso sin obligarla a beber. Durante unos segundos solo se oye el soporte. «Pensé que, si contestaba alguien, iba a saber qué pedirle», dice Irene. Se detiene para tomar aire. Sara espera. Noa se vuelve hacia el corredor cuando oye un golpe y después vuelve a mirarlas. La conversación tendrá que ocurrir con ese ruido al otro lado de la puerta.");
 ireneFinalDialogue.nodes.consent.lines.push("Sara revisa la conexión otra vez antes de hacer nada. No confunde haber encontrado un soporte portátil con haber asegurado la salida. Le explica qué pueden preparar dentro de la habitación y qué seguirá dependiendo del camino. Irene la escucha sin apartar la mirada. Elías mantiene el lector sobre la mesa para que vea cuándo termine la copia. Noa pregunta qué necesita Sara para sostener el traslado si esa es la decisión. Nadie toca aún el interruptor. Irene ha podido expresar lo que quiere; ahora el grupo debe responder sabiendo qué puede cumplir y qué no.");
}
expandChapterOneRoutes();
