"use strict";
/* eslint-disable @typescript-eslint/no-unused-vars */

/* Campaña vertical de tres días: nueve situaciones por jornada. */
var CAMPAIGN_EVENTS=[
  {day:1,time:"06:40",loc:"Refugio Línea 1",type:"Preparación",title:"La señal imposible",text:"Durante la noche, una frecuencia prohibida atravesó el blindaje del refugio y repitió tres palabras: «todavía estamos aquí». Los ancianos autorizan una salida breve, pero recuerdan que cada recurso entregado al grupo faltará en la enfermería común.",choices:[
    {label:"Reservar una celda de energía",hint:"Elías podrá alimentar puertas, terminales o una descarga de emergencia.",cost:"Batería +1",title:"Energía bajo custodia",result:"Elías envuelve la celda en tela seca y la guarda lejos de la radio. Nadie celebra: todos conocen las bombas de agua que dejarán de funcionar si no vuelve.",fx:{battery:1,morale:1},flags:{choseBattery:true}},
    {label:"Solicitar el botiquín sellado",hint:"Sara acepta responder ante la comunidad por cada dosis utilizada.",cost:"Medicina +1",title:"Una deuda médica",result:"El botiquín llevaba años reservado para un derrumbe. Sara firma el registro analógico y promete devolverlo, aunque sabe que la superficie rara vez devuelve algo intacto.",fx:{meds:1,morale:-1},add:["medkit"]},
    {label:"Salir con las reservas propias",hint:"Conserva los recursos del refugio y fortalece la confianza de quienes se quedan.",cost:"Moral +4",title:"Viajar ligero",result:"La compuerta se abre sin ceremonia. Las familias observan las mochilas medio vacías y entienden que el grupo no trasladará el costo de la expedición a quienes permanecen abajo.",fx:{morale:4},flags:{refugeTrust:true}}
  ]},
  {day:1,time:"07:25",loc:"Andén de Asamblea",type:"Decisión",title:"Lo que no dicen los sabios",text:"El consejo llama a Sara antes de partir. Ordena investigar la señal, pero prohíbe mencionar a los merodeadores frente a los jóvenes: oficialmente no existen humanos modificados en los túneles. El secreto protege la calma y también protege a quienes lo sostienen.",choices:[
    {label:"Aceptar el silencio del consejo",hint:"Mantiene estable el refugio, pero limita lo que el grupo podrá contar al volver.",cost:"Moral −2",title:"Una orden sin testigos",result:"Sara asiente y guarda la instrucción junto al mapa. Noa no discute, aunque deja claro que una verdad escondida puede ser más peligrosa que una patrulla.",fx:{morale:-2,threat:-1},flags:{keptElderSecret:true}},
    {label:"Exigir acceso a los archivos",hint:"Prueba social. Puede revelar por qué se prohibió la tecnología de rastreo.",cost:"Dificultad 12",roll:{dc:12,bonus:2,success:{title:"El registro de los exiliados",result:"Un anciano entrega una hoja sin firma: la primera expedición a El Valle volvió con implantes y fue expulsada. Los merodeadores no aparecieron de la nada; alguna vez fueron Rotos.",fx:{morale:3},archive:["exiles"],flags:{knowsExiles:true}},fail:{title:"La puerta del archivo",result:"El consejo cierra filas y acusa al grupo de retrasar la salida. La negativa confirma que existe algo importante detrás del relato oficial.",fx:{morale:-3,threat:1},flags:{distrustCouncil:true}}}},
    {label:"Prometer que cada superviviente decidirá",hint:"No desafía abiertamente al consejo, pero deja la verdad en manos del grupo.",cost:"Sin recursos",title:"Una promesa entre tres",result:"Fuera de la sala, Sara, Elías y Noa acuerdan registrar lo que encuentren. Si regresan, decidirán juntos qué merece saber el refugio.",fx:{morale:2},flags:{partyOwnsTruth:true}}
  ]},
  {day:1,time:"08:50",loc:"Estación Los Héroes",type:"Exploración",title:"La puerta sellada",text:"La ruta directa termina ante una compuerta de mantenimiento. Al otro lado, un lector de la Red UNO conserva energía y algo raspa el metal siguiendo el ritmo de sus respiraciones. Abrir rápido evitará un rodeo; hacerlo con ruido anunciará exactamente dónde están.",choices:[
    {label:"Forzar el mecanismo",hint:"El ruido provoca un encuentro aleatorio con uno o dos merodeadores.",cost:"Combate",reqItems:["tool"],combat:{title:"Ruido en la compuerta",brief:"Las hojas de metal se separan y dos ópticas rojas despiertan en la oscuridad.",encounters:[["merodeador"],["merodeador2"],["merodeador","merodeador4"]],xp:26,canFlee:true},victory:{title:"Metal contra metal",result:"La compuerta cede después del combate. En el suelo queda un plano de servicio marcado con rutas que los cazadores ya no usan.",fx:{threat:5},add:["routeMap"],flags:{returnRoute:true}},defeat:{title:"Retirada por los ductos",result:"El grupo abandona la compuerta antes de quedar rodeado. El conducto superior permite avanzar, pero elimina la ruta rápida de regreso.",fx:{threat:7,morale:-4},flags:{usedVents:true}}},
    {label:"Alimentar el lector",hint:"La credencial atrapada en el marco puede abrir otros sistemas de la Red UNO.",cost:"Batería −1",req:{battery:1},title:"Acceso restaurado",result:"La pantalla reconoce un protocolo antiguo y abre la compuerta durante ocho segundos. Una credencial de técnica cae desde el marco antes de que el sistema vuelva a morir.",fx:{battery:-1,threat:-2},add:["unoCard"]},
    {label:"Buscar los ductos superiores",hint:"Evita el contacto, pero obliga a cargar el equipo por un paso estrecho.",cost:"Moral −3",title:"Por encima de las vías",result:"El grupo avanza de rodillas entre polvo y cables. Nadie los detecta, aunque el esfuerzo y la oscuridad convierten cada roce en una discusión.",fx:{morale:-3,threat:-1},flags:{usedVents:true}}
  ]},
  {day:1,time:"10:15",loc:"Último andén habitado",type:"Intercambio",title:"El peso de una ración",text:"Una familia de cazadores prepara una salida hacia la superficie. Ofrecen munición y componentes, pero necesitan agua para una niña con fiebre. El grupo puede aliviar la carga ahora o conservar reservas para una jornada que recién comienza.",choices:[
    {label:"Entregar agua a la familia",hint:"El gesto abre una futura ruta de cazadores y mejora la moral.",cost:"Agua −1",req:{water:1},title:"La deuda del andén",result:"La niña bebe despacio. Su madre entrega munición recuperada y dibuja un símbolo que identifica casas seguras en la superficie.",fx:{water:-1,morale:5,ammo:1},archive:["hunterMarks"],flags:{huntersTrust:true}},
    {label:"Cambiar una ración por componentes",hint:"Obtiene material para el taller de Elías sin reducir el agua común.",cost:"Alimento −1",req:{food:1},title:"Chatarra útil",result:"El trueque deja dos placas, cable de cobre y una bisagra de la Red UNO en la mochila. Elías ya imagina un casco; Sara solo ve una comida menos.",fx:{food:-1},flags:{tradedForScrap:true}},
    {label:"Guardar todo y seguir",hint:"No altera las reservas, pero el grupo pierde una oportunidad de crear confianza.",cost:"Moral −2",title:"Mochilas cerradas",result:"Nadie intenta detenerlos. Cuando la compuerta queda atrás, Noa señala que la familia recordará tanto la negativa como habría recordado la ayuda.",fx:{morale:-2}}
  ]},
  {day:1,time:"11:40",loc:"Túnel de enlace",type:"Amenaza",title:"Tres luces rojas",text:"Un cable tensado a la altura del tobillo detiene a Noa. Desde las columnas aparecen siluetas con prótesis recuperadas y visores rojos. No parecen una patrulla de la Red UNO: se comunican con golpes breves sobre el hormigón y protegen algo más adelante.",choices:[
    {label:"Romper la emboscada",hint:"Enfrenta una formación aleatoria de dos merodeadores.",cost:"Combate",combat:{title:"Emboscada del enlace",brief:"Los merodeadores cierran ambos extremos del túnel y avanzan sin responder.",encounters:[["merodeador2","merodeador4"],["merodeador","merodeador3"],["merodeador4","merodeador5"]],xp:34,canFlee:true},victory:{title:"El túnel queda en silencio",result:"Los hostiles caen, pero uno intenta arrastrarse hacia su compañero antes de apagarse. El gesto no encaja con las historias de monstruos que cuentan los ancianos.",fx:{threat:6,morale:-1},archive:["redEyes"],flags:{sawBond:true}},defeat:{title:"Expulsados del enlace",result:"El grupo entrega terreno y escapa por una escalera lateral. Los merodeadores no persiguen más allá de las marcas grabadas en el muro.",fx:{threat:8,morale:-5},archive:["redEyes"]}},
    {label:"Dejar el arma y mostrar las manos",hint:"Prueba de grupo. Puede revelar que defienden un territorio y no cazan por impulso.",cost:"Dificultad 14",roll:{dc:14,bonus:1,success:{title:"Una frontera, no una cacería",result:"Las ópticas rojas siguen cada latido, pero nadie dispara. Una figura marca otra ruta y golpea dos veces su pecho, donde brilla un núcleo bajo la ropa.",fx:{threat:-3,morale:3},archive:["redEyes","cores"],flags:{merodeadorParley:true},dialogue:{npc:"lira",kicker:"Conversación de frontera",text:"Lira mantiene las manos cerca del pecho abierto. Golpea el hormigón dos veces, espera que Noa imite el ritmo y recién entonces baja el visor. «No seguimos sangre. Seguimos marcas. Ustedes cruzaron una línea vieja. Si vienen por la señal, miren a la torre, no a nuestras heridas.»",options:[{label:"Preguntar por los núcleos",hint:"Pide contexto sobre el ritual antes de seguir.",fx:{morale:1},archive:["coreRite"],flags:{askedLiraCores:true}},{label:"Ofrecer tela para cerrar la herida",hint:"Gasta material, pero reduce la hostilidad del encuentro.",reqItems:["cloth"],fx:{cloth:-1,morale:3,threat:-2},archive:["redEyes"],flags:{helpedLiraWound:true}},{label:"Guardar distancia y marcharse",hint:"Evita comprometer recursos y respeta su frontera.",fx:{threat:-1},flags:{keptLiraDistance:true}}]}},fail:{title:"El aviso",result:"Un proyectil golpea el suelo frente a Sara. El grupo retrocede y pierde suministros durante la huida, aunque logra evitar una pelea abierta.",fx:{threat:5,morale:-3,food:-1}}}},
    {label:"Retroceder hacia los ductos",hint:"Evita la batalla y sacrifica tiempo y cohesión.",cost:"Moral −4",title:"La ruta más larga",result:"La expedición vuelve sobre sus pasos hasta encontrar un respiradero. Nadie resulta herido, pero el desvío confirma que alguien controla los túneles mejor que los Rotos.",fx:{morale:-4,threat:-2},flags:{avoidedRedEyes:true}}
  ]},
  {day:1,time:"13:10",loc:"Galería inundada",type:"Supervivencia",title:"Agua sobre los rieles",text:"Una rotura antigua cubre la galería hasta la cintura. El agua oculta cables, fierros y una corriente que puede despertar el sistema de alarma. En la pared opuesta, una caja médica permanece seca sobre un soporte.",choices:[
    {label:"Cruzar asegurados con una cuerda",hint:"Prueba física. Un fallo hiere al grupo, pero conserva el equipo.",cost:"Dificultad 11",roll:{dc:11,bonus:2,success:{title:"Paso firme",result:"Noa encuentra los durmientes intactos y guía cada pisada. La caja contiene vendas todavía utilizables y una ampolla sin abrir.",fx:{morale:2,meds:1}},fail:{title:"Metal bajo el agua",result:"Elías resbala sobre una plancha y el golpe abre su protección. Llegan al otro lado con la caja, pero el ruido viaja por toda la galería.",fx:{threat:6,morale:-2,meds:1}}}},
    {label:"Cortar la corriente antes de cruzar",hint:"Consume energía para eliminar el riesgo y mantener baja la amenaza.",cost:"Batería −1",req:{battery:1},title:"Un cauce muerto",result:"La celda alimenta el interruptor el tiempo suficiente para descargar el circuito. El grupo cruza en silencio y recupera la caja médica.",fx:{battery:-1,threat:-3,meds:1}},
    {label:"Rodear por el túnel de ventilación",hint:"No arriesga recursos, pero deja la caja y agota la paciencia del grupo.",cost:"Moral −3",title:"La medicina queda atrás",result:"El desvío evita el agua. Desde la rejilla todavía se ve la caja intacta, imposible de alcanzar sin regresar varias horas.",fx:{morale:-3,threat:-1}}
  ]},
  {day:1,time:"14:35",loc:"Casa de máquinas",type:"Investigación",title:"El campamento apagado",text:"Tres lechos aún conservan calor y una olla cuelga sobre brasas recientes. No hay cuerpos, solo símbolos de cazadores tachados y un mensaje analógico: «ellos recuperan sus núcleos». Algo arrastró equipo pesado hacia la casa de bombas.",choices:[
    {label:"Seguir el rastro de arrastre",hint:"Puede terminar en un combate contra dos o tres merodeadores.",cost:"Combate",combat:{title:"La casa de los núcleos",brief:"Una herramienta de luz azul corta la oscuridad. Los merodeadores protegen el cuerpo de uno de los suyos.",encounters:[["merodeador4","merodeador5"],["merodeador2","merodeador3","merodeador4"],["merodeador","merodeador3","merodeador5"]],xp:42,canFlee:true},victory:{title:"Una victoria incómoda",result:"Bajo las placas encuentran un núcleo implantado y señales de un ritual interrumpido. El grupo comprende que los hostiles regresaron por su muerto, no por el campamento.",fx:{threat:8,morale:-3},archive:["coreRite"],flags:{interruptedRite:true}},defeat:{title:"El cuerpo recuperado",result:"El grupo se repliega mientras los merodeadores cargan a su compañero. Ninguno intenta rematarlos después de abandonar la sala.",fx:{threat:5,morale:-4},archive:["coreRite"]}},
    {label:"Registrar el campamento",hint:"Recupera suministros y pruebas sin perseguir a los desaparecidos.",cost:"Amenaza +2",title:"Lo que dejaron los cazadores",result:"Encuentran una ración, cartuchos envueltos en tela y un cuaderno con rutas a la superficie. Cada objeto útil recuerda a alguien que quizá aún lo necesita.",fx:{food:1,ammo:1,threat:2},archive:["hunterMarks"],flags:{lootedCamp:true}},
    {label:"Apagar las brasas y retirarse",hint:"Evita dejar una firma térmica y respeta el lugar.",cost:"Sin recursos",title:"Un campamento sin testigos",result:"Sara cubre la olla y Noa borra sus huellas. No descubren qué ocurrió, pero tampoco convierten la desaparición ajena en oportunidad.",fx:{morale:2,threat:-2}}
  ]},
  {day:1,time:"16:05",loc:"Casa de bombas",type:"Combate",title:"El guardián reconstruido",text:"La bomba que mantiene seco el acceso a la superficie todavía funciona. Frente al tablero espera un merodeador enorme unido a placas industriales; dos exploradores se mueven detrás de él. Si la máquina se detiene, el regreso quedará bajo agua.",choices:[
    {label:"Recuperar la casa de bombas",hint:"Combate exigente contra una formación aleatoria de hasta tres merodeadores.",cost:"Combate difícil",combat:{title:"Guardianes de la bomba",brief:"El reconstruido absorbe el primer avance mientras sus compañeros buscan los flancos.",encounters:[["merodeador3","merodeador2"],["merodeador3","merodeador4","merodeador"],["merodeador5","merodeador2","merodeador4"]],xp:48,canFlee:true},victory:{title:"La bomba sigue viva",result:"Elías estabiliza el motor con piezas del suelo. La ruta de regreso permanecerá seca, pero el combate deja una señal que otros podrán seguir.",fx:{threat:9,morale:3},flags:{pumpSecured:true}},defeat:{title:"La galería comienza a llenarse",result:"El grupo huye cuando el reconstruido rompe una tubería principal. La ruta de regreso se estrecha y el refugio pierde una salida valiosa.",fx:{threat:7,morale:-8},flags:{pumpLost:true}}},
    {label:"Reactivar el señuelo térmico",hint:"Elías puede atraerlos a un corredor y cerrar la compuerta.",cost:"Batería −1",req:{battery:1},roll:{dc:12,bonus:3,success:{title:"Calor sin pulso",result:"Los sensores improvisados siguen el señuelo. El grupo sella a los merodeadores tras una puerta de presión y conserva la bomba sin disparar.",fx:{battery:-1,threat:-4,morale:3},flags:{pumpSecured:true}},fail:{title:"El señuelo se rompe",result:"La luz térmica estalla antes de cruzar el corredor. El grupo escapa, pero la bomba queda bajo control de los merodeadores.",fx:{battery:-1,threat:6,morale:-5},flags:{pumpLost:true}}}},
    {label:"Marcar la posición y continuar",hint:"Evita una batalla difícil, a costa de abandonar una infraestructura crítica.",cost:"Moral −5",title:"Una pérdida calculada",result:"Noa marca la pared para una futura patrulla. Detrás, el ritmo de la bomba cambia y todos entienden que quizá no haya una segunda oportunidad.",fx:{morale:-5,threat:-2},flags:{pumpAbandoned:true}}
  ]},
  {day:1,time:"18:20",loc:"Farmacia del enlace",type:"Dilema",title:"El hombre bajo el mostrador",text:"Matías lleva dos días escondido, con una herida profunda y fiebre. Afirma conocer los cambios de ruta de la Red UNO y reconoce el código de la señal, pero apenas puede caminar; llevarlo convierte la misión en un rescate.",choices:[
    {label:"Estabilizarlo y cargar con él",hint:"La medicina transforma información en una promesa que puede regresar después.",cost:"Medicina −1",req:{meds:1},title:"Una vida por una respuesta",result:"La fiebre baja lo suficiente para moverlo. Matías entrega una frecuencia y promete guiar al grupo por la superficie cuando pueda sostenerse solo.",fx:{meds:-1,morale:6,threat:3},archive:["matias"],flags:{savedMatias:true,debtMatias:true},dialogue:{npc:"matias",kicker:"Superviviente rescatado",text:"Matías se aferra al vendaje como si fuera una cuerda. Habla bajo, mirando la puerta: «La Red UNO cambia los barridos cuando detecta fiebre, no armas. Usen mi ritmo como señuelo y no crucen por República si el cielo está quieto.»",options:[{label:"Preguntar por la operadora",hint:"Busca una pista directa hacia el origen de la señal.",fx:{threat:-1},archive:["origin"],flags:{knowsOperatorWord:true}},{label:"Pedir una ruta segura",hint:"Acepta su ayuda táctica para la superficie.",fx:{morale:1},add:["routeMap"],flags:{matiasRoute:true}},{label:"Ordenarle silencio para no perder tiempo",hint:"Reduce el riesgo inmediato, pero daña la cohesión.",fx:{morale:-2,threat:-1},flags:{silencedMatias:true}}]}},
    {label:"Escucharlo y dejar provisiones",hint:"Obtiene su ruta, pero nadie sabrá si sobrevivirá hasta el regreso.",cost:"Alimento −1",req:{food:1},title:"Información sin rescate",result:"Matías dibuja una ruta entre temblores. Sara deja una ración a su alcance y cierra la puerta para ocultar la luz.",fx:{food:-1,morale:1},archive:["matias"],add:["routeMap"],flags:{leftSupplies:true},dialogue:{npc:"matias",kicker:"Últimas indicaciones",text:"Matías empuja el mapa hacia Sara con dedos manchados de polvo. «Si me dejan aquí, al menos no caminen por la avenida cuando los semáforos despierten. Hay sensores viejos usando luces nuevas.»",options:[{label:"Prometer volver por él",hint:"No cambia el rescate ahora, pero sostiene la moral del grupo.",fx:{morale:2},flags:{promisedMatiasReturn:true}},{label:"Preguntar por la señal",hint:"Obtiene una pista sobre la voz antes de cerrar la puerta.",archive:["origin"],flags:{knowsOperatorWord:true}},{label:"Cerrar sin responder",hint:"Ahorra tiempo y evita falsas promesas.",fx:{morale:-1,threat:-1},flags:{leftMatiasWithoutPromise:true}}]}},
    {label:"Tomar la frecuencia y marcharse",hint:"Conserva recursos, pero convierte a un superviviente en un costo descartado.",cost:"Moral −8",title:"La voz queda atrás",result:"Matías comprende la decisión antes de que nadie la explique. Sus indicaciones son correctas; el silencio del grupo también dice algo verdadero.",fx:{morale:-8},archive:["matias"],flags:{abandonedMatias:true}}
  ]},

  {day:2,time:"06:50",loc:"Túnel de servicio",type:"Encuentro",title:"El pulso del dron",text:"Una unidad de la Red UNO desciende y bloquea la subida. No busca movimiento: mide temperatura, respiración y ritmo cardíaco, comparando cada cuerpo con una lista de firmas autorizadas. La transmisión comenzará en segundos.",choices:[
    {label:"Interceptar antes de la transmisión",hint:"Enfrenta uno o dos drones antes de que marquen el sector.",cost:"Combate",combat:{title:"Intercepción de la Red UNO",brief:"Las placas de defensa se abren y una segunda señal mecánica responde desde el pozo.",encounters:[["drone"],["drone","drone"]],xp:34,canFlee:true},victory:{title:"Núcleos recuperados",result:"Las unidades caen antes de completar el envío. Elías extrae una memoria todavía intacta y borra la firma térmica del grupo.",fx:{threat:6},add:["droneCore"]},defeat:{title:"Sector marcado",result:"El grupo rompe contacto, pero una unidad transmite una firma parcial hacia la superficie.",fx:{threat:13,morale:-4},flags:{droneAlert:true}}},
    {label:"Cortar la energía del túnel",hint:"Una maniobra técnica puede conservar el núcleo sin iniciar una batalla.",cost:"Batería −1",req:{battery:1},roll:{dc:11,bonus:3,success:{title:"Oscuridad calculada",result:"La subestación se apaga antes de la lectura final. El dron cae sin energía y su núcleo permanece utilizable.",fx:{battery:-1,threat:-4},add:["droneCore"]},fail:{title:"Arco eléctrico",result:"El corte llega tarde. La unidad transmite una fracción de la señal antes de caer sobre los rieles.",fx:{battery:-1,threat:8,morale:-2},add:["droneCore"]}}},
    {label:"Controlar el pulso",hint:"El grupo intenta volverse invisible para sensores que escuchan el cuerpo.",cost:"Dificultad 13",roll:{dc:13,bonus:1,success:{title:"Latidos invisibles",result:"Durante nueve segundos nadie respira. La unidad clasifica el túnel como vacío y asciende sin registrar una firma.",fx:{threat:-5,morale:3},flags:{sparedDrone:true},dialogue:{npc:"unit7",kicker:"Eco mecánico",text:"Antes de subir, la unidad S-7 titubea. Una ranura del chasis queda abierta y la voz sale partida por estática: «Firma no autorizada. Error: pulso humano protegido por protocolo antiguo. Solicitud: orden final.»",options:[{label:"Responder con la frecuencia de la señal",hint:"Usa la anomalía para confundir el registro de la Red UNO.",fx:{threat:-2},archive:["sonar"],flags:{unit7Echo:true}},{label:"Extraer su última ruta",hint:"Obtiene un mapa, pero fuerza la memoria del dron.",fx:{threat:1},add:["routeMap"],flags:{unit7Route:true}},{label:"Apagarlo antes de que despierte",hint:"Evita que vuelva a transmitir a costa de la moral.",fx:{morale:-2,threat:-3},flags:{unit7Silenced:true}}]}},fail:{title:"Un latido fuera de lugar",result:"La respiración de Sara se acelera. El dron marca la galería antes de desaparecer hacia la superficie.",fx:{threat:10,morale:-4},flags:{droneAlert:true}}}}
  ]},
  {day:2,time:"08:05",loc:"Escalera República",type:"Exploración",title:"La primera luz",text:"La escalera termina bajo una reja cubierta de raíces. Arriba, el cielo gris revela edificios tomados por vegetación y calles demasiado silenciosas. En una columna hay marcas recientes de cazadores que contradicen el mapa del refugio.",choices:[
    {label:"Seguir las marcas de cazadores",hint:"Una casa abandonada puede servir como punto seguro y depósito temporal.",cost:"Amenaza −2",title:"La ruta de las ventanas negras",result:"Noa identifica tres símbolos: agua, descanso y peligro mecánico. El grupo emerge dentro de una casa sin techo, fuera del barrido principal de la Red UNO.",fx:{threat:-2,morale:2},archive:["hunterMarks"],flags:{safeHouseRoute:true}},
    {label:"Abrir la reja por la avenida",hint:"La salida es rápida, pero expone al grupo a los sensores de altura.",cost:"Amenaza +5",title:"Bajo el cielo abierto",result:"El metal cede y la luz cae sobre todos a la vez. No hay disparos, pero un punto azul cambia de rumbo entre las nubes.",fx:{threat:5},flags:{surfaceExposed:true}},
    {label:"Esperar un ciclo completo de vigilancia",hint:"Reduce el riesgo a costa de tensión y tiempo de misión.",cost:"Moral −3",title:"Cuarenta y siete minutos",result:"La señal se repite mientras esperan. Cuando el barrido se aleja, incluso Elías duda de que la voz siga viva al final del día.",fx:{morale:-3,threat:-3},flags:{timedPatrol:true}}
  ]},
  {day:2,time:"09:15",loc:"Alameda hundida",type:"Combate",title:"Sombras sobre el asfalto",text:"Dos drones recorren la avenida siguiendo columnas de aire caliente. Uno ilumina fachadas; el otro permanece alto, listo para transmitir. Cruzar obliga a combatir, engañar sus sensores o abandonar una ruta directa hacia la señal.",choices:[
    {label:"Derribar el barrido",hint:"Combate aleatorio contra uno, dos o tres drones.",cost:"Combate",combat:{title:"Cielo de vigilancia",brief:"Las unidades se separan y atacan desde alturas distintas sobre la avenida hundida.",encounters:[["drone","drone"],["drone","drone","drone"],["drone"]],xp:42,canFlee:true},victory:{title:"Una calle sin ojos",result:"El último dron cae dentro de un bus oxidado. Durante unos minutos, la avenida vuelve a pertenecer a quienes caminan sobre ella.",fx:{threat:8,morale:3},add:["droneCore"],flags:{alamedaClear:true}},defeat:{title:"Marcados desde el aire",result:"El grupo alcanza un subterráneo mientras las unidades fijan la zona. La ruta permanece abierta, pero la Red UNO conoce su dirección.",fx:{threat:14,morale:-5},flags:{surfaceMarked:true}}},
    {label:"Emitir una firma falsa",hint:"El núcleo recuperado puede enviar a los drones hacia otra calle.",cost:"Pierde núcleo",reqItems:["droneCore"],title:"Un fantasma autorizado",result:"El núcleo repite la firma de una patrulla destruida. Los drones obedecen y escoltan el señuelo hasta perderse entre las torres.",fx:{threat:-6,morale:2},remove:["droneCore"],flags:{alamedaClear:true}},
    {label:"Cruzar por los subterráneos",hint:"Evita la batalla, pero las galerías están inestables y agotan al grupo.",cost:"Moral −4",title:"Debajo del asfalto",result:"Cada derrumbe obliga a desmontar equipo y arrastrarlo. Salen dos cuadras más adelante sin ser vistos, pero con menos confianza en la ruta.",fx:{morale:-4,threat:-2},flags:{undergroundDetour:true}}
  ]},
  {day:2,time:"10:50",loc:"Casa de cazadores",type:"Refugio",title:"La mesa para cuatro",text:"La casa marcada conserva mantas secas, una cocina de alcohol y cuatro platos preparados. Sus dueños no están; un rastro de sangre sale por la puerta trasera. Comer ahora devuelve fuerzas, pero convierte la necesidad ajena en suministro.",choices:[
    {label:"Comer y dejar una ración propia",hint:"Descansa sin vaciar la reserva de quienes podrían regresar.",cost:"Alimento −1",req:{food:1},title:"Un intercambio sin testigos",result:"El grupo calienta la comida y deja una ración sellada en la misma posición. El descanso ayuda, aunque nadie puede asegurar que el intercambio sea justo.",fx:{food:-1,morale:2,threat:-3},flags:{restedAtHouse:true}},
    {label:"Seguir el rastro de sangre",hint:"Puede encontrar a los cazadores o una emboscada de merodeadores.",cost:"Combate posible",combat:{title:"Tras el patio derrumbado",brief:"El rastro termina donde dos merodeadores registran las mochilas de un cazador herido.",encounters:[["merodeador2","merodeador4"],["merodeador","merodeador5"],["merodeador3","merodeador2"]],xp:38,canFlee:true},victory:{title:"El cuarto plato",result:"El cazador sobrevive y reconoce las marcas entregadas en el andén. A cambio indica una entrada lateral al nodo de la Red UNO.",fx:{morale:6,threat:6},flags:{savedHunter:true,nodeSideDoor:true}},defeat:{title:"La puerta trasera",result:"El grupo regresa a la casa sin el cazador. Los golpes contra la pared se apagan y nadie propone volver a intentarlo.",fx:{morale:-7,threat:5},flags:{lostHunter:true}}},
    {label:"Tomar suministros y marcharse",hint:"Obtiene alimento, pero rompe el código no escrito de los cazadores.",cost:"Moral −5",title:"Una casa más vacía",result:"Las raciones caben con facilidad en las mochilas. Noa borra la marca de refugio seguro: después de lo ocurrido, ya no lo es para nadie.",fx:{food:2,morale:-5},flags:{strippedSafeHouse:true}}
  ]},
  {day:2,time:"12:20",loc:"Nodo 14 de la Red UNO",type:"Investigación",title:"La máquina que recuerda",text:"El terminal conserva un mapa parcial de refugios, firmas cardíacas y el origen de la señal. Su memoria está dañada: abrir una sección puede borrar otra, y una mala consulta enviará la ubicación del nodo a la red.",choices:[
    {label:"Acceder con la credencial",hint:"La identidad de una técnica desaparecida abre ambos archivos sin forzar el sistema.",cost:"Requiere credencial",reqItems:["unoCard"],title:"Una identidad todavía válida",result:"El sistema saluda a una mujer muerta hace décadas y entrega las rutas bajo su nivel de acceso. Entre ellas aparece un enlace humano hacia la torre repetidora.",fx:{threat:2},archive:["protocol","names"],flags:{fullAccess:true}},
    {label:"Injertar el núcleo del dron",hint:"Elías intenta que el terminal reconozca al grupo como una unidad de la Red UNO.",cost:"Dificultad 12",reqItems:["droneCore"],roll:{dc:12,bonus:3,success:{title:"Memoria injertada",result:"El núcleo acepta el nodo como unidad madre. Los archivos salen completos y revelan cómo la Red UNO clasifica a los refugios no registrados.",fx:{threat:3},archive:["protocol","names","sonar"],remove:["droneCore"]},fail:{title:"Copia incompleta",result:"La memoria se quema al llegar al último bloque. Solo queda el protocolo y una alerta que asciende hacia la superficie.",fx:{threat:9},archive:["protocol"],remove:["droneCore"]}}},
    {label:"Copiar solo el origen de la señal",hint:"Evita profundizar en la lista de refugios, pero renuncia a nombres que podrían ser salvados.",cost:"Información parcial",title:"Una voz dentro de la red",result:"La transmisión fue insertada por una operadora humana conectada a soporte vital. Sigue viva cerca de la torre, usando los intervalos entre barridos.",fx:{morale:2,threat:-1},archive:["origin"],flags:{knowOrigin:true}}
  ]},
  {day:2,time:"14:05",loc:"Cruce Dieciocho",type:"Patrulla",title:"Tres firmas autorizadas",text:"Un rastreador de la Red UNO compara el pulso del grupo con firmas archivadas mientras un tirador cubre la calle. Un dron flota entre ambos y bloquea el regreso. La patrulla todavía no sabe que son Rotos; solo sabe que no deberían estar allí.",choices:[
    {label:"Atacar antes de la identificación",hint:"Combate contra una formación aleatoria de agentes y drones.",cost:"Combate difícil",combat:{title:"Control de identidad",brief:"El rastreador abre el canal SONAR mientras la escolta busca una línea de tiro.",encounters:[["agent2","drone"],["agent3","agent2"],["agent3","drone","agent2"]],xp:50,canFlee:true},victory:{title:"Firmas eliminadas",result:"Elías borra el registro local antes de que cierre la conexión. El equipo del rastreador conserva un mapa de pulsos que conduce a la torre.",fx:{threat:9,morale:3},archive:["sonar"],flags:{patrolBroken:true}},defeat:{title:"Identificación parcial",result:"La patrulla obtiene una lectura incompleta antes de que el grupo escape. Desde ahora, los drones buscarán tres ritmos cardíacos concretos.",fx:{threat:15,morale:-5},flags:{signaturesKnown:true}}},
    {label:"Presentar la credencial de la Red UNO",hint:"Puede sostener la mentira durante el control de identidad.",cost:"Dificultad 14",reqItems:["unoCard"],roll:{dc:14,bonus:2,success:{title:"Técnicos de continuidad",result:"La patrulla acepta la orden antigua y despeja el cruce. Antes de irse, el rastreador menciona refuerzos de cascos morados cerca de la torre.",fx:{threat:-5,morale:2},archive:["purpleHelmets"],flags:{trackerCredential:true}},fail:{title:"Credencial revocada",result:"El lector detecta la fecha imposible. El grupo rompe contacto entre disparos y pierde la credencial durante la huida.",fx:{threat:12,morale:-4},remove:["unoCard"],flags:{signaturesKnown:true}}}},
    {label:"Esperar dentro de un edificio",hint:"Evita el combate, pero sacrifica tiempo y permite que la Red UNO cierre otras rutas.",cost:"Moral −3",title:"Una ciudad que escucha",result:"Permanecen inmóviles mientras el rastreador consulta cada piso. La patrulla se retira, pero deja un sensor en la intersección.",fx:{morale:-3,threat:2},flags:{patrolSensor:true}}
  ]},
  {day:2,time:"15:35",loc:"Clínica abandonada",type:"Dilema",title:"El núcleo expuesto",text:"Una merodeadora herida yace junto a una camilla, con el pecho abierto y un núcleo azul conectado a su respiración. Su arma está lejos. En la pared dibujó el mismo símbolo que aparece en el archivo de los exiliados.",choices:[
    {label:"Cerrar la herida",hint:"Sara utiliza medicina en alguien que el refugio considera enemigo.",cost:"Medicina −1",req:{meds:1},title:"La enemiga respira",result:"La merodeadora despierta sin atacar. Proyecta una imagen de El Valle y señala la torre: la Red UNO utiliza allí los núcleos de sus exiliados como balizas.",fx:{meds:-1,morale:5,threat:2},archive:["coreRite","exiles"],flags:{savedMerodeadora:true},dialogue:{npc:"lira",kicker:"Corazón abierto",text:"Lira despierta con el núcleo azul todavía vibrando entre costillas y cable. «Me llamaban Eliana antes del destierro. Lira fue el nombre que sobrevivió arriba. Si toman mi núcleo, abren una puerta. Si lo dejan conmigo, quizá abran otra clase de puerta.»",options:[{label:"Decirle que no son cazadores",hint:"Afianza una futura confianza con los exiliados.",fx:{morale:2,threat:-2},archive:["exiles"],flags:{liraTrust:true}},{label:"Pedir una ruta hacia la torre",hint:"Consigue dirección concreta, aunque revela intención.",fx:{threat:1},add:["routeMap"],flags:{liraTowerRoute:true}},{label:"Exigir el núcleo de todas formas",hint:"Obtiene tecnología sacrificando la alianza posible.",fx:{morale:-8,threat:4},add:["droneCore"],flags:{betrayedLira:true}}]}},
    {label:"Extraer el núcleo",hint:"Elías puede convertirlo en una llave, pero la extracción será irreversible.",cost:"Moral −6",title:"Una llave todavía caliente",result:"La respiración se detiene cuando el núcleo abandona el soporte. El dispositivo contiene una firma aceptada por los sensores de la torre.",fx:{morale:-6,threat:1},add:["droneCore"],archive:["cores"],flags:{tookLivingCore:true}},
    {label:"Dejar agua y retirarse",hint:"No decide su destino, pero conserva medicina y evita el saqueo.",cost:"Agua −1",req:{water:1},title:"Una posibilidad",result:"Sara deja el recipiente dentro de su alcance. Al cerrar la puerta, la óptica roja vuelve a encenderse y sigue al grupo sin hostilidad.",fx:{water:-1,morale:2,threat:-1},flags:{sparedMerodeadora:true}}
  ]},
  {day:2,time:"17:05",loc:"Semáforo operativo",type:"Combate",title:"Cazadores de pulsos",text:"Un único semáforo continúa cambiando sobre una avenida destruida. Su controlador emite un pulso y tres merodeadores responden desde balcones distintos: aprendieron a usar la infraestructura de la Red UNO para detectar viajeros.",choices:[
    {label:"Tomar la intersección",hint:"Combate aleatorio contra tres merodeadores con funciones diferentes.",cost:"Combate difícil",combat:{title:"La intersección roja",brief:"Un reconstruido bloquea la calle mientras dos rastreadores disparan desde los costados.",encounters:[["merodeador3","merodeador2","merodeador4"],["merodeador5","merodeador","merodeador2"],["merodeador4","merodeador5","merodeador3"]],xp:54,canFlee:true},victory:{title:"El pulso se detiene",result:"Elías desconecta el controlador y descubre rutas de otros grupos marcadas en su memoria. El mapa conduce al mercado y también revela cuántas personas fueron cazadas aquí.",fx:{threat:10,morale:-1},add:["routeMap"],flags:{intersectionWon:true}},defeat:{title:"La luz permanece roja",result:"El grupo se esconde en un colector hasta que los merodeadores abandonan la caza. Parte del equipo queda arriba, junto al semáforo.",fx:{threat:10,morale:-7,ammo:-1},flags:{intersectionLost:true}}},
    {label:"Sobrecargar el controlador",hint:"Una celda puede quemar el sensor y abrir una ventana de escape.",cost:"Batería −1",req:{battery:1},roll:{dc:13,bonus:3,success:{title:"Verde durante nueve segundos",result:"El pulso revienta la caja de control. Los merodeadores pierden la firma del grupo y disparan contra una calle vacía.",fx:{battery:-1,threat:-5,morale:2},flags:{intersectionEscaped:true}},fail:{title:"El sensor replica la firma",result:"La descarga multiplica el pulso antes de quemarlo. El grupo escapa, pero su dirección queda expuesta.",fx:{battery:-1,threat:10,morale:-3},flags:{signaturesKnown:true}}}},
    {label:"Desviar por los patios interiores",hint:"Evita el combate a costa de abandonar la ruta directa.",cost:"Moral −4",title:"Muros entre la señal",result:"Cruzan casas sin techo y patios convertidos en bosque. La torre desaparece detrás de cada muro, y la expedición pierde horas valiosas.",fx:{morale:-4,threat:-2},flags:{longSurfaceRoute:true}}
  ]},
  {day:2,time:"19:00",loc:"Mercado subterráneo",type:"Negociación",title:"El precio de la ruta",text:"Los Cosechadores controlan la única bajada segura antes de la noche. Su jefa conoce los movimientos de la Red UNO y ofrece un módulo de radio, pero exige coordenadas de comunidades que todavía no aparecen en la red.",choices:[
    {label:"Entregar coordenadas falsas",hint:"Una mentira convincente protege los refugios y conserva el trato.",cost:"Dificultad 13",roll:{dc:13,bonus:2,success:{title:"Una mentira útil",result:"La jefa acepta el mapa alterado. El grupo obtiene el módulo y desvía a los Cosechadores hacia túneles abandonados.",fx:{morale:3,threat:-2},add:["radio"],flags:{fooledHunters:true}},fail:{title:"La tinta no coincide",result:"La jefa reconoce una marca fuera de escala y coloca precio a los nombres del grupo. Conservan la información, pero pierden la ruta segura.",fx:{morale:-3,threat:10},flags:{huntersHostile:true}}}},
    {label:"Invocar la deuda de los cazadores",hint:"Solo funciona si el grupo ayudó a su gente o rescató a uno de los suyos.",cost:"Requiere confianza",reqFlags:["huntersTrust","savedHunter"],title:"Una deuda atraviesa la superficie",result:"Un cazador confirma el gesto del andén y la casa recuperada. La jefa entrega el módulo sin pedir coordenadas y ofrece un rincón para pasar la noche.",fx:{threat:-4,morale:4},add:["radio"],flags:{huntersAlliance:true}},
    {label:"Entregar una coordenada real",hint:"Compra seguridad inmediata exponiendo una comunidad que no puede defenderse.",cost:"Moral −10",title:"El trato permanece",result:"El módulo funciona y la bajada se abre. En algún punto de los túneles, una comunidad acaba de convertirse en mercancía.",fx:{morale:-10,threat:-2},add:["radio"],flags:{soldRefuge:true}}
  ]},

  {day:3,time:"06:35",loc:"Alameda superior",type:"Supervivencia",title:"Cruzando a cielo abierto",text:"La torre está al otro lado de una avenida expuesta. Una patrulla de la Red UNO avanza mientras tres desconocidos piden ayuda desde un edificio hundido. Intervenir cuesta tiempo y munición; ignorarlos deja el camino libre para la patrulla.",choices:[
    {label:"Desviar la patrulla con un núcleo",hint:"La firma mecánica envía a la Red UNO lejos de los desconocidos.",cost:"Pierde núcleo",reqItems:["droneCore"],title:"Una firma conocida",result:"El núcleo transmite un código de retorno. La patrulla abandona la avenida para recuperar su propia memoria y los atrapados alcanzan otra salida.",fx:{threat:-8,morale:3},remove:["droneCore"],flags:{clearAvenue:true,rescuedStrangers:true}},
    {label:"Abrir paso por la fuerza",hint:"Combate aleatorio contra agentes y drones para rescatar a los desconocidos.",cost:"Combate difícil",combat:{title:"Patrulla de superficie",brief:"Las unidades de la Red UNO cubren la avenida mientras un dron fija todas las rutas de escape.",encounters:[["agent","drone"],["agent2","agent3","drone"],["agent4","drone"]],xp:52,canFlee:true},victory:{title:"La avenida queda abierta",result:"La patrulla cae y los desconocidos alcanzan un subterráneo. Una de ellos entrega el código del ascensor de la torre.",fx:{morale:6,threat:9},flags:{rescuedStrangers:true,towerCode:true,clearAvenue:true}},defeat:{title:"Bajo el fuego de la Red UNO",result:"El grupo se repliega por una galería hundida. Las voces del edificio dejan de escucharse antes de que cierre la compuerta.",fx:{morale:-7,threat:11},flags:{lostStrangers:true}}},
    {label:"Usar el mapa y evitar contacto",hint:"Una galería técnica oculta al grupo, pero deja a los desconocidos atrás.",cost:"Requiere mapa",reqItems:["routeMap"],title:"Bajo las veredas rotas",result:"El mapa conduce por una línea de mantenimiento. La patrulla nunca ve al grupo; las voces quedan en la superficie.",fx:{threat:-5,morale:-3},flags:{silentSurface:true}}
  ]},
  {day:3,time:"08:00",loc:"Perímetro de Gobierno",type:"Combate",title:"Los cascos morados",text:"Cuatro figuras protegen el acceso a un distrito brutalista aún iluminado. Sus cascos morados no pertenecen a las patrullas comunes: son guardianes del perímetro de El Valle y no aceptan identidades antiguas.",choices:[
    {label:"Romper el cordón exterior",hint:"Combate contra dos o tres agentes de la Red UNO, incluyendo unidades pesadas.",cost:"Combate muy difícil",combat:{title:"Cordón morado",brief:"El comandante ocupa el centro mientras los tiradores cierran los corredores laterales.",encounters:[["agent4","agent2"],["agent4","agent3","agent2"],["agent3","agent2","agent"]],xp:58,canFlee:true},victory:{title:"El perímetro se abre",result:"El comandante cae sin emitir una orden de retirada. En su visor aparece El Valle al otro lado de la ciudad y una lista de exiliados convertidos en objetivos.",fx:{threat:11,morale:4},archive:["purpleHelmets","exiles"],flags:{purpleLineBroken:true}},defeat:{title:"Fuera del perímetro",result:"El grupo sobrevive porque los cascos morados no abandonan su línea. Deben rodear por una zona donde los drones conservan el cielo.",fx:{threat:9,morale:-7},flags:{purpleDetour:true}}},
    {label:"Mostrar la ruta de los exiliados",hint:"El archivo puede crear una contradicción suficiente para cruzar sin combate.",cost:"Requiere archivo",reqFlags:["knowsExiles","savedMerodeadora"],title:"Nombres que siguen activos",result:"El rastreador encuentra una identidad que el sistema nunca revocó. La puerta se abre y nadie admite que el protocolo ha aceptado a una exiliada.",fx:{threat:-5,morale:3},flags:{purpleLineBypassed:true}},
    {label:"Rodear por la zona de derrumbes",hint:"Evita el cordón, pero expone al grupo a vigilancia aérea.",cost:"Amenaza +5",title:"Fuera de la muralla",result:"El desvío conduce por edificios abiertos al cielo. Ningún agente los ve, pero varias ópticas mecánicas cambian de dirección.",fx:{threat:5,morale:-2},flags:{purpleDetour:true}}
  ]},
  {day:3,time:"09:35",loc:"Azoteas de la Alameda",type:"Asalto",title:"El nido de vigilancia",text:"La señal atraviesa una azotea donde la Red UNO recarga sus drones. Las unidades están conectadas al relé y comparten visión: atacar una despierta a todas; sabotear el nido puede dejar ciega media comuna.",choices:[
    {label:"Destruir el nido",hint:"Combate contra una formación de dos o tres drones con apoyo escalonado.",cost:"Combate difícil",combat:{title:"Enjambre de la Alameda",brief:"Los drones se desconectan del relé y forman un triángulo de fuego sobre el techo.",encounters:[["drone","drone"],["drone","drone","drone"]],xp:56,canFlee:true},victory:{title:"Media ciudad sin ojos",result:"El relé colapsa y las rutas aéreas desaparecen del mapa de la Red UNO. El núcleo central conserva la secuencia que abre la torre.",fx:{threat:10,morale:3},add:["droneCore"],archive:["sonar"],flags:{droneNestDown:true}},defeat:{title:"Bajo el enjambre",result:"El grupo desciende por una caja de ascensor mientras los drones marcan el edificio. La torre queda más cerca y también más alerta.",fx:{threat:15,morale:-6},flags:{towerAlert:true}}},
    {label:"Infectar el relé con una memoria",hint:"Un núcleo puede propagar rutas falsas a todas las unidades conectadas.",cost:"Pierde núcleo",reqItems:["droneCore"],roll:{dc:13,bonus:3,success:{title:"Un mapa imposible",result:"Durante un minuto, la Red UNO ve cientos de firmas corriendo hacia el sur. Los drones abandonan el nido para seguir cuerpos que no existen.",fx:{threat:-10,morale:3},remove:["droneCore"],flags:{droneNestBypassed:true}},fail:{title:"La red rechaza el injerto",result:"El núcleo se quema y los drones reciben una imagen parcial del grupo. Escapan antes del cierre completo.",fx:{threat:12,morale:-3},remove:["droneCore"],flags:{towerAlert:true}}}},
    {label:"Descender y buscar otra calle",hint:"Evita el nido, pero entrega la ventaja de altura y añade otro desvío.",cost:"Moral −4",title:"La torre desaparece otra vez",result:"Bajan por un edificio sin escaleras y vuelven al nivel de la calle. El cielo permanece vigilado y la señal se escucha más débil.",fx:{morale:-4,threat:-1},flags:{lostAltitude:true}}
  ]},
  {day:3,time:"11:10",loc:"Vestíbulo del ministerio",type:"Investigación",title:"Los muertos sin núcleo",text:"El vestíbulo contiene cuerpos de agentes, cazadores y merodeadores. A estos últimos les abrieron el pecho con una herramienta limpia; alguien recuperó sus núcleos antes de abandonar el lugar. Las posiciones sugieren una alianza temporal contra la Red UNO.",choices:[
    {label:"Reconstruir el combate",hint:"Noa puede identificar quién protegía a quién y obtener una ruta segura.",cost:"Dificultad 12",roll:{dc:12,bonus:3,success:{title:"Una tregua borrada",result:"Los impactos muestran que los merodeadores cubrieron la retirada de los cazadores. Bajo un cuerpo aparece la ruta que ambos grupos intentaban proteger.",fx:{morale:4,threat:-2},archive:["coreRite","truce"],add:["routeMap"],flags:{knowsTruce:true}},fail:{title:"Demasiadas versiones",result:"Cada huella contradice la anterior. El grupo toma una ruta aparente que termina junto a un sensor de la Red UNO todavía activo.",fx:{threat:6,morale:-2}}}},
    {label:"Registrar equipo de la Red UNO",hint:"Recupera suministros, pero aumenta el tiempo expuesto en una zona de muerte.",cost:"Amenaza +6",title:"Restos de una patrulla",result:"Encuentran munición, placas reparables y una frecuencia de mando. El botín ayuda, aunque el relé registra cada segundo de permanencia.",fx:{ammo:2,meds:1,threat:6},archive:["purpleHelmets"]},
    {label:"Cerrar los ojos de los muertos",hint:"No obtiene recursos; preserva el ritual común a cazadores y exiliados.",cost:"Moral +3",title:"Un gesto anterior a la Red UNO",result:"Sara cubre los rostros y Elías apaga las ópticas restantes. No resuelve la batalla, pero recuerda que todos murieron intentando abandonar el mismo lugar.",fx:{morale:3,threat:-1},flags:{honoredDead:true}}
  ]},
  {day:3,time:"12:45",loc:"Corredor de hormigón",type:"Combate",title:"La puerta de continuidad",text:"El único acceso funcional a la torre está protegido por un rastreador, un agente pesado y apoyo mecánico. El corredor no ofrece flancos: solo una sucesión de pilares, sensores y puertas que se cierran detrás del grupo.",choices:[
    {label:"Avanzar pilar por pilar",hint:"Combate contra una formación de la Red UNO aleatoria de hasta tres hostiles.",cost:"Combate muy difícil",combat:{title:"Corredor de continuidad",brief:"El comandante bloquea la puerta mientras el rastreador sincroniza el fuego del dron.",encounters:[["agent4","agent3","drone"],["agent","agent2","drone"],["agent4","agent2"]],xp:62,canFlee:true},victory:{title:"La puerta reconoce a los vivos",result:"El grupo cruza antes del cierre automático. Detrás queda la fuerza más preparada de la Red UNO y delante una torre que ya sabe que vienen.",fx:{threat:12,morale:5},flags:{towerEntered:true}},defeat:{title:"A través del muro",result:"Elías abre un paso de mantenimiento antes de que el corredor los encierre. Llegan a la torre heridos y sin controlar la puerta.",fx:{threat:14,morale:-8},flags:{towerServiceEntry:true}}},
    {label:"Usar el código del ascensor",hint:"Los desconocidos rescatados entregaron una entrada que evita la línea principal.",cost:"Requiere código",reqFlags:["towerCode"],title:"La deuda de la avenida",result:"El ascensor de carga responde a una clave civil. El grupo asciende detrás de la patrulla y deja intacta una ruta para salir.",fx:{threat:-6,morale:4},flags:{towerEntered:true,safeExit:true}},
    {label:"Detonar una granada en la estructura",hint:"Abre un paso sin combate, pero daña la torre y anuncia la entrada.",cost:"Amenaza +10",title:"Una brecha sin regreso",result:"El muro cede sobre cables y polvo. La transmisión sobrevive, pero el estruendo activa cada alarma del edificio.",fx:{threat:10,morale:-2},flags:{towerBreached:true}}
  ]},
  {day:3,time:"14:20",loc:"Sala de antenas",type:"Asedio",title:"La última patrulla",text:"La antena responde a la señal, pero la transmisión necesita varios minutos para alinearse. Ascensores y escaleras muestran contactos de la Red UNO acercándose desde dos niveles. Esta pelea decidirá si la torre permanece operativa.",choices:[
    {label:"Defender la sala de antenas",hint:"Combate culminante contra tres unidades de la Red UNO de composición aleatoria.",cost:"Combate extremo",combat:{title:"Asedio de la torre",brief:"Las puertas se abren por turnos: tiradores, rastreadores, drones y un comandante convergen sobre la consola.",encounters:[["agent4","agent3","drone"],["agent4","agent2","agent"],["agent3","drone","drone"]],xp:70,canFlee:true},victory:{title:"La antena permanece en pie",result:"La última unidad cae lejos de la consola. La torre tiene energía y una ventana limpia para transmitir, pero no habrá otra defensa.",fx:{threat:14,morale:7},flags:{antennaHeld:true}},defeat:{title:"Frecuencia de emergencia",result:"El grupo abandona la sala principal y conserva un canal débil desde mantenimiento. La verdad podrá salir, aunque fragmentada.",fx:{threat:16,morale:-8},flags:{weakBroadcast:true}}},
    {label:"Cerrar pisos con la credencial",hint:"Un acceso de la Red UNO puede dividir la patrulla y evitar la batalla abierta.",cost:"Requiere credencial",reqItems:["unoCard"],roll:{dc:14,bonus:2,success:{title:"Una torre dividida",result:"Las compuertas aíslan a cada escuadra en un nivel distinto. El grupo gana tiempo sin destruir la antena.",fx:{threat:-5,morale:4},flags:{antennaHeld:true}},fail:{title:"Acceso revocado",result:"La torre reconoce la intrusión y quema la credencial. Logran sellar un piso, pero el resto de la patrulla sigue acercándose.",fx:{threat:10,morale:-3},remove:["unoCard"],flags:{weakBroadcast:true}}}},
    {label:"Sobrecargar la antena y ocultarse",hint:"La emisión será corta e inestable, pero el pulso puede derribar temporalmente los sensores.",cost:"Batería −1",req:{battery:1},title:"Un trueno electrónico",result:"El pulso apaga visores y drones durante segundos. Cuando la Red UNO recupera imagen, el grupo ya opera desde una sala secundaria.",fx:{battery:-1,threat:6,morale:1},flags:{weakBroadcast:true}}
  ]},
  {day:3,time:"16:10",loc:"Soporte vital",type:"Revelación",title:"La mujer de la señal",text:"La operadora sigue viva, suspendida por tecnología de la Red UNO. Ella insertó la señal entre ciclos de vigilancia y conservó un archivo de refugios, exiliados y órdenes de continuidad. Liberarlo puede salvar comunidades o convertirlas en objetivos.",choices:[
    {label:"Reparar el enlace completo",hint:"La tecnología recuperada permite hablar con varios refugios al mismo tiempo.",cost:"Requiere tecnología",reqAny:["radio","droneCore"],title:"La red vuelve a respirar",result:"El enlace reconoce la pieza añadida y la voz deja de ser un bucle. Por primera vez, respuestas humanas llegan desde distintos puntos bajo Santiago.",fx:{threat:8,morale:5},archive:["origin","names"],flags:{fullBroadcast:true},dialogue:{npc:"operator",kicker:"La voz de la señal",text:"Irene abre los ojos por primera vez en años. La Red UNO todavía usa su pulso como contraseña, pero su voz ya no suena automática. «No transmitan solo mi nombre. Transmitan las rutas, los muertos y las órdenes. Que nadie vuelva a creer que el silencio era seguridad.»",options:[{label:"Preguntar a quién avisar primero",hint:"Ordena prioridades y mejora la cohesión.",fx:{morale:2},archive:["names"],flags:{operatorPriorities:true}},{label:"Pedir una ventana limpia",hint:"Usa su acceso para reducir el rastreo de salida.",fx:{threat:-4},flags:{operatorWindow:true}},{label:"Prometer llevar su nombre",hint:"Convierte la transmisión en memoria compartida.",fx:{morale:3},flags:{operatorNameRemembered:true}}]}},
    {label:"Copiar los archivos y desconectarla",hint:"Conserva la información y cumple su petición de no quedar en manos de la Red UNO.",cost:"Irreversible",title:"El último favor",result:"La operadora entrega la clave y confirma que los merodeadores son exiliados del Valle. Cuando Sara desconecta el soporte, la señal deja de repetirse.",fx:{morale:-3,threat:-2},archive:["origin","names","exiles"],flags:{carryTruth:true},dialogue:{npc:"operator",kicker:"Última conversación",text:"Irene sonríe apenas cuando la copia termina. «Gracias por no dejarme como máquina. La Red UNO guarda nombres para obedecer; ustedes tendrán que guardarlos para responder.»",options:[{label:"Preguntar qué nombre salvar primero",hint:"Recupera una lista prioritaria antes de desconectar.",archive:["names"],fx:{morale:1},flags:{operatorPriorities:true}},{label:"Pedirle una ruta de salida",hint:"Acepta su último acceso técnico.",fx:{threat:-3},flags:{operatorExitRoute:true}},{label:"Desconectar sin más preguntas",hint:"Cumple la decisión con dureza y sin demora.",fx:{morale:-1,threat:-1},flags:{operatorQuietEnd:true}}]}},
    {label:"Mantenerla conectada y retirarse",hint:"Evita decidir por ella ahora, pero deja el sistema expuesto al regreso de la Red UNO.",cost:"Moral −5",title:"La misma señal",result:"El grupo abandona la sala sin tocar el soporte. A sus espaldas, la operadora vuelve a repetir las únicas palabras que puede enviar.",fx:{morale:-5,threat:-4},flags:{leftOperator:true}}
  ]},
  {day:3,time:"17:35",loc:"Cámara de núcleos",type:"Confrontación",title:"Los exiliados regresan",text:"Cinco merodeadores entran en la torre siguiendo los núcleos almacenados por la Red UNO. No vienen por la señal: vienen a recuperar a los suyos. El grupo puede compartir la verdad, negociar una salida o proteger la cámara por la fuerza.",choices:[
    {label:"Abrir la cámara y compartir los archivos",hint:"La tregua exige reconocer públicamente que los exiliados también fueron Rotos.",cost:"Moral +4",reqFlags:["knowsExiles","savedMerodeadora","knowsTruce"],title:"Un nombre anterior al destierro",result:"Las armas descienden cuando el archivo reproduce los nombres borrados. Los merodeadores recuperan los núcleos y entregan una ruta que la Red UNO no puede rastrear.",fx:{morale:4,threat:-7},archive:["truce"],flags:{exileAlliance:true,safeExit:true}},
    {label:"Negociar núcleo por paso seguro",hint:"Entrega tecnología recuperada y obtiene una retirada protegida.",cost:"Pierde núcleo",reqItems:["droneCore"],title:"Una deuda de superficie",result:"El intercambio no borra la desconfianza, pero establece una regla comprensible. Los exiliados escoltarán al grupo hasta salir del radio SONAR.",fx:{morale:1,threat:-5},remove:["droneCore"],flags:{exilePassage:true}},
    {label:"Defender la cámara",hint:"Combate contra tres merodeadores elegidos aleatoriamente entre cinco variantes.",cost:"Combate extremo",combat:{title:"La cámara de los exiliados",brief:"Tres combatientes avanzan mientras los demás cubren la extracción de los núcleos.",encounters:[["merodeador5","merodeador3","merodeador4"],["merodeador2","merodeador","merodeador5"],["merodeador3","merodeador2","merodeador4"]],xp:68,canFlee:true},victory:{title:"Núcleos bajo custodia",result:"Los supervivientes se retiran sin abandonar a sus caídos. La cámara queda en manos del grupo, pero la verdad ahora carga con otra matanza.",fx:{threat:10,morale:-9},archive:["coreRite"],flags:{exilesDefeated:true}},defeat:{title:"El ritual continúa",result:"El grupo abandona la cámara. Los merodeadores recuperan los núcleos y abren una salida lateral antes de desaparecer.",fx:{threat:-2,morale:-5},flags:{exilesRecoveredCores:true}}}
  ]},
  {day:3,time:"20:30",loc:"Torre repetidora 6",type:"Decisión final",title:"¿Quién merece la verdad?",text:"La ventana de transmisión dura menos de un minuto. Los archivos prueban que la Red UNO aisló refugios, que los merodeadores fueron exiliados y que El Valle siguió observando la ciudad. Publicarlos puede despertar Santiago; guardarlos puede proteger a quienes aún no pueden defenderse.",choices:[
    {label:"Transmitir a todos los refugios",hint:"La verdad deja de pertenecer al consejo, al grupo o a la Red UNO, pero revela que la torre sigue activa.",cost:"Final: transmisión",title:"La voz atraviesa la ciudad",result:"Las frecuencias prohibidas despiertan una tras otra. Rotos, cazadores y exiliados oyen los mismos nombres; nadie podrá fingir que la Red UNO protegía a todos.",fx:{threat:18,morale:8},ending:"broadcast"},
    {label:"Llevar los archivos a los Rotos",hint:"La comunidad decidirá qué revelar y cuándo, repitiendo o corrigiendo el secreto de los ancianos.",cost:"Final: regreso",title:"La memoria bajo tierra",result:"El grupo desconecta el almacenamiento. La verdad sobrevivirá al viaje, pero volverá a depender de quienes controlen el archivo.",fx:{threat:-4,morale:2},ending:"return"},
    {label:"Negociar con los Cosechadores",hint:"La información compra alimento, armas y protección; también crea un nuevo dueño para la verdad.",cost:"Final: pacto",title:"Una verdad con dueño",result:"La jefa ofrece paso seguro y suministros. A cambio exige cada copia y el derecho a decidir qué comunidad escucha primero.",fx:{morale:-12,food:3,ammo:2},flags:{veraFinalPact:true},ending:"trade"}
  ]}
];
