"use strict";

// Narrative checks only. Combat dice and the inhibitor's input challenge remain independent.
// Stable IDs belong to choices, so route replacements never inherit a roulette by position.
var decisionScenes={
  council:{mode:"social",lead:"Sara deja la mano sobre el registro de salida. Elías reconoce un sello arrancado; Noa espera junto a la puerta. El consejo debe decidir si esos tres testigos merecen leer lo que otros ocultaron.",quote:"«Si esperan que volvamos, necesitamos saber qué hizo que los otros no volvieran.» — Sara",waiting:"El consejo intercambia miradas…",good:["Archivo","Archivo abierto","Recuperas el registro y puedes interrogar a Varela."],bad:["Rechazo","El consejo cierra filas","Pierdes confianza y queda registrada la desconfianza hacia el consejo."]},
  border:{mode:"social",lead:"Noa baja el arma despacio. Sara abre las manos y Elías deja de tocar su equipo. Al otro lado de las luces rojas, una figura observa si el gesto de uno contradice al de los demás.",quote:"«No crucen la marca. Primero tienen que ver que entendimos.» — Noa",waiting:"Las ópticas siguen sus manos…",good:["Tregua","La frontera se abre","Lira acepta hablar; su historia puede abrir un desvío."],bad:["Aviso","Disparo de advertencia","Retrocedes y pierdes suministros durante la huida."],alarm:{word:"Ataque",title:"El gesto mal leído",note:"Los defensores interpretan el movimiento como una amenaza. Combate.",result:"Un roce de metal rompe el silencio. La primera luz roja avanza y las otras cierran la retirada. Sara se aparta del disparo; Noa alcanza el arma antes de que los defensores crucen su propia marca.",enemies:["merodeador","merodeador2"],winTitle:"Fuera de la línea roja",winText:"El grupo rompe el cerco y se retira por el borde del territorio. Nadie vuelve a confundir la frontera con un camino libre: la ocasión de hablar con Lira quedó atrás."}},
  rails:{mode:"physical",lead:"La cuerda pasa de una cintura a otra. Noa prueba un durmiente antes de apoyar el peso; Sara protege la caja y Elías calcula cuánto metal queda bajo el agua.",quote:"«Si uno resbala, los otros dos sostienen. No tiren antes de sentir el peso.» — Noa",waiting:"La cuerda empieza a tensarse…",good:["Paso","Apoyos firmes","Cruzas y recuperas la medicina."],bad:["Golpe","Metal bajo el agua","Recuperas la caja, pero Elías puede perder hasta 5 HP y aumenta la amenaza."],failDamage:{elias:5}},
  lure:{mode:"technical",lead:"Elías conecta la celda al señuelo. Sara mantiene despejado el corredor y Noa espera junto al cierre manual. Deben mover a los merodeadores antes de que distingan el calor de una máquina del calor de un cuerpo.",quote:"«Cuando sigan la luz, cierren. No esperen a que me vean correr.» — Elías",waiting:"El señuelo emite su primer pulso…",good:["Señuelo","Calor sin pulso","Gastando una batería, conservas la bomba y evitas el combate."],bad:["Fuga","La bomba se pierde","El señuelo consume la batería y falla; escapas sin asegurar la bomba."],alarm:{word:"Cerco",title:"El corredor equivocado",note:"Los merodeadores ignoran el señuelo y bloquean la salida. Combate.",result:"La luz se apaga antes de alcanzar la puerta. Los merodeadores giran hacia el cable y encuentran a Elías en el otro extremo. Noa sostiene el cierre con el hombro: todavía hay espacio para defenderse, pero ya no para pasar inadvertidos.",enemies:["merodeador3","merodeador"],winTitle:"La bomba después del ruido",winText:"El grupo despeja el corredor y recupera el control de la bomba. La batería está agotada y el ruido ya ha recorrido los túneles.",winFlags:{pumpSecured:true,pumpLost:false}}},
  blackout:{mode:"technical",lead:"Elías abre la caja de la subestación. Sara vigila el descenso del dron; Noa cuenta los intervalos entre sus barridos. La batería debe absorber la descarga antes de que el lector identifique al grupo.",quote:"«La luz tiene que morir antes que el silencio.» — Elías",waiting:"La subestación retiene la carga…",good:["Corte","Oscuridad calculada","Consumes una batería y recuperas el núcleo sin transmitir la posición."],bad:["Arco","Transmisión parcial","Obtienes el núcleo y gastas la batería, pero la unidad alcanza a alertar a la red."]},
  pulse:{mode:"composure",lead:"La óptica se detiene sobre el túnel. Sara marca un ritmo con dos dedos; Elías ajusta el respirador y Noa inmoviliza la mano sobre el arma. El dron busca una diferencia entre el calor del lugar y el pulso de los tres.",quote:"«Respiren conmigo. No intenten ganar segundos solos.» — Sara",waiting:"La unidad compara los tres pulsos…",good:["Silencio","Latidos invisibles","S-7 no registra la identidad y deja abierto un contacto con el grupo."],bad:["Marca","El túnel queda marcado","El dron transmite una alerta antes de retirarse."],alarm:{word:"Bloqueo",title:"Tres pulsos confirmados",note:"La unidad fija las identidades y bloquea la subida. Combate con un dron.",result:"La óptica deja de buscar. Tres puntos permanecen encendidos sobre la pared mientras la unidad desciende hasta la salida. Elías suelta el aire que estaba reteniendo: el silencio ya no puede protegerlos.",enemies:["drone"],winTitle:"Silencio entre piezas",winText:"La unidad deja de transmitir cuando su chasis golpea el suelo. La subida queda libre, aunque parte de las identidades ya llegó a la Red UNO."}},
  memory:{mode:"technical",lead:"El núcleo todavía conserva una orden que el terminal reconoce. Elías une los contactos; Sara observa la temperatura de la carcasa y Noa mantiene libre el cable de extracción. Una desconexión precipitada puede borrar el último bloque.",quote:"«No estoy abriendo una puerta. Estoy convenciendo a la máquina de que ya estamos dentro.» — Elías",waiting:"El terminal compara la memoria injertada…",good:["Memoria","Archivo completo","Consumes el núcleo y recuperas protocolo, nombres y datos de la señal."],bad:["Copia","Memoria incompleta","El núcleo se quema. Conservas el protocolo y la red recibe una alerta."]},
  credential:{mode:"deception",lead:"El lector despierta en la mano del agente. Elías entrega la credencial; Sara sostiene la mirada y Noa deja de buscar una salida. Durante unos segundos, los tres deben parecer parte de la misma mentira.",quote:"«No miren el arma. Miren al hombre que decide si puede usarla.» — Elías",waiting:"La patrulla examina la credencial…",good:["Acceso","Identidad aceptada","Cruzas el control, obtienes información y puedes hablar con Vega."],bad:["Retirada","Retirada a tiempo","Escapas entre disparos. Pierdes la credencial y tus identidades quedan registradas."],alarm:{word:"Alarma",title:"Identidades detectadas",note:"La patrulla cierra el cruce. Combate con un agente y un dron.",result:"«Esa identidad pertenece a un muerto.» El lector proyecta las tres identidades sobre el muro y la reja se cierra detrás del grupo. Noa vuelca una mesa; Sara tira de Elías hacia la cobertura. Un dron desciende mientras el agente da la orden de fuego.",enemies:["agent2","drone"],winTitle:"El control deja de responder",winText:"La escolta cae y el grupo cruza antes de que el puesto reciba refuerzos. La credencial se perdió en el lector; vencer no borra las identidades que ya fueron transmitidas."}},
  controller:{mode:"technical",lead:"La caja de control cambia de color con cada latido detectado. Elías conecta la celda mientras Noa vigila a los cazadores y Sara cuenta los intervalos. La sobrecarga debe borrar la identidad antes de que el sensor la replique.",quote:"«Cuando se ponga verde, crucen. Ese color no va a durar.» — Elías",waiting:"El controlador redistribuye la descarga…",good:["Ventana","Verde durante nueve segundos","Consumes una batería y abres una ventana de escape."],bad:["Rastro","La identidad se replica","Escapas, pero pierdes la batería y dejas tu dirección expuesta."]},
  coordinates:{mode:"deception",lead:"La jefa extiende el mapa sobre una mesa marcada por cuchillos. Noa coloca el dedo sobre un túnel vacío; Elías sostiene la explicación técnica y Sara evita mirar hacia la ubicación real del refugio.",quote:"«Una mentira que necesita demasiadas palabras ya empezó a fallar.» — Noa",waiting:"La jefa contrasta las marcas del mapa…",good:["Desvío","Coordenadas creíbles","Proteges el refugio, obtienes el módulo y abres una conversación con Vera."],bad:["Deuda","La tinta no coincide","La jefa detecta el engaño. Los Cosechadores quedan hostiles y aumenta la amenaza."]},
  relay:{mode:"technical",lead:"El relé recibe órdenes del nido y las devuelve a todas las unidades. Elías aproxima el núcleo mientras Sara comprueba sus manos y Noa sigue las ópticas del techo. El mapa falso debe circular antes de que el sistema reconozca su origen.",quote:"«Si pregunta quién envía la ruta, ya tardamos demasiado.» — Elías",waiting:"El relé distribuye el nuevo mapa…",good:["Mapa","Un mapa imposible","Consumes el núcleo y desvías a los drones del nido."],bad:["Rechazo","El injerto es rechazado","Pierdes el núcleo y escapas con una alerta activa."],alarm:{word:"Nido",title:"El nido mira hacia dentro",note:"El relé señala el origen de la intrusión. Combate con dos drones.",result:"Las rutas falsas desaparecen del relé. Una única identidad queda repetida en todas las pantallas: la del grupo. Dos ópticas se desprenden del techo antes de que Elías pueda retirar el núcleo quemado.",enemies:["drone","drone"],winTitle:"Un nido sin ojos",winText:"Las dos unidades dejan de responder y el grupo abandona el relé destruido. El núcleo se consumió durante el intento; la torre conserva la alerta que alcanzó a recibir."}},
  traces:{mode:"investigation",lead:"Noa se arrodilla junto a los impactos. Sara distingue vendas de ataduras y Elías compara la dirección de los disparos. La escena parece una ejecución hasta que los tres empiezan a leerla juntos.",quote:"«Miren hacia dónde apuntaban. No todos estaban peleando entre sí.» — Noa",waiting:"Las huellas empiezan a formar una historia…",good:["Tregua","Una tregua borrada","Recuperas archivos, un mapa y la evidencia de una alianza."],bad:["Duda","Huellas contradictorias","Sigues un camino equivocado hasta un sensor activo; aumenta la amenaza."]},
  floors:{mode:"technical",lead:"Los indicadores del ascensor suben uno tras otro. Elías presenta la credencial; Sara verifica qué puertas siguen abiertas y Noa escucha las botas entre pisos. Una sola orden debe separar a la patrulla de la antena.",quote:"«No necesito cerrar toda la torre. Solo el piso correcto, en el momento correcto.» — Elías",waiting:"La torre verifica la orden de cierre…",good:["Cierre","Una torre dividida","Aíslas a la patrulla y aseguras la antena."],bad:["Brecha","Acceso revocado","Pierdes la credencial. Solo sellas un piso y la transmisión queda comprometida."],alarm:{word:"Asalto",title:"La orden abre la esclusa",note:"La torre rechaza el cierre y una escuadra alcanza la sala. Combate.",result:"La credencial se apaga. Al otro lado del cristal, una puerta que debía cerrarse libera a la primera escuadra. Noa arrastra un armario frente a la consola; Sara y Elías quedan entre la patrulla y la antena.",enemies:["agent2","agent3"],winTitle:"La antena sigue en pie",winText:"El grupo expulsa a la escuadra de la sala y asegura la consola. La credencial quedó quemada, pero la antena todavía puede transmitir sin aquella interferencia.",winFlags:{antennaHeld:true,weakBroadcast:false}}},
  recoveredNames:{mode:"investigation",lead:"El registro original ya no existe. Elías despliega la copia que rescató antes del colapso; Sara compara las placas con los cuerpos y Noa busca una coincidencia entre las posiciones y los nombres incompletos.",quote:"«Una copia no devuelve a nadie. Pero todavía puede impedir que los borren dos veces.» — Sara",waiting:"La copia devuelve identidades fragmentadas…",good:["Nombres","Una copia contra el olvido","Reconstruyes parte de la tregua y recuperas una ruta con los nombres rescatados."],bad:["Fragmento","Nombres sin rostro","Conservas la evidencia fragmentaria, pero no obtienes el mapa de la tregua."]}
};

// Each living character contributes percentage points for this kind of action.
// The base remains the original check's neutral probability; the old psychological
// bonus is replaced, not added again. Three characters can shift it at most 15 pp.
var decisionMoodWeights={
  social:{sereno:5,empatico:5,resuelto:0,pragmatico:0,tenso:-5,culpa:0,rabia:-5,frio:-5},
  physical:{sereno:5,empatico:0,resuelto:5,pragmatico:0,tenso:-5,culpa:-5,rabia:0,frio:0},
  technical:{sereno:5,empatico:0,resuelto:0,pragmatico:5,tenso:-5,culpa:-5,rabia:-5,frio:5},
  composure:{sereno:5,empatico:5,resuelto:0,pragmatico:0,tenso:-5,culpa:-5,rabia:-5,frio:5},
  deception:{sereno:5,empatico:0,resuelto:0,pragmatico:5,tenso:-5,culpa:-5,rabia:-5,frio:5},
  investigation:{sereno:5,empatico:5,resuelto:0,pragmatico:5,tenso:-5,culpa:0,rabia:-5,frio:0}
};
var decisionModeNames={social:"Diálogo",physical:"Coordinación",technical:"Maniobra técnica",composure:"Control del pulso",deception:"Engaño",investigation:"Investigación"};
var decisionState=null,decisionAnimationTimer=null,decisionFinishTimer=null;
function decisionScene(choice){return choice&&decisionScenes[choice.decisionId]||null}
function decisionProbability(choice){
  var scene=decisionScene(choice),weights=decisionMoodWeights[scene?scene.mode:"technical"],base=clamp((21-choice.roll.dc+(choice.roll.bonus||0))*5,0,100);
  var members=state.party.map(function(p){var mood=psychState(p),key=Object.keys(psychStateDefs).filter(function(k){return psychStateDefs[k]===mood})[0]||"estable";return{name:p.name,mood:mood.name,bonus:p.hp>0?(weights[key]||0):0,available:p.hp>0}});
  var modifier=members.reduce(function(n,m){return n+m.bonus},0),success=clamp(base+modifier,5,95),alarm=scene&&scene.alarm?Math.round((100-success)/3):0;
  var counts={};members.filter(function(m){return m.available}).forEach(function(m){counts[m.mood]=(counts[m.mood]||0)+1});var live=members.filter(function(m){return m.available}).length,dominant=Object.keys(counts).filter(function(k){return counts[k]>live/2})[0];
  return{base:base,modifier:success-base,rawModifier:modifier,members:members,mood:dominant||"Mixto",chances:alarm?[success,100-success-alarm,alarm]:[success,100-success]}
}
function decisionCostText(choice){
  if(!choice.roll)return choice.cost||"";var cost=String(choice.cost||"").replace(/Dificultad\s+\d+/i,"").trim();return(cost?cost+" · ":"")+"Favorable "+decisionProbability(choice).chances[0]+"%"
}
function clearDecision(){
  clearInterval(decisionAnimationTimer);clearTimeout(decisionFinishTimer);decisionAnimationTimer=null;decisionFinishTimer=null;decisionState=null;$("decisionOutcomeModal").classList.add("hidden");$("decisionModal").classList.add("hidden");$("decisionModal").removeAttribute("inert");$("decisionModal").removeAttribute("aria-hidden");$("decisionModal").setAttribute("aria-modal","true");signalLastTick=Date.now()
}
function closeDecision(){if(!decisionState||decisionState.phase!=="ready")return;var opener=decisionState.opener;clearDecision();if(opener&&opener.focus)opener.focus()}
function decisionSigned(n){return(n>0?"+":"")+n}
function decisionDraw(angle){
  $("decisionWheel").style.transform="rotate("+angle+"deg)";
  Array.prototype.forEach.call($("decisionWheel").querySelectorAll(".decision-wheel-label"),function(label){label.style.transform="translate(-50%,-50%) rotate("+(-angle)+"deg)"})
}
function openDecision(choice,ev){
  if(decisionState||pending||battleState)return false;
  var scene=decisionScene(choice)||{mode:"technical",lead:ev.text,waiting:"El grupo intenta la maniobra…",good:["Avance",choice.roll.success.title,choice.roll.success.result],bad:["Revés",choice.roll.fail.title,choice.roll.fail.result]};
  var probability=decisionProbability(choice),options=[{key:"success",word:scene.good[0],title:scene.good[1],note:scene.good[2],out:choice.roll.success},{key:"fail",word:scene.bad[0],title:scene.bad[1],note:scene.bad[2],out:choice.roll.fail}];
  if(scene.alarm)options.push({key:"alarm",word:scene.alarm.word,title:scene.alarm.title,note:scene.alarm.note,out:Object.assign({},choice.roll.fail,{title:scene.alarm.title,result:scene.alarm.result})});
  decisionState={phase:"ready",choice:choice,scene:scene,index:state.index,probability:probability,options:options,opener:document.activeElement,changes:[],selected:null};
  $("decisionKicker").textContent=ev.loc+" · "+decisionModeNames[scene.mode];$("decisionTitle").textContent=choice.label;$("decisionLead").textContent=scene.lead;$("decisionQuote").textContent=scene.quote||"";$("decisionQuote").classList.toggle("hidden",!scene.quote);
  $("decisionMood").textContent=probability.mood;$("decisionModifier").textContent=probability.modifier?decisionSigned(probability.modifier)+" puntos de probabilidad":"Sin cambio de probabilidad";
  $("decisionParty").innerHTML=probability.members.map(function(m){return'<div class="decision-member"><strong>'+esc(m.name)+'</strong><span>'+esc(m.mood)+'</span><small class="'+(m.bonus<0?"adverse":m.bonus>0?"favorable":"")+'">'+(m.available?(m.bonus?decisionSigned(m.bonus)+" puntos":"Sin modificador"):"Agotado · no participa")+'</small></div>'}).join("");
  $("decisionMath").textContent="Probabilidad favorable: "+probability.base+"% de base "+decisionSigned(probability.rawModifier)+" puntos por el grupo = "+probability.chances[0]+"%. El aporte depende de la acción y solo cuenta a quienes pueden participar.";
  $("decisionExplanation").open=false;$("decisionStatus").textContent="El resultado sigue siendo incierto";$("decisionResolution").classList.add("hidden");$("decisionConfirm").textContent="Resolver acción";$("decisionConfirm").disabled=false;$("decisionBack").classList.remove("hidden");$("decisionSurface").dataset.result="";$("decisionSurface").classList.remove("decided","resolving");
  $("decisionCost").textContent=String(choice.cost||"").replace(/Dificultad\s+\d+/i,"").trim()||(choice.reqItems&&choice.reqItems.length?"Requiere "+choice.reqItems.map(function(id){return gear(id)?gear(id).name:resName(id)}).join(", "):"Sin consumo fijo de objetos");
  var angle=0,stops=[],labels=[];options.forEach(function(opt,i){var end=angle+probability.chances[i]*3.6,mid=(angle+end)/2*Math.PI/180;opt.start=angle;opt.end=end;stops.push(["#102726","#282116","#2b1615"][i]+" "+angle+"deg "+end+"deg");labels.push('<span class="decision-wheel-label" style="left:'+(50+31*Math.sin(mid))+'%;top:'+(50-31*Math.cos(mid))+'%">'+esc(opt.word)+'</span>');angle=end});
  $("decisionWheel").style.background="conic-gradient("+stops.join(",")+")";$("decisionWheel").innerHTML=labels.join("");decisionDraw(0);
  $("decisionOptions").innerHTML=options.map(function(opt,i){return'<div class="decision-option '+opt.key+'" data-decision-outcome="'+i+'"><div><strong>'+esc(opt.title)+'</strong><b>'+probability.chances[i]+'%</b></div><p>'+esc(opt.note)+'</p></div>'}).join("");
  $("decisionWheelBox").setAttribute("aria-label",options.map(function(opt,i){return opt.title+" "+probability.chances[i]+"%"}).join("; "));
  $("decisionModal").classList.remove("hidden");$("decisionSurface").scrollTop=0;$("decisionConfirm").focus({preventScroll:true});return true
}
function resolveDecision(){
  var game=decisionState;if(!game||game.phase!=="ready")return;
  if(game.index!==state.index||reason(game.choice)){closeDecision();toast("La acción ya no está disponible");return}
  // The pre-encounter checkpoint includes the seed. Reload cannot reroll or keep rewards.
  save();encounterSaveLocked=true;game.phase="spinning";drainHunger(4);$("decisionBack").classList.add("hidden");$("decisionConfirm").disabled=true;$("decisionConfirm").textContent="Resolviendo…";$("decisionStatus").textContent=game.scene.waiting;$("decisionSurface").classList.add("resolving");playSfx("ui-click");
  var draw=random()*100,cumulative=0,index=game.options.length-1;game.probability.chances.some(function(chance,i){cumulative+=chance;if(draw<cumulative){index=i;return true}return false});game.selected=index;
  var opt=game.options[index],landing=(opt.start+opt.end)/2,target=360*6+360-landing,reduced=window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches,duration=reduced?180:3200,start=Date.now();
  game.target=target;
  if(!reduced)decisionAnimationTimer=setInterval(function(){if(decisionState!==game)return;var t=clamp((Date.now()-start)/duration,0,1);decisionDraw(target*(1-Math.pow(1-t,4)))},32);
  decisionFinishTimer=setTimeout(function(){if(decisionState!==game||game.phase!=="spinning")return;clearInterval(decisionAnimationTimer);decisionAnimationTimer=null;decisionFinishTimer=null;decisionDraw(target);revealDecision(game)},duration)
}
function decisionDamage(damage){
  var changes=[];Object.keys(damage||{}).forEach(function(id){var p=state.party.filter(function(m){return m.id===id})[0];if(!p||p.hp<=1)return;var lost=Math.min(damage[id],p.hp-1);p.hp-=lost;state.stats.damageTaken+=lost;changes.push([p.name+" · golpe","−"+lost+" HP"])});return changes
}
function revealDecision(game){
  if(decisionState!==game||game.phase!=="spinning")return;game.phase="resolved";
  var opt=game.options[game.selected],isCombat=opt.key==="alarm",damage=opt.key==="fail"?decisionDamage(game.scene.failDamage):[];
  if(isCombat){game.changes=apply(opt.out);renderMini()}else{completeChoice(game.choice,opt.out,null,null,damage);$("result").classList.add("hidden")}
  $("decisionResolutionTitle").textContent=opt.out.title;$("decisionResolutionText").textContent=opt.out.result;
  $("decisionChanges").innerHTML=isCombat?game.changes.map(function(c){return'<div class="result-chip">'+esc(c[0])+'<strong>'+esc(c[1])+'</strong></div>'}).join(""):$("resultChanges").innerHTML;
  $("decisionResolution").classList.remove("hidden");$("decisionSurface").classList.remove("resolving");$("decisionSurface").classList.add("decided");$("decisionSurface").dataset.result=opt.key;
  Array.prototype.forEach.call($("decisionOptions").querySelectorAll("[data-decision-outcome]"),function(node){node.classList.toggle("selected",Number(node.dataset.decisionOutcome)===game.selected)});
  $("decisionStatus").textContent="Acción decidida · "+opt.title;$("decisionConfirm").textContent="Acción decidida";$("decisionConfirm").disabled=true;
  $("decisionOutcomeKicker").textContent=isCombat?"Acción decidida · contacto hostil":"Acción decidida · consecuencia";
  $("decisionOutcomeContinue").textContent=isCombat?"Prepararse para el combate":pending&&pending.dialogue?"Continuar la conversación":"Continuar expedición";
  $("decisionOutcomeModal").dataset.result=opt.key;$("decisionOutcomeModal").classList.remove("hidden");$("decisionResolution").scrollTop=0;
  $("decisionOutcomeContinue").focus({preventScroll:true});$("decisionModal").setAttribute("inert","");$("decisionModal").setAttribute("aria-hidden","true");$("decisionModal").removeAttribute("aria-modal");
  playSfx(opt.key==="success"?"ui-click":"ui-error")
}
function continueDecision(){
  var game=decisionState;if(!game||game.phase!=="resolved")return;var opt=game.options[game.selected];game.phase="committed";clearDecision();
  if(opt.key==="alarm"){
    var alarm=game.scene.alarm,choice={label:game.choice.label,title:alarm.title,_decisionChanges:game.changes,victory:{title:alarm.winTitle,result:alarm.winText,flags:alarm.winFlags||{}}};
    startCombat({title:alarm.title,brief:alarm.result,enemies:alarm.enemies,canFlee:true},choice);return
  }
  advance()
}
function decisionPrimaryAction(){if(!decisionState)return;if(decisionState.phase==="ready")resolveDecision();else if(decisionState.phase==="resolved")continueDecision()}
function decisionKeydown(e){
  if(!decisionState)return false;
  if(e.key==="Escape"){e.preventDefault();closeDecision();return true}
  if(e.key==="Tab"){
    var activeModal=decisionState.phase==="resolved"?$("decisionOutcomeModal"):$("decisionModal"),focusable=Array.prototype.slice.call(activeModal.querySelectorAll('button:not(:disabled),summary')).filter(function(n){return n.getClientRects().length>0});
    if(focusable.length){var first=focusable[0],last=focusable[focusable.length-1];if(focusable.indexOf(document.activeElement)<0){e.preventDefault();(e.shiftKey?last:first).focus()}else if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}else e.preventDefault();
  }
  // Native button/summary Enter and Space behavior is retained. No global choice shortcuts.
  return true
}
document.getElementById("decisionOutcomeContinue").addEventListener("click",continueDecision);
