"use strict";
// Save schema 3 is independent of the product version. Load before game-v2.js; functions run after runtime initialization.
function fresh(){return{companionCommitments:{version:1,care:null,route:null,information:null,trade:null},expeditionRest:{version:1,nights:{}},worldContinuity:{version:1,facts:{}},fieldUpgrades:typeof fieldFresh==="function"?fieldFresh():null,version:3,finaleRevision:1,campaignRevision:3,inventoryRevision:5,progressionRevision:1,introCompleted:false,introPage:0,storyPreludeSeen:false,logisticsSeen:false,economyHelpSeen:false,index:0,threat:18,morale:64,credits:0,factionPoints:0,collection:[],tradeStock:tradeStockForDay(1),tradeStockDay:1,armorerStock:armorerStockForDay(1),armorerStockDay:1,starterKitGiven:false,refuge:{active:false,reason:null,rested:false,rejoined:false,visits:0,npc:"mara",message:""},inhibitor:{active:false,remainingMs:0,durationMs:270000,exposed:true,needsSync:true,tutorialSeen:false,successes:0,failures:0,alarms:0,exposedMoves:0},summarySeen:false,finalTier:null,score:0,engineeringUses:3,medicalUses:3,ordnanceUses:3,res:{food:0,water:4,meds:0,ammo:0,battery:0},cons:{bandage:0,emp:0,grenade:0},party:[
  {id:"sara",name:"Sara",role:"Médico",hp:44,maxHp:44,hunger:82,xp:0,level:1,skills:[],guard:0,bleed:0,psyche:{stress:0,empathy:2,resolve:1,pragmatism:0},categories:["sidearm","melee"],equipment:{head:null,body:"vestLight",weapon:"pistol9",backpack:"packMedic"},durability:{head:null,body:10},bag:[{id:"ammo9",qty:6},{id:"bandage",qty:1},{id:"meds",qty:1},{id:"food",qty:2}]},
  {id:"elias",name:"Elías",role:"Ingeniero",hp:40,maxHp:40,hunger:76,xp:0,level:1,skills:[],guard:0,bleed:0,psyche:{stress:0,empathy:0,resolve:1,pragmatism:2},categories:["sidearm","shotgun","rifle","melee"],equipment:{head:"helmetWork",body:null,weapon:"crowbar",backpack:"packRig"},durability:{head:8,body:null},bag:[{id:"shell12",qty:4},{id:"emp",qty:1},{id:"food",qty:1},{id:"battery",qty:1},{id:"tool",qty:1}]},
  {id:"noa",name:"Noa",role:"Cazadora",hp:38,maxHp:38,hunger:88,xp:0,level:1,skills:[],guard:0,bleed:0,psyche:{stress:1,empathy:0,resolve:2,pragmatism:1},categories:["rifle","sidearm","melee"],equipment:{head:null,body:"vestLight",weapon:"rifle556",backpack:"packHunt"},durability:{head:null,body:10},bag:[{id:"ammo556",qty:6},{id:"grenade",qty:1},{id:"food",qty:1}]}
],inv:[],docs:["signal"],flags:{},missionRewards:{},history:[],stats:{battles:0,wins:0,enemies:0,loot:0,lootItems:{},fullSquadWins:0,criticals:0,retreats:0,refugeVisits:0,trades:0,creditsEarned:0,attacks:0,hits:0,misses:0,shots:0,damageDealt:0,damageTaken:0,medicineUsed:0,hpRestored:0,restHpRecovered:0,rests:0,skillsUsed:0,revives:0,defends:0,crafts:0,craftedItems:{},itemsUsed:{},disassembled:0,disassembleFailures:0,mentalShifts:0,xpFromHits:0,xpFromCrafting:0,xpFromVictories:0,factionEarned:0,factionSpent:0,skillsUnlocked:0,signalHacks:0,signalSuccesses:0,signalFailures:0,signalAlarms:0,trackingCombats:0},seed:2130,ending:null,finished:false}}

// Persist complete encounters only: pending UI and combat callbacks are not serialized.
// The title screen must never replace a save before the player starts or resumes.
var gameSessionActive=false,encounterSaveLocked=false;
function serializeCampaignSave(snapshot){
  var ev=events[snapshot.index];
  if(!ev||!ev.id)throw Error("Escena de campaña desconocida");
  return JSON.stringify(Object.assign({},snapshot,{sceneId:ev.id}));
}
function save(){if(!gameSessionActive||encounterSaveLocked)return;try{localStorage.setItem(KEY,serializeCampaignSave(state))}catch{}}
function load(serializedSave){
  // Validation and legacy migrations use the shared state binding. Commit it
  // only when every validator succeeds; a rejected save must not poison a session.
  var previousState=state;
  try{
    var x=JSON.parse(serializedSave===undefined?localStorage.getItem(KEY):serializedSave),base=fresh(),baseParty=base.party,baseRes=base.res,baseCons=base.cons,baseStats=base.stats,baseRefuge=base.refuge,baseInhibitor=base.inhibitor,baseEngineeringUses=base.engineeringUses,baseMedicalUses=base.medicalUses,baseOrdnanceUses=base.ordnanceUses;
    if(!x||x.version!==3)return false;
    var resolvedIndex=NeoCampaignScenes.resolve(events,x);
    if(resolvedIndex<0)return false;
    x.index=resolvedIndex;delete x.sceneId; // Runtime remains ordinal; saves carry a stable location.
    if(x.matiasBridge!==undefined)NeoCommunityBridge.request(x.matiasBridge);
    if(x.rosaBridge!==undefined)NeoRosaBridge.request(x.rosaBridge);
    state=Object.assign(base,x);state.finaleRevision=x.finished&&!x.finaleRevision?0:1;state.campaignRevision=3;state.inventoryRevision=5;state.progressionRevision=1;state.introCompleted=x.introCompleted===undefined?true:!!x.introCompleted;state.storyPreludeSeen=!!x.storyPreludeSeen;state.logisticsSeen=!!x.logisticsSeen;state.economyHelpSeen=!!x.economyHelpSeen;state.res=Object.assign(baseRes,x.res||{});state.cons=Object.assign(baseCons,x.cons||{});state.stats=Object.assign(baseStats,x.stats||{});state.stats.lootItems=Object.assign({},baseStats.lootItems,(x.stats&&x.stats.lootItems)||{});state.stats.craftedItems=Object.assign({},baseStats.craftedItems,(x.stats&&x.stats.craftedItems)||{});state.stats.itemsUsed=Object.assign({},baseStats.itemsUsed,(x.stats&&x.stats.itemsUsed)||{});state.missionRewards=Object.assign({},x.missionRewards||{});state.refuge=Object.assign(baseRefuge,x.refuge||{});state.inhibitor=Object.assign(baseInhibitor,x.inhibitor||{});state.inhibitor.remainingMs=clamp(Number(state.inhibitor.remainingMs)||0,0,360000);state.inhibitor.durationMs=clamp(Number(state.inhibitor.durationMs)||270000,90000,360000);state.inhibitor.active=!!state.inhibitor.active&&state.inhibitor.remainingMs>0;state.inhibitor.exposed=!state.inhibitor.active;state.refuge.npc=state.refuge.npc==="armorer"?"armorer":"mara";state.credits=Math.max(0,Number(x.credits)||0);state.factionPoints=Math.max(0,Number(x.factionPoints)||0);state.starterKitGiven=x.starterKitGiven===undefined?true:!!x.starterKitGiven;state.summarySeen=!!(x.summarySeen||x.epilogueSeen);state.finalTier=x.finalTier||null;state.score=Math.max(0,Number(x.score)||0);state.tradeStockDay=Number(x.tradeStockDay)||((events[x.index]||events[0]).day);state.tradeStock=Object.assign(tradeStockForDay(state.tradeStockDay),x.tradeStock||{});state.armorerStockDay=Number(x.armorerStockDay)||((events[x.index]||events[0]).day);state.armorerStock=Object.assign(armorerStockForDay(state.armorerStockDay),x.armorerStock||{});state.engineeringUses=clamp(Number.isFinite(Number(x.engineeringUses))?Number(x.engineeringUses):baseEngineeringUses,0,3);state.medicalUses=clamp(Number.isFinite(Number(x.medicalUses))?Number(x.medicalUses):baseMedicalUses,0,3);state.ordnanceUses=clamp(Number.isFinite(Number(x.ordnanceUses))?Number(x.ordnanceUses):baseOrdnanceUses,0,3);
    state.inhibitor.needsSync=!state.inhibitor.active;
    state.collection=Array.isArray(x.collection)?Array.from(new Set(x.collection.filter(function(id){return typeof battleCollectibles!=="undefined"&&!!battleCollectibles[id]}))):[];
    state.party=baseParty.map(function(p,i){var saved=(x.party||[])[i]||{},baseRole=p.role,baseMaxHp=p.maxHp,baseHunger=p.hunger,baseEquipment=p.equipment,baseDurability=p.durability,baseCategories=p.categories,baseBag=p.bag,merged=Object.assign(p,saved),savedHp=Number(saved.hp),savedHunger=Number(saved.hunger);merged.level=Math.max(1,Number(merged.level)||1);merged.skills=Array.isArray(saved.skills)?saved.skills.filter(function(id){return(skillTrees[merged.id]||[]).some(function(node){return node.id===id})}):[];merged.role=baseRole;merged.maxHp=baseMaxHp+(merged.level-1)*6;merged.hp=clamp(Number.isFinite(savedHp)?savedHp:merged.maxHp,0,merged.maxHp);merged.hunger=clamp(Number.isFinite(savedHunger)?savedHunger:baseHunger,0,100);merged.equipment=Object.assign({},baseEquipment,saved.equipment||{});merged.durability=Object.assign({},baseDurability,saved.durability||{});["head","body"].forEach(function(slot){var d=gear(merged.equipment[slot]);if(d&&d.maxDurability&&!Number.isFinite(Number(merged.durability[slot])))merged.durability[slot]=d.maxDurability;if(!d)merged.durability[slot]=null});merged.categories=baseCategories.slice();merged.bag=(saved.bag||baseBag).map(function(entry){var d=gear(entry.id),out={id:entry.id,qty:entry.qty};if(d&&d.maxDurability)out.durability=clamp(Number.isFinite(Number(entry.durability))?Number(entry.durability):d.maxDurability,0,d.maxDurability);return out});normalizePsyche(merged);return merged});
    redistributeOverflow();migrateLegacyInventory();redistributeOverflow();if(typeof normalizeWorldContinuity==="function")normalizeWorldContinuity();if(typeof narrativeNormalize==="function")narrativeNormalize();if(typeof migrateNarrativeFinale==="function")migrateNarrativeFinale(x);if(typeof fieldNormalize==="function")fieldNormalize();if(typeof normalizeExpeditionRest==="function")normalizeExpeditionRest();if(typeof normalizeCompanionCommitments==="function")normalizeCompanionCommitments();if(x.outcomes!==undefined)state.outcomes=NeoOutcomes.normalize(x.outcomes);return true
  }catch{state=previousState;return false}
}
