const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ready=import('../extensions/mensajeros/production.mjs');
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../extensions/mensajeros/production.json')));
async function setup(id='guzman-01',seed=2130){const E=await ready,d=E.prepare(source);return {E,d,w:E.start(d,E.createWorld(d,{seed}),id)}}
function finish(E,d,w,fight=false){let guard=0;while(w.run.status==='active'&&guard++<260){
 if(!w.run.pending){if(E.here(d,w).rest&&w.run.condition<78&&w.run.supplies.food&&w.run.supplies.water&&!w.run.rested.includes(w.run.index))w=E.rest(d,w);w=E.advance(d,w);}
 if(w.run.status!=='active')break;const os=E.options(d,w).filter(o=>E.optionAvailable(w,o));
 let o=w.run.pending.combat?(os.find(x=>x.id==='fire')||os.find(x=>x.id==='melee')):fight&&w.run.pending.category==='hostile'?os.find(x=>x.combat):os.find(x=>x.id==='scout')||os.find(x=>x.id==='jam-skill')||os.find(x=>x.id==='assist')||os.find(x=>x.id==='avoid')||os.find(x=>x.id==='continue')||os[0];
 assert.ok(o,'reachable action');w=E.choose(d,w,o.id);w=E.restore(d,E.serialize(w));
 }assert.ok(guard<260,'journey terminates');return w;}
test('all seven contacts, routes and images resolve and production is separate from laboratory',async()=>{const E=await ready,d=E.prepare(source);assert.equal(Object.keys(d.missions).length,7);assert.equal(d.contacts.length,7);assert.equal(d.crew.length,3);assert.notEqual(d.save_key,JSON.parse(fs.readFileSync(path.join(__dirname,'../extensions/mensajeros/data.json'))).save_key);for(const i of [...Object.values(d.items),...d.crew,...d.contacts])assert.ok(fs.existsSync(path.resolve(__dirname,'../extensions/mensajeros',i.image)),i.image);for(const m of Object.values(d.missions)){assert.ok(d.contacts.some(n=>n.id===m.npc));const r=d.routes[m.route];assert.equal(r.nodes.length,r.edges.length+1);r.edges.forEach((e,i)=>{assert.equal(e.from,r.nodes[i]);assert.equal(e.to,r.nodes[i+1])})}});
test('every assignment completes from fresh state across seeds, persists decisions and pays once',async()=>{for(const id of Object.keys(source.missions))for(const seed of [1,4,18,2130]){const {E,d,w}=await setup(id,seed),done=finish(E,d,w);assert.equal(done.run.status,'completed',id+' '+seed);assert.equal(done.credits,d.missions[id].reward.base+d.missions[id].reward.stealth_bonus);assert.ok(done.effects.includes(id));assert.ok(done.crew.every(x=>x.xp===35));assert.throws(()=>E.start(d,done,id),/entregado/);assert.throws(()=>E.choose(d,done,'deliver'));assert.ok(done.run.receipt.effect);}});
test('pickup missions begin empty and cannot deliver before collecting their protected cargo',async()=>{const {E,d,w}=await setup('romero-01');assert.deepEqual(w.run.cargo,{});let at=E.advance(d,w);assert.equal(at.run.pending.id,'romero-reserva');at=E.choose(d,at,'signal');assert.deepEqual(at.run.cargo,{'medical-case':1});assert.ok(at.run.flags.includes('romero_avisado'));let end=E.advance(d,at);end.run.cargo={};assert.throws(()=>E.choose(d,end,'deliver'),/incompleta/);});
test('tactical battle persists actor, targets, HP and resource costs across reload; retreat preserves unresolved passage',async()=>{const {E,d}=await setup();let w;for(let seed=0;seed<100;seed++){w=E.advance(d,E.start(d,E.createWorld(d,{seed}),'adasme-01'));if(w.run.pending.category==='hostile')break;}w=E.choose(d,w,'fight');assert.ok(w.run.pending.combat.enemies.length);const ammo=w.run.supplies.ammo556;w=E.choose(d,w,'fire');assert.equal(w.run.supplies.ammo556,ammo-2);assert.equal(w.run.pending.combat.actor,1);assert.deepEqual(E.restore(d,E.serialize(w)),w);const alerts=w.regions.oriente,index=w.run.index;w=E.choose(d,w,'smoke-retreat');assert.equal(w.run.index,index);assert.equal(w.regions.oriente,alerts);assert.equal(w.run.pending,null);w=E.advance(d,w);assert.equal(w.run.pending.category,'hostile');assert.equal(w.run.combats,1);});
test('victory resolves the passage, gives loot once, and uses three individual actors',async()=>{const {E,d}=await setup();let w;for(let seed=0;seed<100;seed++){w=E.advance(d,E.start(d,E.createWorld(d,{seed}),'adasme-01'));if(w.run.pending.category==='hostile')break;}w=E.choose(d,w,'fight');const start=w.run.index,seen=new Set();for(let i=0;i<70&&w.run.pending?.combat;i++){seen.add(w.run.pending.combat.actor);w=E.choose(d,w,w.run.supplies.ammo556>=2?'fire':'melee');}assert.equal(w.run.status,'active');assert.equal(w.run.index,start+1);assert.ok(seen.size>1);assert.ok(w.run.log.some(s=>s.includes('Recuperan 2')));assert.throws(()=>E.choose(d,w,'fire'));});
test('separate permanent rewards change prices, supplies and group progression',async()=>{const {E,d}=await setup();let w=E.createWorld(d,{seed:1});for(const id of ['romero-01','beatriz-01'])w=finish(E,d,E.start(d,w,id));assert.equal(E.price(d,w,'medkit'),6);assert.equal(E.price(d,w,'food'),3);assert.ok(w.crew.every(c=>c.level===2));const money=w.credits;w=E.buy(d,w,'medkit');assert.equal(w.credits,money-6);assert.equal(w.stock.medkit,1);w=E.start(d,w,'guzman-01');assert.equal(w.run.supplies.medkit,1);assert.deepEqual(w.stock,{});w=E.advance(d,w);assert.throws(()=>E.buy(d,w,'water'),/control/);});
test('defeat recovers from checkpoint without erasing enemy rolls or regional alert',async()=>{const {E,d,w}=await setup();let lost=E.advance(d,w);lost.run.status='failed';lost.run.condition=0;lost.run.party.forEach(c=>c.hp=0);lost.regions.l6=2;lost.run.combats=2;const revived=E.retry(d,lost);assert.equal(revived.run.status,'active');assert.equal(revived.regions.l6,2);assert.equal(revived.run.combats,2);assert.ok(revived.run.party.every(c=>c.hp>0));assert.deepEqual(revived.run.rolls,lost.run.rolls);});
test('invalid courier and foreign save data are rejected without mutation',async()=>{const {E,d,w}=await setup();const raw=E.serialize(w);const bad=JSON.parse(raw);bad.run.party[0].hp=-1;assert.throws(()=>E.restore(d,JSON.stringify(bad)),/Mensajero/);assert.throws(()=>E.restore(d,JSON.stringify({version:3})));assert.equal(E.serialize(w),raw);});
test('purchased supplies and crafted tools survive delivery; borrowed loadout is not farmable',async()=>{const {E,d}=await setup();let w=E.createWorld(d,{seed:1});w.credits=40;w=E.buy(d,w,'scrap');w=E.buy(d,w,'scrap');w=E.craft(d,w,'trap');assert.equal(w.stock.trap,1);assert.equal(w.stock.scrap,0);assert.throws(()=>E.craft(d,w,'trap'),/materiales/);w=E.start(d,w,'romero-01');w=finish(E,d,w);assert.equal(w.stock.trap,1);assert.equal(w.stock.food,undefined);assert.equal(w.stock.water,undefined);});
test('returning a failed assignment cannot strand a penniless exhausted team',async()=>{const {E,d,w}=await setup();w.run.status='failed';w.run.party.forEach(c=>c.hp=0);assert.throws(()=>E.start(d,w,'adasme-01'),/interrumpido/);const returned=E.abandon(d,w),next=E.start(d,returned,'adasme-01');assert.ok(next.run.party.every(c=>c.hp>=Math.ceil(c.maxHp*.4)));assert.equal(next.credits,0);});
