const {connectedWorld,atOrigin}=require('./courier-fixtures.cjs');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ready=import('../extensions/mensajeros/production.mjs');
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../extensions/mensajeros/production.json')));
async function setup(id='guzman-01',seed=2130){const E=await ready,d=E.prepare(source);return {E,d,w:E.start(d,atOrigin(d,connectedWorld(E,d,{seed}),id),id)}}
function finish(E,d,w,fight=false){let guard=0;while(w.run.status==='active'&&guard++<260){
 if(!w.run.pending){if(E.here(d,w).rest&&w.run.condition<78&&w.run.supplies.food&&w.run.supplies.water&&!w.run.rested.includes(w.run.index))w=E.rest(d,w);w=E.advance(d,w);}
 if(w.run.pending?.combat?.phase==='loot'){w=E.finishLoot(d,w);continue;}
 if(w.run.status!=='active')break;const os=E.options(d,w).filter(o=>E.optionAvailable(w,o));
 let o=w.run.pending.combat?(os.find(x=>x.id==='fire')||os.find(x=>x.id==='melee')):fight&&w.run.pending.category==='hostile'?os.find(x=>x.combat):os.find(x=>x.id==='scout')||os.find(x=>x.id==='jam-skill')||os.find(x=>x.id==='assist')||os.find(x=>x.id==='avoid')||os.find(x=>x.id==='continue')||os[0];
 assert.ok(o,'reachable action');w=E.choose(d,w,o.id);w=E.restore(d,E.serialize(w));
 }assert.ok(guard<260,'journey terminates');return w;}
test('all seven contacts, routes and images resolve and production is separate from laboratory',async()=>{const E=await ready,d=E.prepare(source);assert.equal(Object.keys(d.missions).length,8);assert.equal(d.contacts.length,7);assert.equal(d.crew.length,3);assert.notEqual(d.save_key,JSON.parse(fs.readFileSync(path.join(__dirname,'../extensions/mensajeros/data.json'))).save_key);for(const i of [...Object.values(d.items),...d.crew,...d.contacts])assert.ok(fs.existsSync(path.resolve(__dirname,'../extensions/mensajeros',i.image)),i.image);for(const m of Object.values(d.missions)){assert.ok(d.contacts.some(n=>n.id===m.npc));const r=d.routes[m.route];assert.equal(r.nodes.length,r.edges.length+1);r.edges.forEach((e,i)=>{assert.equal(e.from,r.nodes[i]);assert.equal(e.to,r.nodes[i+1])})}});
test('every introduced assignment completes across seeds, persists decisions and pays once',async()=>{for(const id of Object.keys(source.missions))for(const seed of [1,4,18,2130]){const {E,d,w}=await setup(id,seed),done=finish(E,d,w);assert.equal(done.run.status,'completed',id+' '+seed);assert.equal(done.credits,done.run.receipt.amount);assert.equal(done.run.receipt.gross,d.missions[id].reward.base+d.missions[id].reward.stealth_bonus);assert.equal(done.run.receipt.amount,done.run.receipt.gross-done.run.receipt.penalty);assert.ok(done.effects.includes(id));assert.ok(done.crew.every(x=>x.xp>=35));assert.throws(()=>E.start(d,done,id),/entregado/);assert.throws(()=>E.choose(d,done,'deliver'));assert.ok(done.run.receipt.effect);}});
test('pickup missions begin empty and cannot deliver before collecting their protected cargo',async()=>{const {E,d,w}=await setup('romero-01');assert.deepEqual(w.run.cargo,{});let at=E.advance(d,w);assert.equal(at.run.pending.id,'reserva-recuento');at=E.choose(d,at,'count');assert.deepEqual(at.run.cargo,{'medical-case':1});assert.ok(at.run.flags.includes('reserva_cotejada'));at=E.choose(d,E.advance(d,at),'signal');at=E.choose(d,E.advance(d,at),'copy');let end=E.advance(d,at);end.run.cargo={};assert.throws(()=>E.choose(d,end,'deliver'),/incompleta/);});
test('tactical battle persists actor, targets, HP and resource costs across reload; retreat preserves unresolved passage',async()=>{const {E,d}=await setup();let w;for(let seed=0;seed<100;seed++){w=E.advance(d,E.start(d,atOrigin(d,connectedWorld(E,d,{seed}),'adasme-01'),'adasme-01'));if(w.run.pending.category==='hostile')break;}w=E.choose(d,w,'fight');assert.ok(w.run.pending.combat.enemies.length);const ammo=w.run.supplies.ammo9;w=E.choose(d,w,'fire');assert.equal(w.run.supplies.ammo9,ammo-1);assert.equal(w.run.pending.combat.actor,1);assert.deepEqual(E.restore(d,E.serialize(w)),w);const alerts=w.regions.oriente,index=w.run.index;w=E.choose(d,w,'smoke-retreat');assert.equal(w.run.index,index);assert.equal(w.regions.oriente,alerts);assert.equal(w.run.pending,null);w=E.advance(d,w);assert.equal(w.run.pending.category,'hostile');assert.equal(w.run.combats,1);});
test('victory opens an explicit loot phase, charges time per item, and uses individual actors',async()=>{const {E,d}=await setup();let w;for(let seed=0;seed<100;seed++){w=E.advance(d,E.start(d,atOrigin(d,connectedWorld(E,d,{seed}),'adasme-01'),'adasme-01'));if(w.run.pending.category==='hostile')break;}w=E.choose(d,w,'fight');const start=w.run.index,seen=new Set();for(let i=0;i<90&&w.run.pending?.combat?.phase==='combat';i++){seen.add(w.run.pending.combat.actor);const actions=E.options(d,w);w=E.choose(d,w,actions.some(x=>x.id==='fire')?'fire':'melee');}assert.equal(w.run.pending.combat.phase,'loot');assert.equal(w.run.index,start);assert.ok(seen.size>1);const drop=w.run.pending.combat.enemies.flatMap((e,i)=>e.loot.filter(x=>x.qty).map(x=>({i,id:x.id})))[0],before=w.run.minutes;w=E.takeLoot(d,w,drop.i,'rocio',drop.id);assert.equal(w.run.minutes,before+1);w=E.finishLoot(d,w);assert.equal(w.run.index,start+1);assert.throws(()=>E.finishLoot(d,w));});
test('permanent rewards change prices, individual bags and group progression',async()=>{const {E,d}=await setup();let w=connectedWorld(E,d,{seed:1});for(const id of ['romero-01','beatriz-01'])w=finish(E,d,E.start(d,atOrigin(d,w,id),id));assert.equal(E.price(d,w,'medkit'),6);assert.equal(E.price(d,w,'food'),3);assert.ok(w.crew.every(c=>c.level===2));w=finish(E,d,E.travelHeroes(d,w));const money=w.credits;w=E.buy(d,w,'medkit','tomas');assert.equal(w.credits,money-6);assert.ok(w.crew.find(c=>c.id==='tomas').bag.some(x=>x.id==='medkit'));w=E.start(d,atOrigin(d,w,'guzman-01'),'guzman-01');assert.ok(w.run.party.find(c=>c.id==='tomas').bag.some(x=>x.id==='medkit'));w=E.advance(d,w);assert.throws(()=>E.buy(d,w,'water','tomas'),/Los Héroes/);});
test('defeat recovers from checkpoint without erasing enemy rolls or regional alert',async()=>{const {E,d,w}=await setup();let lost=E.advance(d,w);lost.run.status='failed';lost.run.condition=0;lost.run.party.forEach(c=>c.hp=0);lost.regions.l6=2;lost.run.combats=2;const revived=E.retry(d,lost);assert.equal(revived.run.status,'active');assert.equal(revived.regions.l6,2);assert.equal(revived.run.combats,2);assert.ok(revived.run.party.every(c=>c.hp>0));assert.deepEqual(revived.run.rolls,lost.run.rolls);});
test('invalid courier and foreign save data are rejected without mutation',async()=>{const {E,d,w}=await setup();const raw=E.serialize(w);const bad=JSON.parse(raw);bad.run.party[0].hp=-1;assert.throws(()=>E.restore(d,JSON.stringify(bad)),/Mensajero/);assert.throws(()=>E.restore(d,JSON.stringify({version:3})));assert.equal(E.serialize(w),raw);});
test('purchased tools survive delivery without crafting; borrowed loadout is not farmable',async()=>{const {E,d}=await setup();let w=connectedWorld(E,d,{seed:1});const initial=id=>w.crew.reduce((n,c)=>n+c.bag.filter(x=>x.id===id).reduce((a,x)=>a+x.qty,0),0),food=initial('food'),water=initial('water');w.credits=40;w=E.buy(d,w,'trap','rocio');assert.ok(w.crew[0].bag.some(x=>x.id==='trap'&&x.qty===1));assert.throws(()=>E.craft(d,w,'trap'),/no pueden fabricar/);w=E.start(d,atOrigin(d,w,'romero-01'),'romero-01');w=finish(E,d,w);const totals=id=>w.crew.reduce((n,c)=>n+c.bag.filter(x=>x.id===id).reduce((a,x)=>a+x.qty,0),0);assert.equal(totals('trap'),1);assert.equal(totals('food'),food);assert.equal(totals('water'),water);});
test('returning a failed assignment cannot strand a penniless exhausted team',async()=>{const {E,d,w}=await setup();w.run.status='failed';w.run.party.forEach(c=>c.hp=0);assert.throws(()=>E.start(d,w,'adasme-01'),/interrumpido/);const returned=E.abandon(d,w);assert.throws(()=>E.start(d,returned,'adasme-01'),/Viaja/);const stopped=E.travelToMission(d,returned,'adasme-01');assert.equal(stopped.run.status,'failed');const next=E.retry(d,stopped);assert.ok(next.run.party.every(c=>c.hp>=Math.ceil(c.maxHp*.5)));assert.equal(next.credits,0);});
test('skill branches enforce costs, prerequisites, persistence and migrate old saves',async()=>{const {E,d,w}=await setup();assert.throws(()=>E.learn(d,w,'tomas','focus'),/anterior/);let n=E.learn(d,w,'tomas','echo');assert.equal(E.skillPoints(n.run.party[1]),0);assert.throws(()=>E.learn(d,n,'tomas','exit'));assert.deepEqual(E.restore(d,E.serialize(n)),n);n.run.status='failed';n=E.retry(d,n);assert.ok(n.run.party[1].skills.includes('echo'));const old=JSON.parse(E.serialize(w));for(const party of [old.crew,old.run.party,old.run.checkpoint.snapshot.party])for(const c of party)delete c.skills;assert.equal(E.skillPoints(E.restore(d,JSON.stringify(old)).run.party[1]),1);});
async function fightState(){const {E,d}=await setup();for(let seed=0;seed<100;seed++){let w=E.advance(d,E.start(d,atOrigin(d,connectedWorld(E,d,{seed}),'adasme-01'),'adasme-01'));if(w.run.pending.category==='hostile')return {E,d,w:E.choose(d,w,'fight')};}throw Error('No hostile seed');}
test('blind courier has lower accuracy; listening costs a turn, persists and improves melee only',async()=>{let {E,d,w}=await fightState();w.run.pending.combat.actor=1;const base=E.hitChance(d,w,'melee'),fire=E.hitChance(d,w,'fire');assert.ok(base<=.6);assert.ok(fire<=.45);const turn=w.run.pending.combat.turn;w=E.choose(d,w,'listen');assert.equal(w.run.pending.combat.turn,turn+1);assert.equal(w.run.pending.combat.actor,2);w=E.restore(d,E.serialize(w));w.run.pending.combat.actor=1;assert.ok(E.hitChance(d,w,'melee')>base);assert.equal(E.hitChance(d,w,'fire'),fire);w=E.choose(d,w,'melee');assert.equal(w.run.pending.combat.listening,false);});
test('guided retreat preserves passage and alert, reduces wear, and needs conscious Tomas',async()=>{let {E,d,w}=await fightState();const condition=w.run.condition,index=w.run.index,regions={...w.regions};let n=E.choose(d,w,'guided-retreat');assert.equal(n.run.index,index);assert.deepEqual(n.regions,regions);assert.ok(condition-n.run.condition<12);w.run.party[1].hp=0;assert.ok(!E.options(d,w).some(o=>o.id==='guided-retreat'));});
test('Los Héroes is required for trade, vendor stock goes to a chosen bag, and fabrication is disabled',async()=>{const {E,d,w}=await setup();assert.throws(()=>E.sell(d,w,'water','rocio'),/Los Héroes/);assert.throws(()=>E.travelHeroes(d,w),/Termina/);let n=E.abandon(d,w);n=finish(E,d,E.travelHeroes(d,n));n.credits=30;n=E.buy(d,n,'trap','tomas');assert.ok(n.crew.find(c=>c.id==='tomas').bag.some(x=>x.id==='trap'));const paid=n.credits;n=E.sell(d,n,'trap','tomas');assert.equal(n.credits,paid+4);assert.throws(()=>E.craft(d,n,'trap'),/no pueden fabricar/);assert.equal(d.recipes.length,0);});
test('travel time has a visible forecast and late delivery subtracts the configured penalty',async()=>{const {E,d,w}=await setup('romero-01',4);let n=finish(E,d,w),r=n.run.receipt;assert.equal(r.amount,r.gross-r.penalty);assert.equal(r.penalty,Math.min(Math.floor(r.gross*.5),Math.ceil(Math.max(0,r.minutes-r.timeLimit)/d.missions['romero-01'].late_step_minutes)*d.missions['romero-01'].late_penalty));assert.deepEqual(E.rewardForecast(d,n),{gross:r.gross,amount:r.amount,late:r.late,penalty:r.penalty,limit:r.timeLimit,minutes:r.minutes});});
test('acoustic detours consume limited charges which retry cannot refresh',async()=>{const {E,d}=await fightState();let w;for(let seed=0;seed<100;seed++){w=E.advance(d,E.start(d,atOrigin(d,connectedWorld(E,d,{seed}),'adasme-01'),'adasme-01'));if(w.run.pending.category==='hostile')break;}const hp=w.run.condition;w=E.choose(d,w,'echo-path');assert.ok(w.run.condition<hp);assert.equal(w.run.used.echo,1);w.run.status='failed';w=E.retry(d,w);assert.equal(w.run.used.echo,1);});
