const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {parseHTML}=require('linkedom');
const {connectedWorld}=require('./courier-fixtures.cjs');
async function setup(){const E=await import('../extensions/mensajeros/production.mjs'),{dossier}=await import('../extensions/mensajeros/dossier.mjs');const data=E.prepare(JSON.parse(fs.readFileSync('extensions/mensajeros/production.json')));return {E,data,view:(w,id)=>{const before=E.serialize(w),v=dossier(data,w,id,{image:(p,alt)=>`<img src="${p}" alt="${alt}">`,itemRows:s=>Object.entries(s).map(([key,n])=>`<i>${key}:${n}</i>`).join(''),progressHTML:()=>''});assert.equal(E.serialize(w),before,'Browsing must not alter the save');return {selected:v.selected,doc:parseHTML(v.html).document};}};}
test('fresh dossier exposes only known assignments and accepts at the real origin',async()=>{const {E,data,view}=await setup(),w=E.createWorld(data,{seed:1}),{doc,selected}=view(w,'beatriz-01');assert.equal(selected,'relevo-01');assert.equal(doc.querySelectorAll('.index-card').length,E.knownMissions(data,w).length);assert.equal(doc.querySelectorAll('[data-filter]').length,0);assert.ok(doc.querySelector('[data-accept="relevo-01"]'));assert.equal(doc.querySelectorAll('#dialogTitle').length,1);});
test('dossier selects all unlocked contacts and requires a journey before accepting remote work',async()=>{const {E,data,view}=await setup(),w=connectedWorld(E,data,{seed:1}),{doc}=view(w,'romero-01');assert.equal(doc.querySelectorAll('.index-card').length,8);assert.ok(doc.querySelector('[data-approach="romero-01"]'));assert.equal(doc.querySelector('[data-accept]'),null);assert.match(doc.querySelector('.preparation').textContent,/Primero debes llegar/);});
test('dossier states the borrowed field kit and warns when a short contract lends nothing',async()=>{const {E,data,view}=await setup(),w=connectedWorld(E,data,{seed:1});let doc=view(w,'guzman-01').doc;assert.match(doc.querySelector('.provisions').textContent,/food:1/);assert.match(doc.querySelector('.provisions').textContent,/water:1/);assert.match(doc.querySelector('.provisions').textContent,/ammo556:6/);assert.match(doc.querySelector('.loan-note').textContent,/vuelve a la red/);doc=view(w,'romero-01').doc;assert.match(doc.querySelector('.provisions').textContent,/no entrega comida/);});
test('active and interrupted assignments retain their accepted terms and prevent competing acceptance',async()=>{const {E,data,view}=await setup();let w=E.start(data,connectedWorld(E,data,{seed:1}),'relevo-01');w.run.timeLimit=39;for(const status of ['active','failed']){w.run.status=status;let {doc}=view(w,'relevo-01');assert.match(doc.querySelector('.facts').textContent,/39/);assert.ok(doc.querySelector('[data-resume]'));assert.equal(doc.querySelector('[data-accept]'),null);doc=view(w,'beatriz-01').doc;assert.ok(doc.querySelector('[data-resume]'));assert.equal(doc.querySelector('[data-approach]'),null);}});
test('delivered assignment opens its receipt, cannot pay again, and preserves selected identity',async()=>{const {E,data,view}=await setup(),w=connectedWorld(E,data,{seed:1});w.paid.push('relevo-01');w.completed['relevo-01']={startIndex:0,timeLimit:32};const {doc,selected}=view(w,'relevo-01');assert.equal(selected,'relevo-01');assert.ok(doc.querySelector('[data-receipt="relevo-01"]'));assert.equal(doc.querySelector('[data-accept]'),null);assert.equal(doc.querySelector('.tag').textContent,'Entregado');assert.equal(doc.querySelector('[aria-pressed=true]').getAttribute('data-offer'),'relevo-01');});
