const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const data=JSON.parse(fs.readFileSync(path.join(__dirname,'../extensions/mensajeros/data.json')));
const ready=import('../extensions/mensajeros/engine.mjs');
const make=(E,id='guzman-01',seed=2130)=>E.start(data,E.createWorld(data,{mode:'laboratory',seed}),id);
function step(E,w,{fight=false}={}){
 if(!w.run.pending)w=E.advance(data,w);
 if(w.run.status!=='active')return w;
 let opts=E.options(data,w).filter(x=>E.optionAvailable(w,x));
 let option=w.run.pending.combat?opts.find(x=>x.id==='fire')||opts.find(x=>x.id==='melee'):fight&&w.run.pending.category==='hostile'?opts.find(x=>x.id==='fight'):opts.find(x=>x.id==='assist')||opts.find(x=>x.id==='avoid')||opts.find(x=>x.id==='continue')||opts[0];
 return E.choose(data,w,option.id);
}
function finish(E,w){for(let i=0;i<160&&w.run.status==='active';i++){
 if(!w.run.pending&&E.here(data,w).rest&&w.run.condition<80&&w.run.supplies.food&&w.run.supplies.water&&!w.run.rested.includes(w.run.index))w=E.rest(data,w);
 w=step(E,w);
 }return w;}
test('archived lab remains inert; production is a separate entry and save',()=>{
 assert.equal(data.runtime_enabled,false);const npcs=JSON.parse(fs.readFileSync(path.join(__dirname,'../docs/metro-refugios/npcs.json')));assert.equal(npcs.runtime_enabled,false);
 for(const m of Object.values(data.missions)){assert.equal(m.enabled,false);assert.ok(npcs.npcs.some(n=>n.id===m.npc));const rt=data.routes[m.route];assert.equal(rt.edges.length,rt.nodes.length-1);rt.edges.forEach((e,i)=>{assert.equal(e.from,rt.nodes[i]);assert.equal(e.to,rt.nodes[i+1]);assert.ok(data.nodes[e.to]);});}
 for(const item of Object.values(data.items)){assert.ok(fs.existsSync(path.resolve(__dirname,'../extensions/mensajeros',item.image)));assert.equal(item.trade,false);}
 for(const file of fs.readdirSync(path.join(__dirname,'..')).filter(f=>/\.(html|js|css)$/.test(f)))assert.doesNotMatch(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),/mensajeros\.lab\.v1/);
});
test('canonical L6 order and route checkpoints are explicit',()=>{assert.deepEqual(data.routes['guzman-plaza'].nodes.slice(0,7),['leones','ines','nunoa','estadio','nuble','biobio','franklin']);assert.deepEqual(data.routes['guzman-plaza'].nodes.filter(id=>data.nodes[id].checkpoint),['leones','heroes','uchile','plaza']);assert.equal(data.nodes.provisorio.checkpoint,undefined);assert.equal(data.nodes.uchile.provisional,true);});
test('passive engine requires explicit lab start and protects mission cargo',async()=>{const E=await ready;assert.throws(()=>E.createWorld(data),/laboratorio/);let w=make(E);assert.deepEqual(w.run.cargo,{rotor:2,'motion-sensor':1});assert.throws(()=>E.start(data,w,'adasme-01'),/actual/);assert.equal(w.run.supplies.smoke,undefined);});
test('Adasme issues exactly 3 smoke bombs and a 20 minute inhibitor',async()=>{const E=await ready,w=make(E,'adasme-01');assert.equal(w.run.supplies.smoke,3);assert.equal(w.run.battery,20);assert.equal(w.run.jammerOn,false);});
test('pending roll is persisted and cannot be skipped by advancing again',async()=>{const E=await ready,w=E.advance(data,make(E));const restored=E.restore(data,E.serialize(w));assert.deepEqual(restored,w);assert.throws(()=>E.advance(data,restored),/Resuelve/);assert.deepEqual(E.advance(data,make(E)).run.pending,w.run.pending);});
test('quiet, decision and hostile content all occur across seeds',async()=>{const E=await ready,kinds=new Set();for(let seed=0;seed<200;seed++)kinds.add(E.advance(data,make(E,'guzman-01',seed)).run.pending.category);assert.equal(kinds.size,4);});
test('no third consecutive random hostile and no repeats where unused variants exist',async()=>{const E=await ready;let w=make(E);w.run.history=[{id:'merodeadores',category:'hostile'},{id:'patrulla',category:'hostile'}];w=E.advance(data,w);assert.notEqual(w.run.pending.category,'hostile');for(let seed=1;seed<30;seed++){let a=make(E,'guzman-01',seed);a.run.history=[{id:'silencio',category:'quiet'}];a=E.advance(data,a);if(a.run.pending.category==='quiet')assert.notEqual(a.run.pending.id,'silencio');}});
test('hostile evasion costs resources but does not count as combat',async()=>{const E=await ready;let w;for(let seed=0;seed<100;seed++){w=E.advance(data,make(E,'adasme-01',seed));if(w.run.pending.category==='hostile')break;}const before=w.run.supplies.smoke;w=E.choose(data,w,'smoke');assert.equal(w.run.combats,0);assert.equal(w.run.evaded,1);assert.equal(w.run.supplies.smoke,before-1);assert.equal(w.regions.oriente,0);});
test('combat marks alert once and retreat does not erase it',async()=>{const E=await ready;let w;for(let seed=0;seed<100;seed++){w=E.advance(data,make(E,'adasme-01',seed));if(w.run.pending.category==='hostile')break;}w=E.choose(data,w,'fight');assert.equal(w.run.combats,1);assert.equal(w.regions.oriente,1);w=E.choose(data,w,'fire');assert.equal(w.regions.oriente,1);w=E.choose(data,w,'smoke-retreat');assert.equal(w.run.combats,1);assert.equal(w.regions.oriente,1);assert.equal(w.run.pending,null);});
test('insufficient resources rejects atomically',async()=>{const E=await ready;let w;for(let seed=0;seed<100;seed++){w=E.advance(data,make(E,'adasme-01',seed));if(w.run.pending.category==='hostile')break;}w.run.supplies.smoke=0;const before=E.serialize(w);assert.throws(()=>E.choose(data,w,'smoke'),/recursos/);assert.equal(E.serialize(w),before);});
test('inhibitor only consumes narrative time while on; depletion never fails mission',async()=>{const E=await ready;let w=make(E,'adasme-01');w=E.advance(data,w);assert.equal(w.run.battery,20);w=E.toggleJammer(data,w);const before=w.run.minutes;w=step(E,w);assert.equal(w.run.battery,Math.max(0,20-(w.run.minutes-before)));w.run.battery=1;w.run.jammerOn=true;if(w.run.pending)w=step(E,w);if(!w.run.pending)w=E.advance(data,w);assert.equal(w.run.battery,0);assert.equal(w.run.jammerOn,false);assert.equal(w.run.status,'active');});
test('Guzman delivery only at endpoint; exact cargo consumed and payment once',async()=>{const E=await ready;let w=make(E);assert.throws(()=>E.choose(data,w,'deliver'),/instancia/);w=finish(E,w);assert.equal(w.run.status,'completed');assert.deepEqual(w.run.cargo,{});assert.equal(w.credits,40);assert.equal(w.run.receipt.recipient,'Técnicos de Plaza de Armas');assert.throws(()=>E.choose(data,w,'deliver'),/activo/);assert.throws(()=>E.start(data,w,'guzman-01'),/entregado/);});
test('incomplete cargo cannot be delivered and mutation is atomic',async()=>{const E=await ready;let w=make(E);while(w.run.status==='active'&&w.run.pending?.category!=='delivery'){if(!w.run.pending)w=E.advance(data,w);if(w.run.pending?.category!=='delivery')w=step(E,w);}w.run.cargo.rotor=1;assert.throws(()=>E.choose(data,w,'deliver'),/incompleta/);assert.equal(w.credits,0);});
test('both escort and carrying paths complete, stealth bonus requires zero fights',async()=>{const E=await ready,modes=new Set();for(let seed=1;seed<=12;seed++){let w=finish(E,make(E,'adasme-01',seed));assert.equal(w.run.status,'completed');assert.equal(w.credits,70);assert.equal(w.run.combats,0);modes.add(w.run.rescued.mode);}assert.deepEqual([...modes].sort(),['carry','escort']);let w=make(E,'adasme-01');w.run.combats=1;w.regions.oriente=1;w=finish(E,w);assert.equal(w.credits,40);assert.match(w.run.receipt.dialogue,/enfrentamientos/);});
test('rest costs provisions once and updates checkpoint',async()=>{const E=await ready;let w=make(E);w.run.condition=50;w=E.rest(data,w);assert.equal(w.run.condition,75);assert.equal(w.run.supplies.water,2);assert.equal(w.run.checkpoint.snapshot.condition,75);assert.throws(()=>E.rest(data,w),/descansaste/);});
test('defeat retry preserves rolls, threat and combat history but restores checkpoint stock',async()=>{const E=await ready;let w=make(E);w=E.advance(data,w);w.run.condition=0;w.run.status='failed';w.run.combats=1;w.regions.l6=1;const rolls=w.run.rolls;w=E.retry(data,w);assert.equal(w.run.index,0);assert.equal(w.run.condition,100);assert.equal(w.run.combats,1);assert.equal(w.regions.l6,1);assert.deepEqual(w.run.rolls,rolls);w=E.advance(data,w);assert.equal(w.run.pending.id,rolls[0].id);});
test('world threat carries into later journeys; unrelated corridor unaffected',async()=>{const E=await ready;let w=make(E);w.regions.oriente=2;assert.equal(E.effectiveRisk(data,w),'low');w=E.abandon(data,w);w=E.start(data,w,'adasme-01');assert.equal(E.effectiveRisk(data,w),'high');});
test('save rejects incompatible versions and negative supplies',async()=>{const E=await ready,w=make(E);assert.throws(()=>E.restore(data,'bad'));assert.throws(()=>E.restore(data,JSON.stringify({...w,contentVersion:'old'})),/incompatible/);w.run.supplies.water=-1;assert.throws(()=>E.restore(data,E.serialize(w)),/Inventario/);});
