const test=require('node:test'),assert=require('node:assert/strict'),{boot,root}=require('./runtime-harness.cjs');
const plain=x=>JSON.parse(JSON.stringify(x));
function session(options={}){const a=boot(new Map(),options),c=a.ctx;c.gameSessionActive=true;c.state.introCompleted=true;c.state.starterKitGiven=true;c.state.activity='story';for(const id of ['titleScreen','start','gameIntro','refuge','storyPrelude','activityMenu'])a.nodes.get(id).classList.add('hidden');c.state.index=c.veraIndex();c.save();c.render();return a}
function current(c){return c.eventDisplay(c.events[c.state.index],c.state.index)}
function resources(c){return JSON.stringify({party:c.state.party,res:c.state.res,morale:c.state.morale,threat:c.state.threat,stats:c.state.stats,faction:c.state.factionPoints})}
function topic(c,kind){c.choose(['line1','list'].includes(kind)?2:1);assert.ok(c.pending);assert.equal(c.veraTrade(),null);c.advance();assert.equal(c.npcDialogueState.dialogue.npc,'vera');c.revealNpcDialogueText()}
function trade(a,kind){const c=a.ctx;if(kind==='contract'){c.choose(3);assert.ok(c.pending)}else{topic(c,kind);const i=c.npcDialogueState.options.findIndex(o=>o._veraTrade===kind);assert.ok(i>=0);assert.equal(c.reason(c.npcDialogueState.options[i]),'');c.selectNpcDialogueChoice(i)}assert.equal(c.veraTrade().kind,kind)}
function finish(a){const c=a.ctx;if(c.decisionState)c.continueDecision();if(c.npcDialogueState){c.revealNpcDialogueText();if(!c.npcDialogueState.selected)c.selectNpcDialogueChoice(0);c.closeNpcDialogueAndContinue()}else if(c.pending)c.advance();if(c.pending)c.continuePendingAdvance();assert.equal(c.state.index,18);assert.ok(c.pendingNight());}
function bluff(a,success){const c=a.ctx;c.choose(0);assert.equal(c.decisionState.phase,'ready');c.random=()=>success?0:.99999;c.resolveDecision();a.timers.get(c.decisionFinishTimer).fn();assert.equal(c.veraTrade().kind,success?'bluff':'caught');}
function setup(c,kind){if(kind==='list')c.state.docs.push('names');if(kind==='debt')c.state.flags.savedHunter=true;if(kind==='work')c.placePartyItem('scrap',1);c.save();}
test('opening terms never exchanges data, grants rewards or invents a hunter debt',()=>{
 for(const menu of [1,2]){const a=session(),c=a.ctx,before=JSON.stringify({docs:c.state.docs,flags:c.state.flags,res:c.state.res,morale:c.state.morale,threat:c.state.threat,faction:c.state.factionPoints}),base=JSON.stringify(c.events[17]);current(c);c.render();assert.equal(JSON.stringify(c.events[17]),base);c.choose(menu);assert.equal(c.veraTrade(),null);assert.equal(JSON.stringify({docs:c.state.docs,flags:c.state.flags,res:c.state.res,morale:c.state.morale,threat:c.state.threat,faction:c.state.factionPoints}),before);assert.equal(c.hasPartyItem('radio'),false);assert.equal(c.pending.crate,undefined);const b=boot(a.storage).ctx;assert.equal(b.load(),true);assert.equal(b.veraTrade(),null);}
});
test('each actual exchange persists its costs, disclosure, night context and one radio',()=>{
 for(const kind of ['debt','work','line1','list','leave','contract']){const a=session(),c=a.ctx;setup(c,kind);const scrap=c.stockCount('scrap'),morale=c.state.morale;trade(a,kind);assert.equal(c.hasPartyItem('radio'),kind!=='leave');assert.equal(c.stockCount('scrap'),scrap-(kind==='work'?1:0));assert.equal(c.veraTrade().source,kind==='line1'?'home':kind==='list'?'archive-names':null);if(kind==='line1')assert.equal(c.state.morale,morale-10);if(kind==='list')assert.equal(c.state.morale,morale-6);assert.equal(!!c.state.flags.soldRefuge,['line1','list'].includes(kind));finish(a);const n=c.pendingNight();assert.ok(n.context.includes(c.veraTradeFact(c.veraTrade())));const b=boot(a.storage).ctx;assert.equal(b.load(),true);assert.equal(b.veraTrade().kind,kind);assert.equal(b.pendingNight().context,n.context);assert.equal(b.hasPartyItem('radio'),kind!=='leave');}
});
test('known home and a recovered old list disclose different facts; hearing about communities supplies no list',()=>{
 const a=session(),c=a.ctx;c.state.flags.knowsExiles=true;c.state.flags.knowOrigin=true;topic(c,'list');const list=c.npcDialogueState.options.findIndex(o=>o._veraTrade==='list');assert.match(c.reason(c.npcDialogueState.options[list]),/No han recuperado/);const before=resources(c);c.selectNpcDialogueChoice(list);assert.equal(c.veraTrade(),null);assert.equal(resources(c),before);c.selectNpcDialogueChoice(0);assert.equal(c.veraTrade().source,'home');assert.ok(c.state.narrative.knowledge.vera.includes('line1Access'));
 const b=session(),d=b.ctx;d.state.docs.push('names');trade(b,'list');assert.ok(d.state.docs.includes('names'));assert.ok(d.state.narrative.knowledge.vera.includes('historicalRefugeList'));assert.ok(!d.state.narrative.knowledge.vera.includes('line1Access'));assert.ok(!d.state.narrative.knowledge.vera.includes('refugeLocation'));assert.match(d.veraTrade().response,/fecha de hace|dieciocho meses/);
});
test('debt needs either real favor and repair requires a capable engineer plus an actual part',()=>{
 const a=session(),c=a.ctx;topic(c,'work');const before=resources(c);c.selectNpcDialogueChoice(0);c.selectNpcDialogueChoice(1);assert.equal(c.veraTrade(),null);assert.equal(resources(c),before);
 for(const flag of ['huntersTrust','savedHunter']){const b=session();b.ctx.state.flags[flag]=true;trade(b,'debt');assert.equal(b.ctx.state.flags.veraHonorsHunterDebt,true);}
 const b=session(),d=b.ctx;d.placePartyItem('scrap',1);d.state.party[1].hp=0;topic(d,'work');assert.match(d.reason(d.npcDialogueState.options[1]),/Elías necesita recuperarse/);d.selectNpcDialogueChoice(1);assert.equal(d.veraTrade(),null);assert.equal(d.stockCount('scrap'),1);d.selectNpcDialogueChoice(2);assert.equal(d.veraTrade().kind,'leave');assert.equal(d.veraTrade().witnessed,false);
});
test('packing cannot charge for a radio that cannot fit; repair may free its own slot and refusal stays available',()=>{
 const a=session(),c=a.ctx;c.state.party.forEach(p=>c.addToBag(p,'scrap',c.bagFree(p)));c.render();assert.match(c.reason(current(c).choices[0]),/Libera un espacio/);assert.match(c.reason(current(c).choices[3]),/Libera un espacio/);c.choose(0);c.choose(3);assert.equal(c.veraTrade(),null);trade(a,'work');assert.equal(c.hasPartyItem('radio'),true);
 const b=session(),d=b.ctx;d.state.party.forEach(p=>{p.bag=[];d.addToBag(p,'ammo9',d.bagCapacity(p));});topic(d,'leave');d.selectNpcDialogueChoice(2);assert.equal(d.veraTrade().kind,'leave');assert.equal(d.hasPartyItem('radio'),false);
});
test('an existing radio is acknowledged and never duplicated by a second payment',()=>{
 for(const kind of ['debt','work','line1','list','contract']){const a=session(),c=a.ctx;setup(c,kind);c.placePartyItem('radio',1);trade(a,kind);assert.equal(c.state.party.reduce((n,p)=>n+c.bagQty(p,'radio'),0),1);assert.equal(c.veraTrade().hadRadio,true);assert.match(c.veraTrade().response,/No reciben una segunda unidad/);if(c.npcDialogueState)assert.match(a.nodes.get('npcDialogueText').textContent,/No reciben una segunda unidad/);}
});
test('deception distinguishes Vera believing the lie from catching it without giving her a real address',()=>{
 for(const success of [true,false]){const a=session(),c=a.ctx;bluff(a,success);assert.equal(c.hasPartyItem('radio'),success);assert.equal(c.veraTrade().source,null);assert.equal(!!c.state.flags.huntersHostile,!success);assert.equal(c.state.flags.soldRefuge,undefined);assert.ok(!c.state.narrative.knowledge.vera?.includes('line1Access'));assert.match(a.nodes.get('decisionResolutionText').textContent,success?/sin saber que no conduce/:/no una ubicación verdadera/);c.continueDecision();assert.match(c.npcDialogueState.lines.join(' '),success?/No ha descubierto/:/No ofrece un segundo premio/);finish(a);assert.match(c.pendingNight().context,success?/a quién enviará/:/detectó el engaño/);}
});
test('reload rolls back the complete payment and duplicate input cannot add another transaction',()=>{
 const a=session(),c=a.ctx;setup(c,'work');trade(a,'work');const after=resources(c);c.selectNpcDialogueChoice(1);assert.equal(resources(c),after);const b=boot(a.storage).ctx;assert.equal(b.load(),true);assert.equal(b.veraTrade(),null);assert.equal(b.stockCount('scrap'),1);assert.equal(b.hasPartyItem('radio'),false);finish(a);const d=boot(a.storage).ctx;assert.equal(d.load(),true);assert.equal(d.stockCount('scrap'),0);assert.equal(d.hasPartyItem('radio'),true);
});
test('the reserved extraction is not a fulfilled rescue; realigning the relay records its cancellation',()=>{
 const a=session(),c=a.ctx;c.state.flags.relayPrepared=true;trade(a,'contract');assert.equal(c.state.flags.relayPrepared,false);assert.equal(c.state.flags.veraExtractionReserved,true);finish(a);const night=c.pendingNight().context;assert.match(night,/todavía no es un rescate cumplido/);c.settleNight('share');c.continueAfterNight();c.state.index=20;c.placePartyItem('battery',1);c.save();c.choose(3);assert.equal(c.veraTrade().cancelled,true);assert.equal(c.state.flags.veraExtractionReserved,false);assert.equal(c.state.flags.relayPrepared,true);assert.equal(c.state.expeditionRest.nights[2].context,night);assert.match(c.finaleStory('archive').refuge,/canceló la extracción/);assert.equal(c.veraTrade().source,null);
 const b=session(),d=b.ctx;d.state.flags.huntersHostile=true;assert.ok(d.reason(current(d).choices[3]));d.choose(3);assert.equal(d.veraTrade(),null);
});
test('disclosures remain in the ending without inventing an attack or turning an old list into current residents',()=>{
 for(const kind of ['line1','list']){const a=session(),c=a.ctx;setup(c,kind);trade(a,kind);finish(a);const record=JSON.stringify(c.veraTrade());c.state.flags.veraCleanRoute=true;c.state.flags.truthNotForSale=true;const story=c.finaleStory('archive');assert.match(story.refuge,kind==='line1'?/No hay noticias de un ataque/:/no tiene una comprobación reciente/);assert.equal(JSON.stringify(c.veraTrade()),record);assert.ok(c.state.flags.soldRefuge);}
});
test('old saves invent no transaction and malformed records are rejected without replacing storage',()=>{
 const a=session(),c=a.ctx;trade(a,'line1');finish(a);const valid=a.storage.get(c.KEY),old=JSON.parse(valid);delete old.companionCommitments.trade;a.storage.set(c.KEY,JSON.stringify(old));const b=boot(a.storage).ctx;assert.equal(b.load(),true);assert.equal(b.veraTrade(),null);assert.equal(b.veraNightContext(),'');
 for(const change of [r=>r.kind='rescued',r=>r.source='archive-names',r=>r.cancelled=true,r=>r.witnessed=null,r=>r.response=7]){const raw=JSON.parse(valid);change(raw.companionCommitments.trade);const text=JSON.stringify(raw);a.storage.set(c.KEY,text);assert.equal(boot(a.storage).ctx.load(),false);assert.equal(a.storage.get(c.KEY),text);}
 c.newGame();assert.equal(c.veraTrade(),null);
});
test('a restored resolved market can only continue without replaying the payment or spawning loot',()=>{
 const a=session(),c=a.ctx;setup(c,'debt');trade(a,'debt');finish(a);c.settleNight('share');c.continueAfterNight();delete c.state.expeditionRest.nights[2];c.state.index=17;c.save();const d=boot(a.storage).ctx;assert.equal(d.load(),true);d.gameSessionActive=true;assert.equal(current(d).choices.length,1);const before=resources(d);d.choose(0);assert.equal(resources(d),before);assert.equal(d.pending.dialogue,null);assert.equal(d.pending.crate,undefined);
});
test('real dialogue controls expose both conditions and the exit, with no reward before selection',()=>{
 const fs=require('node:fs'),path=require('node:path'),{parseHTML}=require('linkedom'),{document,window}=parseHTML(fs.readFileSync(path.join(root,'neosantiago-demo.html'),'utf8'));
 const a=session({document}),c=a.ctx,click=s=>document.querySelector(s).dispatchEvent(new window.Event('click',{bubbles:true}));assert.equal(document.querySelectorAll('#choices button').length,4);click('[data-choice="1"]');click('#advance');c.revealNpcDialogueText();assert.equal(document.getElementById('npcDialogueName').textContent,'Vera');assert.equal(document.querySelectorAll('[data-dialogue-choice]').length,3);assert.ok(document.querySelector('[data-dialogue-choice="0"]').disabled);assert.ok(document.querySelector('[data-dialogue-choice="1"]').disabled);assert.equal(c.veraTrade(),null);click('[data-dialogue-choice="2"]');assert.equal(c.veraTrade().kind,'leave');assert.equal(c.hasPartyItem('radio'),false);assert.match(document.getElementById('npcDialogueText').textContent,/sin su cobertura/);
});
